### ISSUE TITLE
Proper Xinput support.

### ISSUE THREAD

**Issue by WizLizard** [punesemu/puNES#1]
Would help for Xbox one controller users running Windows 10 as the driver for it is bugged when using dinput. For some reason the drivers for the controller are different in 10 compared to 8 and using 8's driver fixes the issue but causes others elsewhere. More of a request i suppose. Thanks!

**Comment by punesemu** [comment]
The problem is that I don't have a Xbox one controller with which to do testing. I'll have to find a way to get it.

**Comment by WizLizard** [comment]
@punesemu I'd be willing to donate to get it implemented.

**Comment by punesemu** [comment]
Many thanks @WizLizard, a help would be really appreciated.

**Comment by WizLizard** [comment]
@punesemu Ok i'll donate as soon as i can. Also i see that you labeled this issue as a bug, but i believe it is Widows 10 causing the bug and not the emu itself. I say this because other emus and even steam games with dinput are exhibiting this issue. Not sure if that matters when coming to the decision of lableing an issue.

**Comment by WizLizard** [comment]
Sorry accidentally closed the issue.

**Comment by punesemu** [comment]
After looking on google, I found that many people are having problems with the xbox one controller and windows 10. So you're probably right, it's not a bug emulator. I found this possible solution on the steam forum, try to look at the first post.

http://steamcommunity.com/app/274190/discussions/0/535152276584863931

**Comment by WizLizard** [comment]
@punesemu Thats funny I've already read that. My Windows 10 installation was a clean one, not an upgrade. The driver from windows 8 (Microsoft Xbox One controller) is only carried over from upgrading. Also like i said in my first post using it fixes the dinput but breaks other things. Windows 10 uses another driver by default but i don't remember the exact name of it and im not able to access my pc atm but will list the name when i can. So i think xinput support is a good idea for the emulator because many people likely use the xbox one controller running windows 10.

**Comment by WizLizard** [comment]
I can confirm that the driver that comes with Windows 10 is just called Xbox controller. Xbox Gaming, Device Version 10.x, Xbox Gaming Device Version 6.2.x and Microsoft Xbox One controller are drivers that come from previous installations of Windows and carried over through the upgrade. Here's a screenshot from my clean Windows 10 installation.

![screenshot 1](https://cloud.githubusercontent.com/assets/12180630/10360081/fc1720b6-6d6b-11e5-8e49-55099c2dd9c8.png)

**Comment by punesemu** [comment]
Ok, so I'll necessarily get an Xbox one controller.

**Comment by punesemu** [comment]
@WizLizard you can test one of this WIP please? Not knowing which version you use I put them all.

https://dl.dropboxusercontent.com/u/21595068/punes32.d3d9.exe
https://dl.dropboxusercontent.com/u/21595068/punes64.d3d9.exe
https://dl.dropboxusercontent.com/u/21595068/punes32.sdl.exe
https://dl.dropboxusercontent.com/u/21595068/punes64.sdl.exe

**Comment by WizLizard** [comment]
@punesemu I've been using 0.98. What changes have you made to these provided if any?

**Comment by punesemu** [comment]
This https://github.com/punesemu/puNES/commit/2e2c67c65613399d0f11f2ed1861791094c91828
I don't know if a bug or to increase the sensitivity of the axes Z and R, the new driver instead of returning the value 0x7FFF (JOY_RETURNCENTERED), for these two axes it returns 0 when not in use, which is not standard. I have implemented this type of management if emulator run in Windows 10 and use the driver of Xbox one controller.

**Comment by WizLizard** [comment]
Interesting, ok i'll test it when i get the chance.

**Comment by WizLizard** [comment]
@punesemu Fixed! Just curious though are you still willing to add actual xinput support?

**Comment by punesemu** [comment]
Not for now, what is implemented works well (as long as Microsoft does not go against his own rules, as in this case). There are other things I want to implement first. Thanks for the support. :)

**Comment by jcdenton2k** [comment]
As of Nov 2016 v1.01 WIP build, on Windows 7 the Xinput controllers are easily detected with all full axis and button layouts in the proper order.
