### ISSUE TITLE
freezes on opening program windows 10

### ISSUE THREAD

**Issue by ccampb** [punesemu/puNES#100]
Program gets hung up when it opens on windows 10.

**Comment by punesemu** [comment]
On all the windows 10 that I have tried I have not encountered problems so to help you I need as much information as possible. First, what version do you use (x32 or x64, d3d9 or opengl)? Are you trying 0.105 or WIP? Is this the first time you use puNES or have you updated from an old version? Does the emulator freeze completely or does it give you some kind of error message? If you freeze, you are able to screeshot the window (it could be useful to help me identify the problem). Does it freeze as soon as you start the emulator or when you try to open a rom?

**Comment by ccampb** [comment]
![punes](https://user-images.githubusercontent.com/20111993/77346947-498cb680-6cf4-11ea-9823-32d073a3bfae.png)
openGL, on a 64bit system, I believe it's WIP. First time using. It freezes completely, no error message

**Comment by punesemu** [comment]
Okay, we have some tests to do to identify the problem. What video card do you have? The problem may depend on its opengl drivers. I have attached a compressed file (https://www.dropbox.com/s/3n7xn932elw0o1z/punes64GL.zip?dl=0), unzip it in the folder and run it from a cmd, it's a debug version. Could you send me a picture of all the emulator's messages in the cmd? Take away another curiosity, do you have the same problem with the d3d9 version?

**Comment by ccampb** [comment]
Video card is an Intel HD Graphics 3000. When I run the debug version I
have no issues...
The d3d9 version is fine, but I really want to figure out this openGL
problem because I think that's why the version I want to ultimately be able
to run is having the same issue:

https://github.com/galchinsky/puNES

(sorry about delayed response, thanks for any help)

**Comment by punesemu** [comment]
So the debug release works smoothly, very strange. Kindly contact me privately at  punes[dot]development[at]gmail[dot]com.

**Comment by punesemu** [comment]
Graphic driver problem.
