### ISSUE TITLE
G++ error during compiling of v0.105

### ISSUE THREAD

**Issue by sidamo82** [punesemu/puNES#101]
I try to compile punes on ubuntu 16.04: I use g++ 9.2.1 20191102.
Compile failing with error below:

------------------------------------------------------------

qt.cpp: In function ‘BYTE gui_create()’:
qt.cpp:127:38: error: ‘class wdgScreen’ has no member named ‘devicePixelRatioF’; did you mean ‘devicePixelRatio’?
  127 |  gfx.device_pixel_ratio = qt.screen->devicePixelRatioF();

**Comment by punesemu** [comment]
It depends on the version of the installed QT libraries. Since the devicePixelRatioF function was introduced in version 5.6 you must have an even older one. What release of QT do you use?

**Comment by punesemu** [comment]
Closed for inactivity.
