### ISSUE TITLE
Rudimentatry FreeBSD support patch

### ISSUE THREAD

**Issue by TCH68k** [punesemu/puNES#103]
I tried to compile puNES on FreeBSD today. I hacked a FreeBSD=>OpenBSD fallback into the autoconfigure file and qt.cpp, and had added some tweaks in the joystick unit, so it builds, but crashes when i start the program. FreeBSD's USB stack has been replaced since 8.0, so it has become incompatible with OpenBSD's. I think, if USB support could be disabled during configuring/compiling, then a partial support for FreeBSD could be introduced as everything else just works fine, so FreeBSD users also could use puNES, but without USB support, at least until a FreeBSD dev fix that.

Patch is here: http://oscomp.hu/depot/punes_freebsd.patch

**Comment by punesemu** [comment]
I'd really like to add support for the freebsd. I could try installing freebsd on a virtual machine and try to play around with it even though I have never had to deal with this OS. Any advice on how I could get started?

**Comment by TCH68k** [comment]
FreeBSD 11 and 12 works good in VirtualBox 6, so you can try it on a virtual machine. If you need an already assembled VM image, you can download a few here: https://download.freebsd.org/ftp/releases/VM-IMAGES/12.1-RELEASE/amd64/Latest/
Although i have no experience about these particular images.

If you would like to install and configure the system as you want, then you can do the following:
First, download the image from here: https://download.freebsd.org/ftp/releases/amd64/amd64/ISO-IMAGES/12.1/FreeBSD-12.1-RELEASE-amd64-dvd1.iso
Then start VirtualBox and create a new VM. (I do not know if you're familiar with VBox or not, but just to be safe, i'll assume, you're not.)
Set the type to BSD and the version to FreeBSD (64-bit), give it at least 4096 MB of RAM and choose to create a new harddisk. (See: http://oscomp.hu/depot/vbox6_freebsd12_amd64_step_00.png)
The new harddisk should be at least 16 GB large. You can select either dynamic or fixed size, but keep in mind, that dynamic is slower (usually not noticeable). (See: http://oscomp.hu/depot/vbox6_freebsd12_amd64_step_01.png)
After it has been created, select it and click settings. Go to "Storage" and choose the downloaded DVD ISO as the Optical Drive and check "Live CD". (See: http://oscomp.hu/depot/vbox6_freebsd12_amd64_step_02.png)
Go to "Display" give the GFX card the maximum 128 MB RAM and select "VBoxVGA" as the "Graphics Controller". Ignore the warning beneath the panel. (See: http://oscomp.hu/depot/vbox6_freebsd12_amd64_step_03.png)
Then switch to the "System" and on that select the "Processor" tab. If you have a lot of cores, then you can give more than one to the VM, but that is not that important, what is important to check the PAE and the nested virtualization below. (See: http://oscomp.hu/depot/vbox6_freebsd12_amd64_step_04.png)

We're done with the setup. Start the VM. Let it boot and then select install. It may be a bit glitchy, just move the cursors sideways to make it right. (See: http://oscomp.hu/depot/vbox6_freebsd12_amd64_step_05.png)
Select your keymap, enter a name for your machine and then you can select what to install. (Use space to select/deselect entries.) You'll only need the "lib32" and "ports" components. (See: http://oscomp.hu/depot/vbox6_freebsd12_amd64_step_06.png)
Then you can select how you want to partition your drive. Select "Auto (ZFS)". Accept the default suggestions, then select the "stripe" option, as no redundancy needed here. (See: http://oscomp.hu/depot/vbox6_freebsd12_amd64_step_07.png and http://oscomp.hu/depot/vbox6_freebsd12_amd64_step_08.png)
Then select the drive you want to configure. (Don't forget to select the drive itself with Space before you hit Enter.) (See: http://oscomp.hu/depot/vbox6_freebsd12_amd64_step_09.png) Say okay to the warning and then let the system install itself. It's just a few moments.
Then you can give the system password and the network card you want to configure (since it's a virtual machine, only one will be available). Configure it for IPv4 and DHCP (just say yes two times). Say no for IPv6 and you can accept the offered configuration. (See: http://oscomp.hu/depot/vbox6_freebsd12_amd64_step_0a.png)
Then you can select your country and set the time and can set up what to run at boot. You don't really need sshd or kernel crash logs here for example, but you need dynamic CPU freqs and mouse support. (See: http://oscomp.hu/depot/vbox6_freebsd12_amd64_step_0b.png)
Then the system offers you a number of security settings. Just say OK, you don't want to harden a virtual system.
Then, if you want, you can add more users, but we don't really need this, you can use the system as root.
Then you'll get a summary and you can alter your previous settings. You can tell "Exit" the installer, we're done (and just skip the offered shell, we don't want to do anything extra).  (See: http://oscomp.hu/depot/vbox6_freebsd12_amd64_step_0c.png) Reboot.

Choose "Devices/Optical drives/Remove disk from virtual drive" from the menu, and "Force unmount" if you must.
Then let the system boot up (it may take a while at the first startup, until it gathers everything). Login as "root".
Let's install some development tools this way: "pkg install gcc gdb gmake autotools mc git pkgconf".
It will ask if it should install the package handler, of course it should.
Now, let's install X11, the desktop and the Qt5 configurator and Qt5 itself: "pkg install xorg lxqt qt5ct qt5".
And since you need SndIO and OpenGL to build puNES: "pkg install sndio freeglut".
(Of course you can install all these stuff in one step too.)
If everything is installed, then execute "echo 'ck-launch-session /usr/local/bin/startlxqt' > ~/.xinitrc", then type "startx". Choose "Openbox" for the window manager and you got the desktop.

Have fun!

**Comment by punesemu** [comment]
![puNES_on_FreeBSD](https://user-images.githubusercontent.com/14859058/80820225-c9048400-8bd6-11ea-8a39-ead144723721.png)
Thanks so much for the help. For the audio I used the Alsa backend (even if I have some problems) and on the support for the gamepads / joysticks there is some work to be done but already so I managed to start it.

**Comment by TCH68k** [comment]
Sounds great. Will you use SndIO in the final setup, or maybe it will be optional?

**Comment by punesemu** [comment]
First version of patch is ready [freebsd patch v1](https://gist.github.com/punesemu/4d655dea169bc93337ab623a3fc387c0#file-punes-freebsd-patch-v1-patch).
I did not like the alsa implementation for freebsd, much better sndio. To compile it's not necessary to install gcc you can safely use the clang.

**Comment by TCH68k** [comment]
It crashes at me with a segfault. Both on FreeBSD 11 and 12. I configured it with `--enable-release`.
I've ran it through GDB and this was the result after the segfault message:
```
<address> in vtable for __cxxabiv1::__si_class_type_info () from /lib/libcxxrt.so.1
```

ALSA on any BSD is merely an emulaion, of course SndIO is better.
I know GCC is not necessary, but usually CLang generates slower - albeit more reliable - code, than GCC.

**Comment by punesemu** [comment]
Really strange, I tried to compile a debug version and one for the release and both work without crash, but it is true that I used the clang for the compilation. I try to install the gcc hoping to be able to replicate the problem.

**Comment by punesemu** [comment]
Try this [freebsd patch v2](https://gist.github.com/punesemu/4d655dea169bc93337ab623a3fc387c0).

**Comment by TCH68k** [comment]
Normally for development i use CLang too, but for testing and releasing i use GCC, because the result is a bit faster and the compiler is buggy, so sometimes it brings up coding mistakes, which would have remained invisible otherwise.

The patch v2 works flawlessly. What exactly the problem was?

**Comment by punesemu** [comment]
I found out that On macOS and FreeBSD libc++ is the default standard library, so I've changed into configure.ac "-lstdc++" with "-lc++" and it worked. I compiled and started without problems with both clang and gcc.

**Comment by TCH68k** [comment]
I see. BTW, how did you manage to compile with CLang?
If i try to override `CC` and `CXX` from terminal, then `ld` ignores the libraries in `/usr/local/lib` and the configure script fails.

**Comment by punesemu** [comment]
In the patch I've added "/usr/local/lib" to the `LDFLAGS` so it's strange that `ld` ignores it. I use the command `CC=cc CXX=c++ ./configure` and I don't have problems.

**Comment by TCH68k** [comment]
It's not with your patch, i'm trying to compile puNES with my original stub patch, to see if it gives segfault with CLang too, or just with GCC. Merely out of curiousity. But if i override the local shell variables, then CLang do not find the SndIO library. When you first tried to build puNES with my patch using CLang, did the result work?

**Comment by punesemu** [comment]
```
[freebsd*], [
	LDFLAGS="${LDFLAGS} -L/usr/local/lib"
```
to your patch in `configure.ac` add this then make `./autogen.sh`

**Comment by TCH68k** [comment]
I see, thanks. It's not that important, i was just curious, that how much stuff you had to alter after using my initial patch to make the binary alive, so next time when i try to add another platform, i will not miss that step. It is somewhat a relief, that it was but one line.

**Comment by TCH68k** [comment]
Off: Can i ask for your email please? I would like to ask something in private.

**Comment by punesemu** [comment]
punes[dot]development[at]gmail[dot]com

**Comment by TCH68k** [comment]
Thanks.

**Comment by punesemu** [comment]
This is [freebsd patch v3](https://gist.github.com/punesemu/4d655dea169bc93337ab623a3fc387c0). I've added the support for the USB gamepads/joystick.

**Comment by TCH68k** [comment]
That was fast. Too bad i cannot test it, as i have no joysticks/gamepads.

I see that you had refactored the bsd directories into one. Porting puNES to other BSD-s will be easier henceforth. (I think actually puNES would work under NetBSD too now.)

**Comment by punesemu** [comment]
In master (https://github.com/punesemu/puNES/commit/e2a64f98ffc5d143e437b1f6744b6d488cbe4883)
