### ISSUE TITLE
puNES 0.105 doesn't allow input from my dualshock 4

### ISSUE THREAD

**Issue by Leonheart0819** [punesemu/puNES#104]
Hi, I really love your emulator and all but for some reason it doesn't register my inputs. It works for your older versions but not past 0.98. Thanks in advance.

**Comment by punesemu** [comment]
Hi, thanks for the report. Do you have the same problem with [WIP](https://github.com/punesemu/puNES#wip-builds--)?

**Comment by Leonheart0819** [comment]
WIP? Does that mean working in progress?

**Comment by punesemu** [comment]
Yes

**Comment by Leonheart0819** [comment]
I never used that. How can I access that?

**Comment by Leonheart0819** [comment]
Sorry about that but it's still giving me the same problem. IDK why.

**Comment by punesemu** [comment]
It's necessary that I find a dualshock 4 to be able to test. I will keep you up to date.

**Comment by Leonheart0819** [comment]
Gotcha.

**Comment by punesemu** [comment]
You can try [this](https://www.dropbox.com/s/qhsvc5gqwnah51x/punes64d3d9.zip?dl=1) version?

**Comment by Leonheart0819** [comment]
It still doesn't work for some odd reason.

**Comment by punesemu** [comment]
Try to calibrate the joystick and see if one of the axes gives you random values even if not used.

**Comment by punesemu** [comment]
I meant to try to calibrate the gamepad from your windows (as reported here [https://www.howtogeek.com/241421/how-to-calibrate-your-gaming-controller-in-windows-10/](https://www.howtogeek.com/241421/how-to-calibrate-your-gaming-controller-in-windows-10/)) and see if one of the axes gives you random values even if not used.

**Comment by punesemu** [comment]
You've tried?

**Comment by Leonheart0819** [comment]
Yes but for some reason I can't put it back to controller for Xbox 360. It
is just a "me" problem now.

**Comment by punesemu** [comment]
I consider it closed.
