### ISSUE TITLE
DX 11 / 32bit color / XAudio Up / Xinput AC

### ISSUE THREAD

**Issue by IPeluchito** [punesemu/puNES#105]
Please add support for **DX 11**, **32-bit color**, **XAudio update** and **Xinput automatic configuration** ...

**Thank you** for your work...

**God bless you.**

**Comment by RokkumanX** [comment]
You do realize what you are asking for is not as easy flipping a switch making all of these changes happen instantly.
It takes time and devotion.

The developer isn't working fully on this and is not getting paid at all.

I know you posted something similar here https://github.com/bsnes-emu/bsnes/issues/31 and I'm not going to repeat myself there.

I realize what you are after and understand your requests but again the developer have other things to work on these changes isn't 10 lines of code long.

Thanks for understanding!
