### ISSUE TITLE
Extra Scanlines for Removing Flickering/Lags

### ISSUE THREAD

**Issue by Catarax** [punesemu/puNES#11]
Like FCEUX emulator, a possibility to set a custom number of extra scanlines in order to avoid lags/flickering in game like Mega Man 3 since computers can handle that.

The experience with puNES would be awesome with that kind of feature.
Thanks!

**Comment by punesemu** [comment]
It is already on my list of things to do. Thanks for the support. :thumbsup:

**Comment by jcdenton2k** [comment]
As of the v1.01 WIP build of Nov 2016, this has been implemented in new UI options.

**Comment by Catarax** [comment]
Thanks, do you have recommended value to do it properly?

**Comment by jcdenton2k** [comment]
I usually use 100 for both Vblank Lines and Postrender Lines.
If you have a weaker system I'd say start with 25 and gradually increase it.
