### ISSUE TITLE
The Compiled 32-bit d3d9 exe with Github Code Cannot Run on Windows XP

### ISSUE THREAD

**Issue by owomomo** [punesemu/puNES#113]
When using 32-bit mingw to compile a 32-bit puNES, the created exe file cannot be run in Windows XP, it shows error "GetTickCount64 entry point could not be located on kernel32.dll".
My QT version is 5.6.3, gcc version is 9.1.0.

**Comment by punesemu** [comment]
Finded with google: https://answers.microsoft.com/en-us/windows/forum/windows_xp-winapps/windows-xp-error-entry-point-not-found/8d08d859-d0ef-46c9-950a-d5d2ca970ede

**Comment by owomomo** [comment]
> Finded with google: https://answers.microsoft.com/en-us/windows/forum/windows_xp-winapps/windows-xp-error-entry-point-not-found/8d08d859-d0ef-46c9-950a-d5d2ca970ede

I tried official puNES 0.106, it runs without problem on XP, but when I run the one compiled myself, the error shows.
Is there any configurations to do with the code to make it work, or some of my dependence libraries has version mismatch?

**Comment by punesemu** [comment]
I use the msys2 development environment to compile under windows and I have never encountered this problem with windows xp. If I have not misunderstood you instead use directly [MinGW](http://mingw.org/), right?

**Comment by owomomo** [comment]
> I use the msys2 development environment to compile under windows and I have never encountered this problem with windows xp. If I have not misunderstood you instead use directly [MinGW](http://mingw.org/), right?

I use MSYS2 either, and I found the 0.104 which I compiled much earlier doesn't have this problem, but when I recompile 0.104 in currently MSYS2, the error appears.
Since it's quite a long time and my compiling environment has been updated for several times, I can only guess that some of relying libraries changing caused this problem.

**Comment by punesemu** [comment]
To be honest, I compile all official versions under Linux with a cross compilation. Can you try one of the 32bit  [WIP](https://github.com/punesemu/puNES#wip-builds---) versions? Those are compiled through Appveyor under windows and always with an updated installation of the msys2 environment.

**Comment by owomomo** [comment]
> To be honest, I compile all official versions under Linux with a cross compilation. Can you try one of the 32bit [WIP](https://github.com/punesemu/puNES#wip-builds---) versions? Those are compiled through Appveyor under windows and always with an updated installation of the msys2 environment.

I found the solve on Github in https://github.com/msys2/MINGW-packages/issues/5139 . It is caused by the update of libpwinthread which stopped support for Windows XP, by downgrade the package to the older version, now the newly compiled program can run.
By the way, -release should be removed from QT compiling step in ./configure.bat command line, because mingw64 need libqtpcred.a and libqtharfbuzzngd.a for some unknown reason.

**Comment by punesemu** [comment]
1) I know, you're right, but not thinking that someone wanted to compile the 5.6.3 I have not reported the options that I used with the compile.bat
2) libqtpcred.a and libqtharfbuzzngd.a are debug version of libqtpcre.a and libqtharfbuzzng.a and I don't need debugging info especially for releases. For this reason I edit the pkgconfig files:
```bash
sed -i -e s,Qt5OpenGLd,Qt5OpenGL,g -e s,Qt5OpenGLExtensionsd,Qt5OpenGLExtensions,g -e s,Qt5Concurrentd,Qt5Concurrent,g -e s,Qt5Cored,Qt5Core,g -e s,Qt5Guid,Qt5Gui,g -e s,Qt5Networkd,Qt5Network,g -e s,Qt5PrintSupportd,Qt5PrintSupport,g -e s,Qt5Sqld,Qt5Sql,g -e s,Qt5Testd,Qt5Test,g -e s,Qt5Widgetsd,Qt5Widgets,g -e s,Qt5Xmld,Qt5Xml,g -e s,libqtpcre2d,libqtpcre2,g -e s,libqtlibpngd,libqtlibpng,g -e s,libqtharfbuzzd,libqtharfbuzz,g $MINGW_PREFIX/lib/qt5/pkgconfig/*
cp -v $MINGW_PREFIX/lib/qt5/pkgconfig/* $MINGW_PREFIX/lib/pkgconfig/.
```
These are the changes for QT 5.15.0 but I have done the same for 5.6.3
