### ISSUE TITLE
Qt 5.15.0 cannot be configured in MSYS2 with the command in Readme

### ISSUE THREAD

**Issue by owomomo** [punesemu/puNES#114]
When I compile and configure Qt 5.15.0 for puNES with the command in Readme.md, I got the following errors:

```
ERROR: Feature 'opengl-desktop' was enabled, but the pre-condition '(config.win32 && !config.winrt && !features.opengles2 && (config.msvc || libs.opengl))
                         || (!config.watchos && !config.win32 && !config.wasm && libs.opengl)' failed.`

ERROR: The OpenGL functionality tests failed!
You might need to modify the include and library search paths by editing QMAKE_INCDIR_OPENGL[_ES2],
QMAKE_LIBDIR_OPENGL[_ES2] and QMAKE_LIBS_OPENGL[_ES2] in the mkspec for your platform.

Check config.log for details.
```

I've tried MSYS2 version 20200720, 20200719, 20200629, 20200602, 20200522, 20200517 and 20190524, they all get the same error. All the command I executed was exactly same in Readme.md.

According to the config.log, it seems like some of the headers are missing, however I can't figure out what packages contains proper headers.
However, the older version of Qt CAN be configured and compiled with the same MSYS2. There might be something missing in the compiling instruction.

Since the older version of Qt is still compatible with the UI of puNES, I temporarily compile the code with Qt 5.10 now.

[config.log](https://github.com/punesemu/puNES/files/5003478/config.log)

**Comment by punesemu** [comment]
Your problem is that for some reason your msys2 environment is unhealthy since the configure cannot find the "GL/gl.h" package (as can be seen in your configure.log) which is installed by the mingw-w64-i686-headers-git and mingw-w64-x86_64-headers-git packages (which are installed by the mingw-w64-i686-toolchain and mingw-w64-x86_64-toolchain packages). I compiled the QT 5.15 16 days ago without problems with precisely those instructions, however for safety I could do a clean installation of the msys2 and try to recompile the QT to see if there is any problem.

**Comment by owomomo** [comment]
It's weird that mingw-w64-i686-headers-git and mingw-w64-x86_64-headers-git were already installed in my MSYS2, their versions are 8.0.0.5966.f5da805f-1.

**Comment by punesemu** [comment]
It 's really strange, I installed a clean msys2 environment following exactly the instructions given in readme.md from points 1 to 6 and the QT configure did not give me any errors. OpenGL includes are found and "OpenGL Desktop" support is enabled. I did all the tests with the 64bit shell of msys2. Did you do your test on a 32bit windows 7 SP1?

**Comment by owomomo** [comment]
> It's really strange, I installed a clean msys2 environment following exactly the instructions given in readme.md from points 1 to 6 and the QT configure did not give me any errors. OpenGL includes are found and "Desktop OpenGL" support is enabled. I did all the tests with the 64bit shell of msys2. Did you do your test on a 32bit windows 7 SP1?

No, I tested it on a 64bit Windows 7 SP1 with mingw64.

**Comment by punesemu** [comment]
The mystery continues. I created a virtual machine, installed win7 sp1 x64, installed msys2 environment following the points from 1-6 and I didn't find any problems. I attach both the config.log and a screeshot of the configure result:
![vboxwin7qt5](https://user-images.githubusercontent.com/14859058/89013513-4e055380-d314-11ea-9db6-6bcb0f9d0242.PNG)
[config.log](https://github.com/punesemu/puNES/files/5005802/config.log)

**Comment by owomomo** [comment]
> The mystery continues. I created a virtual machine, installed win7 sp1 x64, installed msys2 environment following the points from 1-6 and I didn't find any problems. I attach both the config.log and a screeshot of the configure result:
> ![vboxwin7qt5](https://user-images.githubusercontent.com/14859058/89013513-4e055380-d314-11ea-9db6-6bcb0f9d0242.PNG)
> [config.log](https://github.com/punesemu/puNES/files/5005802/config.log)

After comparing the log, I noticed that you compile Qt in MSYS2 home folder. I changed my qt folder location and now the problem was solved. Thank you.
