### ISSUE TITLE
Add PAL-shader (by r57shell) and ability to use RAW-palette with it

### ISSUE THREAD

**Issue by eugene-s-nesdev** [punesemu/puNES#116]
Hi, Fabio!
Can you integrate r57shell's PAL-shader to puNES?

![composite_bucky_green](https://user-images.githubusercontent.com/13199529/99146578-9e69ac80-268a-11eb-9d9a-d102b3b1a8cc.png)
![composite_btdd_title](https://user-images.githubusercontent.com/13199529/99146579-9f9ad980-268a-11eb-8116-e552244d804b.png)
![composite_btdd_lev3](https://user-images.githubusercontent.com/13199529/99146580-9f9ad980-268a-11eb-859e-7aa75ee8711b.png)

Shader can use classic RGB nes palettes, or RAW palette (give more authentic PAL colors!)

> The libretro ports of Nestopia, FCEUmm and Mesen have the option to output the raw chroma, level, and emphasis from the PPU through the RGB color channels. This by itself produces an image with completely bizarre colors, but this can be decoded by shaders to generate actual colors, the main examples being GTU-Famicom and nes-color-decoder.
http://emulation.gametechwiki.com/index.php/Famicom_Color_Palette

For use RAW mode you must uncomment line 70 of the
\pal\shaders\pal-r57shell.cg
`#define USE_RAW`

It's very GPU-intensive, so you can uncomment line 74 (optional) for use lookup-table (nes_lut.png):
`#define USE_LUT`
It's give less accurate colors, but still much closer to real PAL NES / Dendy than any existing external palette.
All of this stuff working ONLY when RAW-palette enabled.

Default shaders and presets paths example for cg-version:
```
\pal\pal-r57shell.cgp
\pal\shaders\pal-r57shell.cg
\pal\resources\nes_lut.png
```

**Links:**
**cg libretro repo:**
https://github.com/libretro/common-shaders/tree/master/pal
https://github.com/libretro/common-shaders/blob/master/crt/crt-royale-pal-r57shell.cgp
**glsl libretro repo:**
https://github.com/libretro/glsl-shaders/tree/master/pal
https://github.com/libretro/glsl-shaders/blob/master/crt/crt-royale-pal-r57shell.glslp
**slang libretro repo:**
https://github.com/libretro/slang-shaders/tree/master/pal
https://github.com/libretro/slang-shaders/blob/master/crt/crt-royale-pal-r57shell.slangp

**r57shell (developer) repo:**
https://gist.github.com/realmonster/b89e63d4018eb5bbab62331c42acf9e7

**Comment by punesemu** [comment]
Hi Eugene, I'm now looking at my implementation of sound of VRC7. As soon as I finish this I take a look at this shader.

**Comment by punesemu** [comment]
I've added the raw palette https://github.com/punesemu/puNES/commit/6344f1ddd7ff127faf57c3f316d86600a786636c.

**Comment by eugene-s-nesdev** [comment]
Strange things happens:

CG-shader, USE RAW, NO LUT:
![CG](https://user-images.githubusercontent.com/13199529/99285526-b129e000-2848-11eb-8e97-5d224d182401.png)

GLSL-shader, USE RAW, NO LUT:
![glsl](https://user-images.githubusercontent.com/13199529/99285544-b6872a80-2848-11eb-8cf5-c01ac46d49aa.png)

[_nes_palette_viewer.zip](https://github.com/punesemu/puNES/files/5548594/_nes_palette_viewer.zip)

**Comment by punesemu** [comment]
Fixed with https://github.com/punesemu/puNES/commit/d43db8df1d95f96cc6286473ad2a8ef14f023924.

**Comment by punesemu** [comment]
Fix that fixes the fix https://github.com/punesemu/puNES/commit/a25c65e962f6c0dfce9a222427a4d652c4cad59e.
Thanks to your request I found and corrected some bugs concerning the management of the shaders and the initialization of the graphics palette (this has been around for a very long time but I never noticed it). I thank you infinitely

**Comment by eugene-s-nesdev** [comment]
Thank you very much, i'll test evening
Can you test CRT-Royale on your machine, i can't get work it with puNES: (loading error, no shader)
but on Retroarch it works (i have nvidia 1050ti so it capable to run it)

I mean:
`/crt/crt-royale-pal-r57shell.cgp`
But this folder have other very nice stuff, including NTSC too


[crt+ntsc+pal.zip](https://github.com/punesemu/puNES/files/5551644/crt%2Bntsc%2Bpal.zip)

**Comment by punesemu** [comment]
The shader loading error I referred to in the previous message concerned the CRT-Royale that before this commit https://github.com/punesemu/puNES/commit/9bdae97d7c8966f3995c8c03fcace628d9f450dc no longer worked in the OpenGL version. I have verified that after the fix and it works correctly (opengl driver permitting) on three different computers. Actually on the D3D9 version the shader compiler gives me an error on which I will investigate. But the OpenGL version doesn't work for you either?

**Comment by eugene-s-nesdev** [comment]
I tested lastest punes64.wip.opengl on win10, nvidia 1050
raw palette fixed now, all CG and GLSL pal-r57shell works good

but Royale-crt don't work,
when loading CG-version, it give error (errors on shader, use "no shader")
when loading GLSL-version, puNES crashes.

**Comment by eugene-s-nesdev** [comment]
Uh sorry, i had not full package. All works good on Win10 opengl

**Comment by punesemu** [comment]
The problem with D3D9 version is that the CG shader is not compatible with the DirectX9. I can't do anything about it.

**Comment by punesemu** [comment]
In any case, I really like the PAL-shader, the visual effect is impressive.

**Comment by eugene-s-nesdev** [comment]
I really don't know is it worth integrate only r57shell into punes, or not. 
There a lot other very quality shaders in package, including NTSC too.
But anyway, thanks for good-working RAW-palette, i tested, it fixed now.

**Comment by punesemu** [comment]
I don't think I will integrate it natively in puNES, the shaders I use are quite simple and are compatible with both D3D9 and OpenGL (even with relatively old drivers) while this is rather "complex". In any case it will be possible to use it via an external shader thanks to your report.

**Comment by eugene-s-nesdev** [comment]
Yes, keep up good work!
