### ISSUE TITLE
Input doesn't work when "rotate screen" activated

### ISSUE THREAD

**Issue by eugene-s-nesdev** [punesemu/puNES#117]
I've found a bug

When you rotate screen via GUI, window focus lose, so input doesn't recongize.
Need to click mouse on game-area window, to re-activate input.

Also interesting suggestion:
since puNES already have rotation, would be funny add "flip" function that will mirror gameplay area.
(left and right key input must be swapped for this mode, i guess)

![Безымянный](https://user-images.githubusercontent.com/13199529/99384892-2ba63e80-28e1-11eb-968e-0dca4ed37a10.png)

I saw this idea here:
http://www.emu-land.net/forum/index.php/topic,76586.0.html

**Comment by punesemu** [comment]
Fixed https://github.com/punesemu/puNES/commit/8b5af1ddb249807ffe450030667597d992fd68d9. It has been a long time since you reported so many bugs. I missed you :). It's a great idea! I could put an option to automatically "follow" the rotation to the input.

**Comment by eugene-s-nesdev** [comment]
Personally i don't use flip or rotation, but looked at that topic, i guess it will be interesting for someone!

> I could put an option to automatically "follow" the rotation to the input.
I guess it will be good idea.

**Comment by punesemu** [comment]
I have implemented rotation mostly for this http://forums.nesdev.com/viewtopic.php?f=22&t=16688. And since it's now there, the input flip seems like a great idea to me.

> P.S. i've donated, you have great emu
> thanks for good work

Many Thx Eugene :wink:

**Comment by eugene-s-nesdev** [comment]
> I have implemented rotation mostly for this http://forums.nesdev.com/viewtopic.php?f=22&t=16688

![gratis-png-emoticon-sonriente-ojos-saltones-expresion-sorprendida](https://user-images.githubusercontent.com/13199529/99388640-f4d32700-28e6-11eb-9b7a-75d7eac6e78f.png)

First time i see something like that

**Comment by punesemu** [comment]
Satisfy my curiosity, like the possibility to record audio in different formats? Or was it better to leave support for the WAV format only?

**Comment by eugene-s-nesdev** [comment]
Personally i use WAV, then edit (trimming, fade-out etc.) it in DAWs, then convert to anything else (FLAC/mp3/ogg)
But i guess some people want to dump audio directly to mp3.

**Comment by punesemu** [comment]
> Personally i use WAV, then edit (trimming, fade-out etc.) it in DAWs, then convert to anything else (FLAC/mp3/ogg)
> But i guess some people want to dump audio directly to mp3.

I figured you would have answered me like this, since you are an audio lover. :smiley: 

> Regarding puNES, i think libretro-port with bunch-of core-options will be useful for people.
> Since cycle-accurate mesen, nestopiaue good, but both dead now.

As for retroarch I have thought about it more than once but there are several reasons that have always held me back. If you like, we'll talk about it in private some more time.

> By the way, BIG thanks for fixing nestopia ppu routine some years ago, i use it on RPi3b+/lakka and enjoy it.

You are welcome :+1:

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/1b86c31906f79512a6a62296ceb489199bb42f39

**Comment by eugene-s-nesdev** [comment]
Looks amazing, i will test it.
P.S.: I sent email to punes.development@gmail.com

**Comment by eugene-s-nesdev** [comment]
Something wrong with input rotation logic, try to test 240pee.nes "shadow sprite" U/D/L/R
for example in all rotation modes:
http://forums.nesdev.com/viewtopic.php?f=22&t=13394&sid=2ded47d9e2c6976a9379170b52a46ff3&start=165#p259370

**Comment by punesemu** [comment]
Fixed https://github.com/punesemu/puNES/commit/e83316d2733ea8a6618ed58f32076af0ebc89eef.
