### ISSUE TITLE
Windows Defender detects WIP builds as a virus

### ISSUE THREAD

**Issue by zachdwyer** [punesemu/puNES#119]
The downloads for at least the 64 bit versions of this app on the main page are detected as **Trojan:Win32/Spursint.F!cl** by Windows Defender. I'm sure (hopefully) it's a false positive but I figured the issue should be made aware.

**Comment by punesemu** [comment]
It's absolutely a false positive. WIPs are compiled from source automatically through the appveyor service every time I push a commit. [Here](https://ci.appveyor.com/project/punesemu/punes) you can find the build logs and [here](https://github.com/punesemu/puNES/blob/master/appveyor.yml) he build script. Thank you so much for the report, I will try to understand what the report comes from even if I think it may depend on the FFmpeg libraries which are the only thing recently added.

**Comment by punesemu** [comment]
Maybe [this](https://answers.microsoft.com/en-us/protect/forum/protect_defender-protect_scanning-windows_10/my-software-is-being-falsely-flagged-for/3a7a1d95-0c26-4b5b-92a6-9b49bc475bd1) would explain the false positive.

**Comment by punesemu** [comment]
https://www.microsoft.com/en-us/wdsi/submission/8922eb22-e66e-41ab-9670-e3c92db8babd
https://www.microsoft.com/en-us/wdsi/submission/3a427603-1860-4c5a-8ece-4f383c38251d
Microsoft removed the false positive.
