### ISSUE TITLE
Super Mario Bros 2 (Japanese Version) Broken

### ISSUE THREAD

**Issue by Catarax** [punesemu/puNES#12]
**Version 0.99 :**
**Japanese version of Super Mario Bros 2**
![h3kldph](https://cloud.githubusercontent.com/assets/3964507/14574308/21116e32-035b-11e6-85ea-d2017ad86309.png)

**Comment by punesemu** [comment]
Fixed in commit [8b8e78b](https://github.com/punesemu/puNES/commit/8b8e78b3e478879dabdfcc748542765ac85a56e5). Thx for the report.

**Comment by Catarax** [comment]
Good job!
Is it possible to get a new official compiled version of punes with this fix?
Thanks! Else, i'll wait the new version.

**Comment by punesemu** [comment]
A new official release no but I can give you a WIP. Which version? (windows? Linux? OpenGL? D3D9?)

**Comment by Catarax** [comment]
No probs.
Windows 64 SDL, thanks!

**Comment by punesemu** [comment]
[puNES win64 SDL 0.100 WIP ](https://dl.dropboxusercontent.com/u/21595068/punes64.0100wip.sdl.zip)
