### ISSUE TITLE
Option to set dead zone for analog sticks

### ISSUE THREAD

**Issue by Zerowalker** [punesemu/puNES#121]
A feature request to allow you to set a dead zone for the analog stick (if you use one).
I use an xbox one controller for example, and i guess the stick is crap but sometimes if i turn right for example and release the stick,
the stick will just barely hit left when it returns to the center, making the character turn left.

Currently playing Metroid and this is very frustrating when i want to turn quickly and shoot, and then notice that the character just turned 2 times;P

This is not a complaint on the emulator in anyway of course, analog sticks are far from ideal these inputs as they are basically buttons.
I just like to use the same controller for everything so just wanted to make a request for a feature that could help alleviate some issues with using analog sticks for buttons.

Love the emulator, keep up the good work:)!

**Comment by punesemu** [comment]
Hi Zerowalker, thanks for reporting and for the compliments. If I can, during the weekend, I will try and study the problem. I will keep you updated.

**Comment by Zerowalker** [comment]
Thanks, i just beat the game but of course i would still want it!
No pressure of course, look into it when you feel like it, don't want it to feel like i am making demands:)

A separate question if i may.
What's the difference between 0 and 1 in the audio buffer settings?
i always have it at 0 as it seems to work, but not sure if it may cause issues that i just don't know about,
or if it's supposed to start clipping if there was an issue (which is normally the case with audio buffering, if you have too low it can't keep up and you get sudden silence which ends up sounding like clipping or pops).

**Comment by punesemu** [comment]
That setting indicates the size of the audio buffer, increasing this increases the size of the audio buffer. With a small buffer, on less powerful CPUs, pops and crackles are possible because it doesn't fill up fast enough. By increasing its value you will also increase the latency of the audio, the audio is delayed compared to the video but no more pops. If you have no problems with the setting to 0, continue to use it quietly, it means that your CPU is fast enough

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/01675d7226c250341b4d85613a7a612417ef3020
Can you try the new WIP? You must first reconfigure the standard pad because I have completely rewritten the gamepds management.
