### ISSUE TITLE
cannot compile master 16.04.2016

### ISSUE THREAD

**Issue by luntik2012** [punesemu/puNES#13]
./autogen.sh && ./configure

./configure: line 6302: syntax error near unexpected token `noext'

./configure: line 6302: `AX_CXX_COMPILE_STDCXX_11(noext)'

**Comment by punesemu** [comment]
You need that package "autoconf-archive" is istalled.

**Comment by Marc34** [comment]
Same problem here and "autoconf-archive" is istalled.

**Comment by punesemu** [comment]
Sorry if I answer only now. You can try to compile with these sources? If it does not give you the error I will apply the patch to the master.
https://dl.dropboxusercontent.com/u/21595068/puNES-master.zip

**Comment by Marc34** [comment]
It works now with this these sources, no more error, emulator works fine.

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/5f9fec7170fa48f4564c33e481ac670cd43b529b Thx for the support.
