### ISSUE TITLE
[Feature Request] Add frame/lags counters

### ISSUE THREAD

**Issue by BroDMax** [punesemu/puNES#130]
Hi! Can you add frame counter and lags counter on screen? For example, near FPS. I think, it would be great feature for speedruns or videos. Thanks.

**Comment by punesemu** [comment]
Like this https://github.com/punesemu/puNES/commit/68f542ef6947965006f4fff3a9ca708f3562807d? If you want you can try the [WIPS](https://github.com/punesemu/puNES#wip-builds---) and tell me what you think.

**Comment by BroDMax** [comment]
Conveniently to use WIP version! I checked it out – looks awesome! 😊
