### ISSUE TITLE
Famicom Disk System emulation doesnt work

### ISSUE THREAD

**Issue by AlexN64gamer** [punesemu/puNES#134]
When trying to load the Super Mario Brothers 2 Japanese FDS version it gives the same error "Ilegal opcode 0x02 at 0xED96" I have the FDS bios assigned in the emu config and set the region to NTSC, is there something im doing wrong? or the emulator just doesnt support FDS yet

Thanks in advance.

**Comment by punesemu** [comment]
The emulator supports FDS and I loaded "Super Mario Bros. 2 (1986) (Nintendo) (J) .fds" without any problem. Contact me at the email address associated with this account and send me the rom you are trying to upload, I think that's the problem, a corrupted rom.

**Comment by AlexN64gamer** [comment]
Ive already sent you an email, thanks a lot ¡¡

**Comment by punesemu** [comment]
I have't received any mail with the rom. You can send me at "punes dot development at gmail dot com".

**Comment by AlexN64gamer** [comment]
this is the email adress I sent the FDS rom and the Bios files: punes.development@gmail.com

**Comment by AlexN64gamer** [comment]
Thanks a lot mate, now it works flawless :)

**Comment by AlexN64gamer** [comment]
It is working now thanks another FDS bios, I had dumped my own disk system unit bios, so I dont know, maybe it got corrupted in the process, however thanks a lot @punesemu
