### ISSUE TITLE
Occasionally get "error loading state" with frequent save state usage

### ISSUE THREAD

**Issue by mariomadproductions** [punesemu/puNES#136]
In a hacked SMB ROM, I occasionally get "error loading" state after frequent save state loading. After this happens once, it happens every time I try to load a state, until I create a new one. Version: v0.107. I can't seem to recreate it on purpose, but it has happened a few times.

**Comment by punesemu** [comment]
Sorry if I answer you just now but I haven't been home in this period. Can you send me one of the corrupt save states, your puNES.cfg and the rom?

**Comment by mariomadproductions** [comment]
Yeah, if I manage to get this error again, I'll send those.

**Comment by punesemu** [comment]
No other info. If the problem recurs, reopen the issue.
