### ISSUE TITLE
Dragon Ball Z Gekito Tenkaichi Budokai

### ISSUE THREAD

**Issue by Catarax** [punesemu/puNES#14]
Error Loading Rom

Seems that DATACH system is not supported by the emulator.

**Comment by punesemu** [comment]
The rom that I have works perfectly. Sure you don't have a corrupt rom?

**Comment by Catarax** [comment]
Thanks! It looks that Punes is much more sensitive than others emulators at this point.
So, i think it'll be better to write "Error: Corrupted Rom" rather than "Error Loading Rom" if you're able to detect it.

**Comment by punesemu** [comment]
Most likely you will have the header of the rom corrupted. This will indicate to the emulator wrong information on the size of "prg rom" or "chr rom" or both. From these incorrect information comes the "Error Loading Rom".
