### ISSUE TITLE
Doesn't recognize USB HID joysticks

### ISSUE THREAD

**Issue by groundflyer** [punesemu/puNES#141]
I have a retro USB joystick that detected by linux as "USB HID v1.10 Joystick [usb gamepad]", but when I'm trying to configure the joystick in puNES the ID option shows "No usable device".

**Comment by punesemu** [comment]
Hi, unfortunately I can't replicate the problem. Contact me privately at the email address associated with the github account, if you agree we could do a remote assistance on your computer so we can investigate the error.

**Comment by punesemu** [comment]
No reply.
