### ISSUE TITLE
Unlimited Sprites not enough powerful

### ISSUE THREAD

**Issue by Catarax** [punesemu/puNES#15]
In games like Megaman 3 (Topman Level), although it seems a little bit better, there is still massive slowdowns with Unlimited Sprites.

**Comment by punesemu** [comment]
In Mega Man 3 slow down are well known (and they are also present on an original nes) and do not depend in any way by the new option. There would be the same even with the option disabled. To eliminate them there are other tweak I can implement (like [http://forums.nesdev.com/viewtopic.php?f=3&t=12823](http://forums.nesdev.com/viewtopic.php?f=3&t=12823)). As regards the power of the new option, more than at the same time support the maximum number of sprites managed by nes (64), I do not see what else I can do. Moreover, the number of CPU cycles that this management adds do not affect on the performance of the emulator (as regards megaman 3, the additional sprites for scanlines ranging from a minimum of 1 to a maximum of 6/7 so really small thing).
