### ISSUE TITLE
Obscure input regression

### ISSUE THREAD

**Issue by eugene-s-nesdev** [punesemu/puNES#151]
Hi Fabio.
I’ve discovered obscure regression happens somewhere between 28.12.2020 and current builds. 
I deleted config especially for fresh test.
Tested opengl and D3D builds on two different desktops under win10-ltsc yet, but need to do it on more systems though.
 
Step-by-step:
Unpack fresh build, delete config, set your preferred inputs
in my case there are:
A = X
B = Z
TurboA = S
TurboB = A
Select = RShift
Start = Enter
 
Try to play game where «B» button uses as «charge», for example bucky o’hare.
Just move there and there, use turbo, etc. 
You’ll see that «B» button will gets stuck randomly. 
Your personage will charge energy at random moment even when you’re not pressed «B» at all

**Comment by punesemu** [comment]
Hi Eugene, as soon the bot finishes completing the build please try and let me know.

**Comment by eugene-s-nesdev** [comment]
>Воскресенье, 20 июня 2021, 17:54 +03:00 от Fabio Cavallo (FHorse) ***@***.***>:
> 
> 
>Hi Eugene, as soon the bot finishes completing the build please try and let me know.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
Sure!
Also, does punes github webpage have link to appveyor status, like this https://ci.appveyor.com/project/zeromus/fceux
 
--
С уважением,
системный администратор АО "Спецремтранс"
Сергунов Евгений Вячеславович.
+7 (925) 825-62-61

**Comment by punesemu** [comment]
Already there, the "build" badge which is next to the "WIP Builds" header not only indicates the status of the build but is also a link. But I realize it's not very intuitive, I could put a direct link.

**Comment by eugene-s-nesdev** [comment]
> Hi Eugene, as soon the bot finishes completing the build please try and let me know

It's fixed, thank You

**Comment by punesemu** [comment]
Thanks to you for the report. Now I can watch the football match. :smile:
