### ISSUE TITLE
Bad segfault UwU

### ISSUE THREAD

**Issue by MikuChan03** [punesemu/puNES#153]
Um, hi~~ ✨

So thewe is this issue, which is like bad and stuff!
I am of cause talking about
`swc/gui/linux/monitow.c in function gui_monitow_enum_monitows`
As it tuwn out, the function XWWGetCwtcInfo can fail O.O
In that case, it wetuwns NULL.
Following that, using the "ci" vawiable in the loop causes a bad segfault 😠
Fow whatevew weason, my computow is affected by that.
So I want to humbly ask you senpais to indulge in my onegai!
If we whewe to put

```c
if (ci == NULL){
  continue;
}
```
in the main loop of the mentioned function, evewything would be peachy cweamy.
All hunky-dowy!

Thanks in advance!

Bye bye  💕

XXX

**Comment by MikuChan03** [comment]
That oughta do it.

**Comment by punesemu** [comment]
Hi MikuChan, thx for your report. I can't access the code for the next three days, I'm not home, but as soon as I get back, I'll take a look at your report. Can you tell me what video card you have?

**Comment by MikuChan03** [comment]
Yes can do! It's this thing:
`Intel® HD Graphics 3000`
I am on a thinkpad t420 with integrated graphics.
