### ISSUE TITLE
Separate "Fast Forward" shortcuts

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#155]
Could you please rename the current "Fast Forward" shortcut to "Toggle Fast Forward", and then add a new "Fast Forward (hold button)" shortcut?

**Comment by punesemu** [comment]
Yes, of course I can, but just out of curiosity, why do you need two?

**Comment by anewuser** [comment]
I don't, but I wouldn't ask you to replace a feature you like with something else! Having both options will make everyone happy.

**Comment by anewuser** [comment]
We're used to hold a key down to fast forward on other emulators like bsnes and MAME.

**Comment by GreyFoxGer** [comment]
I was very disappointed too... always used to hold a key, then release it.
Would be great if you could still implement this.

It would be also awesome to having and hotkey for saving into Slot 1-9 and load them separately.


Great Emulator!

**Comment by punesemu** [comment]
> I was very disappointed too... always used to hold a key, then release it.
> Would be great if you could still implement this.

Ok, I'll see what I can do.
>It would be also awesome to having and hotkey for saving into Slot 1-9 and load them separately.

Mmmm 1 hotkey to save and 1 to load? 18 hotkeys?

**Comment by anewuser** [comment]
>Mmmm 1 hotkey to save and 1 to load? 18 hotkeys?

Some emulators indeed let people set that many hotkeys (<kbd>Shift</kbd> + <kbd>1</kbd>, <kbd>Shift</kbd> + <kbd>2</kbd>, etc.), like mGBA:

<details>
  <summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/6733770/180856546-9d301594-13fc-4b46-8f96-19887283ea3c.png"> 
</details>

puNES already has a nice GUI for using multiple save slots, though:

![puNES](https://user-images.githubusercontent.com/6733770/180857883-ed86a5cf-0806-48ba-b038-592dd36f4106.png)


Instead of hardcoding dozens of new hotkeys, I think it's a better idea to add just one new hotkey to show this save gallery. You can then make it accessible with the player's customized controller and show what buttons should be pressed to save or load the selected slot, as in official save screens:

![example](https://user-images.githubusercontent.com/6733770/180859712-c68e1cf4-9b07-4873-92a6-ae33294c70f8.jpg)


This would make this feature accessible to everyone, including children using gamepads with the toolbar hidden.

**Comment by punesemu** [comment]
"Fast Forward (hold button)" shortcut https://github.com/punesemu/puNES/commit/fcc0d83ad2bfa847e069e2f8bef3c14f4efaaa8e.

**Comment by anewuser** [comment]
Thank you! Maybe you can now move @GreyFoxGer's request to a separate issue and close this one.
