### ISSUE TITLE
Automatically fast forward and switch disks/sides for FDS games

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#156]
Could you implement these options from Mesen? They make it easier for kids to play FDS games. punNES doesn't currently revert to `disk 1 side A` either when you do a hard reset.

![saved](https://user-images.githubusercontent.com/6733770/131268837-06976f2c-3eb1-43db-8f3b-971ffb6c8fb1.png)

**Comment by punesemu** [comment]
I like all three options. I will do it.

**Comment by punesemu** [comment]
What version of the emulator are you using? Windows 64bit?

**Comment by anewuser** [comment]
The latest 64-bit D3D9 build.

**Comment by punesemu** [comment]
If you want you can try this WIP https://www.dropbox.com/s/y02hhe1hsg68elb/punes.zip?dl=1

**Comment by anewuser** [comment]
Everything seems to be working fine.
