### ISSUE TITLE
Reversed NES/Four Score controller modes

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#157]
The current 64-bit D3D9 WIP build enables four controller ports when you select the `NES` mode, and only two ports when the `Four Score` mode is selected. Shouldn't it be the other way around?

**Comment by punesemu** [comment]
Fixed with https://github.com/punesemu/puNES/commit/a6252893b5b22a0851e445c77f6621417bef0f8e. Thx for the report.
