### ISSUE TITLE
Allow just one instance of the program to run

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#158]
If puNES is already open and you launch another ROM from a frontend, it opens a new puNES window instead of reusing the current instance. If some people find it useful to have multiple instances of the program running, could you create an option to limit this?

**Comment by punesemu** [comment]
I never thought about it, I can do it.

**Comment by punesemu** [comment]
After https://github.com/punesemu/puNES/commit/467d195a152dc2b62989e706e4b29d25290a08e3, it's time to think about this feature.

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/582a6664f5449119925441cec0b52ef69cdda453

**Comment by anewuser** [comment]
The running window should be activated/brought to front when you attempt to launch a second instance, or it may stay under other windows/the user may not realize puNES is already running. 

This is how SMPlayer does this: https://github.com/smplayer-dev/smplayer/blob/master/src/qtsingleapplication/qtsingleapplication.cpp

**Comment by punesemu** [comment]
Try this https://www.dropbox.com/s/y02hhe1hsg68elb/punes.zip?dl=1

**Comment by anewuser** [comment]
I think that the matter is that I was starting it with no ROM. Either way, it works when I try launching a new instance with a ROM. Thank you again!
