### ISSUE TITLE
iNES2.0 mapper 48 not supported

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#161]
iNES2.0-headered ROMs with this mapper fail to load: https://wiki.nesdev.com/w/index.php/INES_Mapper_048

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/c78196dd14ed2926e8709a195a8eff0d878191fb

**Comment by anewuser** [comment]
The titles in that list now load correctly. Thank you!
