### ISSUE TITLE
Software filters affecting "unaltered" screenshots

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#162]
Can you reproduce this with the "Save Unaltered NES screen" option?

Windows 64-bit D3D9
Software filter: NTSC Composite

![Balloon Fight (USA) - NTSC Composite](https://user-images.githubusercontent.com/6733770/132396592-307abed1-8b9b-409c-8182-2b3120031084.png)

**Comment by punesemu** [comment]
I'm sorry but I didn't understand, I don't see it altered by the graphic filter. But maybe I misunderstood the problem you are telling me.

**Comment by anewuser** [comment]
This happens with both v.0.107 and the latest D3D9 WIP build on an i3-5005U laptop.

#### Expected "Save Unaltered NES screen" result (works with filters off)
![Balloon Fight (USA)_000001](https://user-images.githubusercontent.com/6733770/132404267-7ceb8ab2-a63c-47d9-837f-55ff94a03816.png)

#### Actual results with filters on
NTSC Composite:
 
![Balloon Fight (USA)_000002](https://user-images.githubusercontent.com/6733770/132404303-97655c54-27da-4485-93d9-714cba61be97.png)

NTSC S-Video:

![Balloon Fight (USA)_000003](https://user-images.githubusercontent.com/6733770/132404360-c2a479f2-e93d-473f-9c32-bac38ef365fb.png)

**Comment by punesemu** [comment]
Ahhhh, yes I've understand. As always, thanks for the report, I'll work on it tomorrow.
