### ISSUE TITLE
NES 2.0 "Gimmick!" Level 1 shows a blank screen

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#163]
Is this caused by the emulator, or is the 2.0 ROM corrupted?

`Gimmick! (Japan)` with iNES headers:
![Gimmick! (Japan)_000001](https://user-images.githubusercontent.com/6733770/132769939-6588fec2-63f7-4d8e-8670-e59c11281d7e.png)

`Gimmick! (Japan)` with NES 2.0 headers:
![Gimmick! (Japan)_000002](https://user-images.githubusercontent.com/6733770/132770166-61c428f7-0938-4742-bda0-31b8157189d0.png)

**Comment by punesemu** [comment]
It depends on the wrong header. This mapper needs prg ram and I expect the size to be specified in the header while in this rom it is set to 0. I added (https://github.com/punesemu/puNES/commit/759acfc83660ac6bd9b9673588a62022dbac7063) a check in the mapper initialization routine so if not specified I set the size of the prg ram.

**Comment by anewuser** [comment]
Thanks for the workaround. I've sent a message to the author of the original NES 2.0 XML Database about this.

**Comment by anewuser** [comment]
@punesemu NewRisingSun looked into it and sent me this reply:

> The game definitely has no PRG-RAM, see https://nescartdb.com/profile/view/2695. It never writes anything to the PRG-RAM area at $6000-$7FFF.
> It does map PRG-R**O**M into the $6000-$7FFF address range, and the game reads from there, so if the emulator does not emulate that properly in the presence of a NES 2.0 header, reads from PRG-ROM mapped to that address range will fail.

**Comment by punesemu** [comment]
Thx for the info, this weekend I'll try to understand the situation better
and let you know.

Il giorno lun 13 set 2021 alle ore 23:51 anewuser ***@***.***>
ha scritto:
