### ISSUE TITLE
Re-enable sprite limit as needed

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#165]
The `Unlimited Sprites` option might cause graphical glitches in some games like Felix the Cat.

puNES savestate: [Felix the Cat (USA).zip](https://github.com/punesemu/puNES/files/7185020/Felix.the.Cat.USA.zip)

Expected:
![Animation](https://user-images.githubusercontent.com/6733770/133769711-e4a27b57-9032-4667-8cec-e5aefb0bf2d8.gif)

Glitch:
![Animation 2](https://user-images.githubusercontent.com/6733770/133770223-fbfd84e4-f01a-4996-b7ff-bc480e6d1461.gif)

Other games to test: https://github.com/punesemu/puNES/issues/25#issuecomment-258655750

Can you adapt SourMesen's solution? https://github.com/SourMesen/Mesen/issues/188

![mesen](https://user-images.githubusercontent.com/6733770/133768581-fe86e137-b9b6-441f-8b32-f7a2e5bdf0d4.png)

**Comment by punesemu** [comment]
I'll do it.

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/82c8e9605553f4721336a818ae9c1fb77342d56c

**Comment by anewuser** [comment]
Thank you. _Felix the Cat_ (with and without the [noDim hack](https://www.romhacking.net/hacks/2152/)) and _Majou Densetsu II - Daimashikyou Galious_ are all working properly.
