### ISSUE TITLE
The controller does not work with a Famicon Disk Game.

### ISSUE THREAD

**Issue by akaelover** [punesemu/puNES#169]
Hello, with the game Zelda Japanese version no controller works, neither in Linux nor in Windows.

I have tried controllers, Xbox series, Nintendo switch and arcade sticks. 
The controller does not work with a Famicon Disk Game.

**Comment by akaelover** [comment]
Hi, yes you were right and it doesn't work in version 0.107 with the game Zelda no Densetsu - The Hyrule Fantasy (Japan) (v1.1), neither does version 1.0 and the patched ones with English subtitles.  On the other hand with the version compiled from git it works perfectly.

**Comment by punesemu** [comment]
Good, then I can consider this issue closed. Thanks anyway for the report.
