### ISSUE TITLE
Portability options

### ISSUE THREAD

**Issue by Dabil** [punesemu/puNES#17]
Thank you very much for building this emulator. You have done a fantastic job with it. I sent you a donation a little bit ago so have a cold one on me. (Maybe this will buy me some favor in this request? lol)

puNES saves settings data in C:\Users\Owner\Documents\puNES. The folders there are:

bios
cheat
diff
pgs
prb
save
screenshot
tmp 

and the following 3 files:

input.cfg
puNES.cfg
recent.cfg

I would like a setting that allows me to select where all this is saved to. (maybe individual setting for each?)  I am sure many people like having the settings data saved in documents so that it is easy to upgrade to a new version, however I prefer to have all this data saved within its own directory. This way I can have multiple versions of this emulator each using different settings configurations. 

Plus it makes the emulator more portable as I can just copy the whole directory along with its settings. 

Thank you very much!

**Comment by punesemu** [comment]
Thanks for the support, I owe you a :beer:. There is already a portable mode, you just rename the executable to punes32.exe in punes32_p.exe (or punes64.exe in punes64_p.exe) and the emulator will use the directory in which it's present as the base directory.
