### ISSUE TITLE
High-res sample rate/bit rate for audio

### ISSUE THREAD

**Issue by andoruB** [punesemu/puNES#172]
Loving this emulator so far! Has the most stable and sane interface out of all the NES emulators I've tried.
Would it possible to add higher sample rates and higher bit depths for the audio?

EDIT: Also audio-only and video recording defaults the sample rate to 44.1kHz, no matter what sample rate is selected.

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/54ef1264961285cddfc298be690cc9b8c70bddca.
Try the latest [WIP](https://github.com/punesemu/puNES#floppy_disk-work-in-progress-wip-builds). As for audio and video recordings, the default value (44100) is set when the audio codec does not offer information on the supported sample rates. The two indicted are the FLAC and VORBIS (OGG) format. I improved the sample rate search routine, thanks for the tip.

**Comment by andoruB** [comment]
Oh wow, that was fast! Fortunately no need for waiting as I compiled it myself on my Linux machine. Thank you for the quick fixes, now it both outputs and records as intended! 
I did try to use flac, mp3, wav and ogg as codecs, but they all gave me the same result. Granted I used the latest stable release of the code, so that's maybe why I got that result.
One thing I forgot to mention is that it still records the audio files in stereo even though the output is in mono. Would it be possible to fix that as well? Would save quite a bit on the space.
Also the bit depth proposition hasn't been touched. Would that be possible to implement, or do you think that might be too difficult, or could cause issues with the RP2A03/RP2A07 emulation?

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/6d1256ff6ad7a2bc0e28691d8c2acab3c93429d3.
So, the VORBIS format only supports the sample rates 48000 and 44100 and doesn't support mono but for the other formats I have corrected the automatic selection of the most suitable mode. I apologize for not explaining why I can't change the bit depth in the previous answer, I forgot about it :). The library I use for manipulating the samples has an output of 16bit signed so I cannot increase its depth.

**Comment by punesemu** [comment]
If there are no other reports, I consider this ticket closed.

**Comment by andoruB** [comment]
Thank you for yet another fix!
Vorbis is no problem, I don't intend to use it. But speaking of it, would it be possible to add support to Opus? It compresses better than ogg/vorbis, easier on the CPU, and supports mono (from what I know).
It's not something urgent, but I thought it would be nice as an option.

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/719dd4acdef315326081eddb24a741d51d01410d.
It's true that it supports mono but the only sample rate it supports is 48000.

**Comment by andoruB** [comment]
Thank you so much! You're the best!

**Comment by punesemu** [comment]
You are welcome. Obviously your system's FFMpeg package must be compiled with libopus support in order to use the format in the emulator.
