### ISSUE TITLE
Buttons are too small in Controller Settings

### ISSUE THREAD

**Issue by tehkonst** [punesemu/puNES#179]
puNES 0.108 (build from sources)
Ubuntu 20.04 xfce4
Something wrong with rendering buttons in settings of a controller. Look at the screenshot:
![image](https://user-images.githubusercontent.com/2618162/146470165-1823292c-0e15-49d8-ac9f-75c9bc28b2ab.png)

**Comment by punesemu** [comment]
Hi tehkonst, thx for your report. Unfortunately I can't reproduce the error but could you try this patch and tell me if it solves?
https://gist.github.com/punesemu/2bae1845258583946c24f6320a18a5a4

**Comment by tehkonst** [comment]
I don't know how to apply it. Any instructions?

To reproduce, you need to increase the default font of the system (xfce in my case).

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/d59d3fdd4fe85d9857a3596c203be4acfc6ef3c6.
Thanks to your suggestion I was able to reproduce the problem and I solved it. I also discovered another problem with the palette widget which I will work on later.

**Comment by punesemu** [comment]
I found that this bug is only present with previous versions of the QT, so it was a bug in the handling of the High DPI of the QT libraries fixed in later versions.
