### ISSUE TITLE
duck hunt on mause

### ISSUE THREAD

**Issue by manotroll** [punesemu/puNES#183]
how do I enable the "virtual pistol"
I selected in the menu nothing else happens only the cross appears in place of the arrow

**Comment by punesemu** [comment]
Hi manotroll, you haven't given me much information about your problem (such as the version you are using, on what operating system, if you have the problem in full screen or in window) but let's try to understand better anyway.
First of all use the [WIP](https://github.com/punesemu/puNES#floppy_disk-work-in-progress-wip-builds) version and set these settings in the input configuration tab and let me know. 
![Duck Hunt](https://user-images.githubusercontent.com/14859058/147417538-ceab73c3-de40-4591-858f-1b4b225511a0.png)

**Comment by manotroll** [comment]
Oops thank you that's right it has to stay on P2 but I didn't understand why you can choose on P1
Is there any easy way to use the wii control in this emulator?

**Comment by punesemu** [comment]
The duck hunt rom expects to find the zapper in port 2. As for the wii controller I'm sorry but I can't help you, not having it I don't know how it works
