### ISSUE TITLE
puNES 0.108 fullscreen is wrecked

### ISSUE THREAD

**Issue by TCH68k** [punesemu/puNES#186]
If i try to play in fullscreen with puNES 0.108, then i get this result:

http://oscomp.hu/depot/punes_fullscreen_108.png

In 0.107 this works:

http://oscomp.hu/depot/punes_fullscreen_107.png

Fullscreen is set to use "desktop resolution" which is 1920x1080.

**Comment by TCH68k** [comment]
The function `gfx_set_screen()` at `src/video/opengl/gfx.c:115` fails to set the dimensions of the window to the screen's if the preferred resolution is "desktop" or manually set to the desktop's.
(Also, the `puNES.cfg` config file has a typo in the variable name `"use integer scaliung in fullscreen"`.)

**Comment by punesemu** [comment]
Hi TCH68k, I'll check it out when I get home, I'm out for a few days. Take away a curiosity, what version of QT are you using? I don't want it to be a bug of some old version of the libraries

**Comment by TCH68k** [comment]
It's Qt 5.7.1, but the very same `showFullscreen()` works in puNES 0.107. I figured it out that if i "inject" `width = 1920, height = 1080;` into `gfx_set_screen()` before the `gfx.w[VIDEO_MODE]` and `gfx.h[VIDEO_MODE]` is set, then it will resize the window correctly in fullscreen, but then it will have the same size in windowed mode too. Also, it seems that `VIDEO_MODE` is always `3`, regardless if i'm in windowed mode, or fullscreen mode and regardless of the physical resolution, whether it is 1920x1080 or 1280x960.

**Comment by punesemu** [comment]
I need to recreate the problem, can you kindly tell me your configuration? What OS do you use?

**Comment by TCH68k** [comment]
Devuan 2 AMD64 (Debian 9 without systemd).
Kernel is "4.9.0-16-amd64 #1 SMP Debian 4.9.272-2 (2021-07-19) x86_64 GNU/Linux"
Qt is 5.7.1
CMake is 3.13.5
GCC is 6.3.0
nVidia driver is 470.57.02

**Comment by punesemu** [comment]
Ok, I'll try to install it on a VM. I will keep you up to date.

**Comment by TCH68k** [comment]
Thanks.

**Comment by punesemu** [comment]
Which desktop environment do you use?

**Comment by TCH68k** [comment]
Well, Trinity Desktop Environment, but that should be irrelevant. However what is relevant, that i use X11 and not Wayland.

**Comment by punesemu** [comment]
I installed the Devuan 2.0 ascii with the DE Mate and I couldn't reproduce the problem then, just out of curiosity, I installed Trinity and finally the problem appeared. Now I can finally try to understand.

**Comment by punesemu** [comment]
Try with this patch https://gist.github.com/punesemu/5e8ea5cf2439683004986f0df5736b9b

**Comment by TCH68k** [comment]
Thank you, it fixes the problem. I am surprised though. What was the bug Trinity caused? puNES uses zero stuff from the Trinity ecosystem and as for the underlying system, it's just X11. What changed since 0.107?

**Comment by punesemu** [comment]
In `qt.cpp` in the `gui_set_window_size()` function I set the size of the main window to the size I want. For some reason the trinity WM, only with the switch to fullscreen mode, does not update the size if I don't reset the min and max size of the window with `reset_min_max_size ()`. Compared to 0.107, all the management of the fullscreen has changed to support the change of resolution.

**Comment by TCH68k** [comment]
Reported: https://mirror.git.trinitydesktop.org/gitea/TDE/tqt3/issues/60
