### ISSUE TITLE
Codemasters "Firehawk" game freezes if using NES 2.0 headers.

### ISSUE THREAD

**Issue by SkyPirate1** [punesemu/puNES#189]
I tested both Firehawk (USA) (Unl) and Firehawk (Europe) (Unl).  With NES 2.0 headers the games freeze on the purple screen just after the Codemasters logo screen, and never make it to the actual intro/title screen.  However using a hex editor I managed to figure out which part of the header is affecting this.

rom hashes without header:
eur rom sha-1 7b23cacd3a6864450561c546c052b6f7f348cf04
usa rom sha-1 334781c830f135cf30a33e392d8aaa4afdc223f9

eur header values:
iNES 1.0 (works)
4e 45 53 1a 08 00 71 40 00 00 00 00 00 00 00 00
2.0 (freezes)
4e 45 53 1a 08 00 71 **48** 10 00 00 07 02 00 00 01

usa header values:
iNES 1.0 (works)
4e 45 53 1a 08 00 70 40 00 00 00 00 00 00 00 00
2.0 (freezes)
4e 45 53 1a 08 00 70 **48** 10 00 00 07 02 00 00 01

The specific part affecting emulation is byte 8 (in bold text above), as changing the value from 48 to 40 allows the games to run, but I don't know why it only affects puNES.  I tested with fceux, Nestopia, and Mesen, and they all work.  The headers are from NewRisingSun's database over at https://forums.nesdev.org/viewtopic.php?t=19940

I'll admit though I am not entirely certain this is an emulation issue so much as maybe the header is wrong in this case.

**Comment by punesemu** [comment]
Fixed with https://github.com/punesemu/puNES/commit/ea85912f4f1560d9be0e3285b98f7f67e01ee418.
