### ISSUE TITLE
Galaxian (Japan) and Galaxian (Japan) (Rev A) error loading rom

### ISSUE THREAD

**Issue by SkyPirate1** [punesemu/puNES#190]
These 2 refuse to load regardless of which header version is used.  Galaxian (World) (Namcot Collection, Namco Museum Archives Vol 1) runs fine.

Galaxian (Japan) without header sha-1
44bc6c4e8b3f6c635281b4c05382e8f316d8269e

header 1.0
4e45531a 00010000 00000000 00000000

header 2.0
4e45531a 34010008 000f0000 00000001

Galaxian (Japan) (Rev A) without header sha-1
0fe9120fd5adc2790b0b9e8fadd136f9c66a709f

header 1.0
4e45531a 00010000 00000000 00000000

header 2.0
4e45531a 34010008 000f0000 00000001

**Comment by punesemu** [comment]
Hi SkyPerate1, you can send this roms?

**Comment by SkyPirate1** [comment]
Should be in your gmail now.  The files are attached there.

**Comment by punesemu** [comment]
Thx for the roms.

**Comment by anewuser** [comment]
@punesemu  `Galaxian (Japan)` and `Galaxian (Japan) (Rev 1)` seem to be broken again.

**Comment by punesemu** [comment]
Fixed.
