### ISSUE TITLE
[Feature Request] Support for XDG Base Directory Specification

### ISSUE THREAD

**Issue by Latrolage** [punesemu/puNES#193]
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

https://wiki.archlinux.org/title/XDG_Base_Directory#User_directories

**Comment by punesemu** [comment]
I could move the $HOME/.puNES directory to $XDG_CONFIG_HOME/puNES.

**Comment by Latrolage** [comment]
Yes. Some folders should probably be in `$XDG_DATA_HOME/puNES` like the bios and screenshot folders.

I'm not sure what the tmp folder is but if it's only used like a temporary cache location, it should be put into `$XDG_CACHE_HOME/puNES`

[The arch wiki explains gives a pretty good summary of each location](https://wiki.archlinux.org/title/XDG_Base_Directory#User_directories)

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/55c957b6257ef43dafffcf9aba5869518513bf25
