### ISSUE TITLE
Unable to create the texture

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#195]
Hello. Starting the emulator from the command prompt with the `--hidden-gui` parameter now gives an "Unable to create the texture" error, and I have to kill the process manually.

    >Z:\punes64.wip.d3d9\punes_p.exe --hidden-gui "Quattro Arcade (USA) (Unl).7z"
    
![punes](https://user-images.githubusercontent.com/6733770/160674556-0b784524-fac8-462a-b328-e32f0fa91fdd.png)

puNES 0.109 634e6a2 D3D9
Windows 10

**Comment by punesemu** [comment]
I thought i solved with this https://github.com/punesemu/puNES/commit/aec49aafa2f226a5970f9923aaa42375e6afb7a5 but the problem is still there. I have to dig deeper.

**Comment by anewuser** [comment]
I'm getting this error from the download link:  `{"message":"Artifacts download limit (1024 MB/day) exceeded."}`.

I'll try again tomorrow.

**Comment by punesemu** [comment]
I didn't know that AppVeyor had set these limits. Maybe it's time to study GitHub Actions.

**Comment by punesemu** [comment]
> * Toggling the GUI on and off with a keyboard shortcut makes the toolbar and the status bar disappear for good. I have to restart the application for them to come back

I can't reproduce the problem, can you send me your puNES.cfg?

> * I also got the `Unable to create the texture` error while toggling the GUI a few times, especially while trying to record the below screencast with [ScreenToGif](https://github.com/NickeManarin/ScreenToGif)

https://github.com/punesemu/puNES/commit/e5b96e829f3d3d24628fd57635086ec4bd18f5e0 Thanks to your reports I also discovered a leak that could also be the cause of this, but I'm not sure. 

> * When the GUI is visible and I use the NTSC Composite filter with scanlines, there's a permanent dark bar in the middle of the window

https://github.com/punesemu/puNES/commit/9905c147b07c94a2eb882470b7ef57f10d1b6360 Try the latest WIP.

**Comment by anewuser** [comment]
>I can't reproduce the problem, can you send me your puNES.cfg?

My configuration file had the `toolbar hidden=yes` setting, which I likely had changed manually in the past. Usually I launch ROMs from the QuickPlay frontend with the GUI already hidden. What confused me is that the toolbar is still displayed when I open puNES normally, and then it goes away after toggling the GUI twice.

>I will continue to investigate.

I had it happen again a few times randomly. Sometimes it crashes if I toggle the GUI as soon as I launch it with a ROM, but at other times I can toggle it several times in a row without any crash.

>Try the latest WIP.

Thank you for fixing the filter issue.

**Comment by punesemu** [comment]
> I had it happen again a few times randomly. Sometimes it crashes if I toggle the GUI as soon as I launch it with a ROM, but at other times I can toggle it several times in a row without any crash.

I finally understood what happens, now I have to understand why it happens. The investigation continues.

**Comment by anewuser** [comment]
That seems to have fixed it. Thanks!

**Comment by punesemu** [comment]
> Toggling the GUI on and off with a keyboard shortcut makes the toolbar and the status bar disappear for good. I have to restart the application for them to come back

So only this remains, but the problem is that I cannot reproduce the problem in any way

**Comment by punesemu** [comment]
> toolbar hidden=yes

OK, now I understand what happens. With this option set to ON the toolbar and the statusbar are always hidden even when you restore the GUI from the shortcut, it is not a bug. That option is controlled by double clicking on the menu bar.
