### ISSUE TITLE
puNES randomly becomes a background process

### ISSUE THREAD

**Issue by SkyPirate1** [punesemu/puNES#196]
This happens with version 109 and latest dev build.  Sometimes it happens when I double click the toolbar to hide the extras, and sometimes it happens when I change an option in the video settings.  It's really random.  Once it is stuck in the background I have to kill it in task manager.  Sometimes it goes straight to fullscreen on the next run after this happens even though I don't have it set to do that.  I'm running it in "portable" mode if that makes a difference.

I thought something like this was reported before and it got fixed but I didn't notice it when looking at the closed issues.

As an aside your latest dev build for opengl includes all the d3d9 stuff too, which probably wasn't intentional?

**Comment by punesemu** [comment]
This problem may have been fixed with commit https://github.com/punesemu/puNES/commit/77ad2b039bb09d71c69b844eaf08d5161562da54. 
Let me know if it still happens to you.

**Comment by SkyPirate1** [comment]
I think it is okay now but since it is random I can't be sure.

But, the toolbar under the menu bar cannot be permanently turned off now.  Even with "toolbar hidden=yes" it still shows up unless I double-click the menu bar again on each run.  Also, is there a way to make a shortcut/hotkey that toggles the menu bar and toolbar separately?

**Comment by punesemu** [comment]
> But, the toolbar under the menu bar cannot be permanently turned off now. Even with "toolbar hidden=yes" it still shows up unless I double-click the menu bar again on each run

Fixed with https://github.com/punesemu/puNES/commit/164346991c3a820db6cb27c2f521230104a99b0d.

> Alt+M only works for the menu bar in fullscreen, and Alt+G toggles both in the window at the same time. Maybe make Alt+M work in both screen modes and Alt+G be strictly for the toolbar underneath in windows.

I don't know, the idea doesn't convince me very much.

**Comment by punesemu** [comment]
For now I close the issue but if it happens again contact me here.
