### ISSUE TITLE
Parameters are not saved for GPU shaders in both opengl and d3d9 versions

### ISSUE THREAD

**Issue by SkyPirate1** [punesemu/puNES#200]
This affects the built in shaders and custom shaders from the net.  Even if I select "save settings" it does not work.  The shp files created in the shp folder are all zero byte files (aren't these the preset save files?), and that folder gets spammed up with them after fiddling with a hundred shaders lol.  But yeah, once you exit the emulator you have to set everything up for them again.

**Comment by punesemu** [comment]
It's much more than a fix. If you find any problems on both versions contact me here.
