### ISSUE TITLE
[Feature request] Make puNES portable by default.

### ISSUE THREAD

**Issue by ghost** [punesemu/puNES#201]
Personal preference but most other emulators don't create folders and settings in a directory other than where the main executable is located.  It is also more intuitive for an end user.

**Comment by anewuser** [comment]
Or maybe ask the user about it when puNES runs for the first time?

![mesen](https://user-images.githubusercontent.com/6733770/161623909-1aed00ac-3da0-4dfc-8e95-654b5eeb0168.png)

**Comment by punesemu** [comment]
I like the idea.

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/f6f2a9d6b4ad9d7aa30d7abf6a36adfe2629e3f3.
Added the Wizard also now you no longer need to rename the executable. If the executable is in a directory containing puNES.cfg it will automatically start in portable mode.

**Comment by anewuser** [comment]
Nice! Everything seems to be working fine on Windows.
