### ISSUE TITLE
Akumajou Special - Boku Dracula-kun (Japan) graphical glitches

### ISSUE THREAD

**Issue by XieTieqiang** [punesemu/puNES#204]
Akumajou Special - Boku Dracula-kun (Japan) graphical glitches

**Comment by punesemu** [comment]
Hello and thank you for contacting me. I tested the rom "Akumajou Special - Boku Dracula-kun (J) [!]. Nes" (from the GoodNes set) but I didn't find any graphical glitches. Are you sure you are using a correct rom and not one with the wrong header? Send me the rom that I do a test.

**Comment by XieTieqiang** [comment]
I have sent the ROM to the email. 
punes.development@gmail.com

**Comment by punesemu** [comment]
Try the last WIP, thanks for the report.
