### ISSUE TITLE
Kid Dracula (World) (Castlevania Anniversary Collection) does not work

### ISSUE THREAD

**Issue by SkyPirate1** [punesemu/puNES#205]
Nothing but green screen.  I've sent you the rom.  I discovered this while testing your fix for Akumajou Special - Boku Dracula-kun (Japan), which also fixed Akumajou Special - Boku Dracula-kun (World) (Ja) (Castlevania Anniversary Collection).

This game requires the included SAV file to work.  More info here:
https://datomatic.no-intro.org/index.php?page=show_record&s=45&n=2846

I also tried with the original header 4E 45 53 1A 08 10 72 10 00 00 00 00 00 00 00 00 and same results.

**Comment by punesemu** [comment]
Interesting. They came up with this to make life difficult for emulators. For now I have no way to make the rom work, I do not have the possibility to upload an additional file. Maybe it would be possible to create a complete rom by joining the sav file inside, there would be some testing to be done.

**Comment by SkyPirate1** [comment]
Yeah, odd they did this to the western version but not the japanese anniversary collection version.  Not a big deal for me personally, just like to be thorough and test all regions/versions for each game.

**Comment by punesemu** [comment]
Okay, I take back what I said. Copy the sav file into the punes "prb" folder by changing the extension from sav to prb. It works.

**Comment by SkyPirate1** [comment]
That makes sense, and you're right.

FOR FUTURE REFERENCE TO ANYONE WANTING TO PLAY THIS GAME:

1. Copy "Kid Dracula (World) (Castlevania Anniversary Collection).sav" file to prb folder for puNES. (Please back up original copy!)
2. Rename file extension to ".prb"
3. Play the game.

You can close this as it is really not a bug. ;)
