### ISSUE TITLE
Holy Diver (USA, Europe) (Ja) (Collector's Edition) (Aftermarket) (Unl) and Metal Storm (USA, Europe) (Aftermarket) (Unl) do not load with message "mapper 268 not supported"

### ISSUE THREAD

**Issue by SkyPirate1** [punesemu/puNES#207]
I didn't see that mapper in the source files either.  Sent them as usual.  I've been meaning to do a rundown of the mapper support, and was actually trying to locate stuff that was coolboy related when I saw these were listed on the nesdev mapper page.

EDIT: note to self, if this mapper gets added also test the various chinese carts/multicarts in mame's nes.xml which are mentioned at https://www.nesdev.org/wiki/NES_2.0_Mapper_268

**Comment by punesemu** [comment]
Fixed with https://github.com/punesemu/puNES/commit/0035ef3c2e4ad7d11d05bcb0af796817d17a5aeb.
