### ISSUE TITLE
"Golden Mario Party II - Around the World 6 in 1" Illegal Opcode 0x02 at 0x01FD error but...

### ISSUE THREAD

**Issue by ghost** [punesemu/puNES#208]
...this one is listed in Mame as a bad dump.  Mame boots it and nothing else seems to (nestopia, mesen, etc).  Uses mapper 370 https://www.nesdev.org/wiki/NES_2.0_Mapper_370 and I don't know if anything else does?

Looks like a hack of Super Mario 3
<img src="https://i.imgur.com/Tzoqf5Y.png"></img>

I merged the prg and chr roms and added the header from nes20db.xml.  If interested I can send it to you, but due to the bad dump status there's probably nothing that can be done at this point.  Basically this can be left as a "to-do" for the future.

**Comment by dragon2snow** [comment]
![20230323152643](https://user-images.githubusercontent.com/4350811/227132828-06e31515-4b05-4208-a478-819d648cf247.png)
this Multicarts?

**Comment by punesemu** [comment]
I think ghost was referring to that multicarts. Since I added support to mapper 370 in ver 0.110 I can close this issue.
