### ISSUE TITLE
Skull & Crossbones 2-player possible defect

### ISSUE THREAD

**Issue by angrylion7** [punesemu/puNES#21]
Compared to this recording off the real NES:
https://www.youtube.com/watch?v=fZ0axV6u5Hs
it seems that puNES 0.100 shows much more garbage below the "RED DOG" line (starting at 14:38) and more garbage on the info screen that appears when pressing "Select" (at 16:53, for example). The problem with the info screen also applies to 1-player mode (at 13:05).

**Comment by punesemu** [comment]
Hello angrylion7, thanks for the report, I will give a look.

**Comment by punesemu** [comment]
Fixed. Try the new 0.101 WIP

Windows:
https://dl.dropboxusercontent.com/u/21595068/punes32.wip.d3d9.zip
https://dl.dropboxusercontent.com/u/21595068/punes64.wip.d3d9.zip
https://dl.dropboxusercontent.com/u/21595068/punes32.wip.sdl.zip
https://dl.dropboxusercontent.com/u/21595068/punes64.wip.sdl.zip
Linux:
https://dl.dropboxusercontent.com/u/21595068/punes32
https://dl.dropboxusercontent.com/u/21595068/punes64

**Comment by angrylion7** [comment]
Looks good. Thank you very much!

**Comment by punesemu** [comment]
Try this new WIP:

Windows:
https://dl.dropboxusercontent.com/u/21595068/punes32.wip.d3d9.zip
https://dl.dropboxusercontent.com/u/21595068/punes64.wip.d3d9.zip
https://dl.dropboxusercontent.com/u/21595068/punes32.wip.sdl.zip
https://dl.dropboxusercontent.com/u/21595068/punes64.wip.sdl.zip
Linux:
https://dl.dropboxusercontent.com/u/21595068/punes32
https://dl.dropboxusercontent.com/u/21595068/punes64

**Comment by angrylion7** [comment]
I've tested Hard Drivin', Skull & Crossbones, Shinobi, Klax, Road Runner, Rolling Thunder and Xybots, and they all seemed OK, but I didn't go very far in any of these games.
