### ISSUE TITLE
"Turn off" option does odd things with Famicom disks

### ISSUE THREAD

**Issue by SkyPirate1** [punesemu/puNES#210]
I don't know of a good title for this bug.  Load a game, doesn't matter if NES or Famicom disk, then turn off the console with Alt+R.  Now load another Famicom disk game using the "Open" command, and the system and game will be in black and white and play at a little over half speed.  "Turn on" button is still green.

I tried ejecting the disk first if doing this with a famicom game as well, same result.
<img src="https://i.imgur.com/U8pWKBh.png"/>

EDIT: Is there any way to select which system to turn on?  Seems this is more intended for the NES than Famicom.  Curious to also see if there is a way to turn on the NES with no game loaded, to see if the screen will constantly flash just like a real console would, or for the Famicom, to easily run the Start+Select RAM check without having to first load a disk.

**Comment by punesemu** [comment]
> Is there any way to select which system to turn on? Seems this is more intended for the NES than Famicom.

From the point of view of the emulator there is no difference, it is only the rom of the bios that makes it.

> Curious to also see if there is a way to turn on the NES with no game loaded, to see if the screen will constantly flash just like a real console would, or for the Famicom, to easily run the Start+Select RAM check without having to first load a disk.

Nice idea, I hadn't thought of that. For now there is no possibility since the bios is loaded only when an fds is loaded, I could create a menu item to start only with the bios without inserting any disk image.

**Comment by punesemu** [comment]
To achieve this goal, you can do this:
1- Disable the options 'Switch the disk / side automatically' and 'Use fast forward when loading the BIOS or disk / side'
2 - As soon as you load the FDS press ALT-E to immediately eject the disk.
You will remain in the bios screen waiting for the disc to be inserted.

**Comment by SkyPirate1** [comment]
> Nice idea, I hadn't thought of that. For now there is no possibility since the bios is loaded only when an fds is loaded, I could create a menu item to start only with the bios without inserting any disk image.

Yes, something like this.  I would just like a way to tell the emulator which system to power on, and to be able to do this with no game loaded.  Is it trivial?  Yes, but I don't see any other emulator doing this.  You could have bragging rights and also it would make it "more accurate" to the real thing.

I'll close this issue as the main problem has been solved.

**Comment by punesemu** [comment]
> Yes, something like this. I would just like a way to tell the emulator which system to power on, and to be able to do this with no game loaded. Is it trivial? Yes, but I don't see any other emulator doing this. You could have bragging rights and also it would make it "more accurate" to the real thing.

Albeit with a little delay https://github.com/punesemu/puNES/commit/3f0ef731ec6e9816bcdad111dbb86cc51a953a8f

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/issues/246
