### ISSUE TITLE
WIP links broken

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#214]
The WIP links are giving this error:
> No successful runs found for workflow 'build.yml' and branch 'master'. 

I was able to download the latest build from [the Actions tab](https://github.com/punesemu/puNES/actions/runs/2180631242), though.

**Comment by punesemu** [comment]
There is some problem with the github actions, you can also see it from the badge [![Build status](https://github.com/punesemu/puNES/actions/workflows/build.yml/badge.svg)](https://github.com/punesemu/puNES/actions) that does not update although the compilation was successful. Hope they resolve soon.

**Comment by punesemu** [comment]
Fixed.
