### ISSUE TITLE
Crashes when saving state to a file, and fails to load the saved state

### ISSUE THREAD

**Issue by cheeseburgerwalruss** [punesemu/puNES#216]
I tried looking through closed and open issues and didn't see this mentioned  I have been trying to save states to a file but every time I do so, puNES hangs up for a couple seconds and then closes.  The .pns file is created, but if I go to try and load it, nothing happens at all.

**Comment by punesemu** [comment]
I cannot reproduce the problem. Give me some more information:
- what version do you use?
- on which operating systems?
- D3D9 or OpenGL?
- tell me a rom with which the problem occurs.

**Comment by cheeseburgerwalruss** [comment]
> 

I'm running .107, which to be fair I should be running latest version.  Will update tomorrow after work and see if it helps.  But I am running this on Windows 10 and OpenGL.  The only rom I've seen this issue with (honestly the only thing I have tested this emu with) is Legend of Zelda.

I should have done more to try and replicate this issue with others roms, but I haven't.  I can definitely test that out tomorrow though just for curiosities sake.

**Comment by punesemu** [comment]
Try the latest [WIP](https://github.com/punesemu/puNES#floppy_disk-work-in-progress-wip-builds) and let me know.

**Comment by punesemu** [comment]
I consider this issue closed.
