### ISSUE TITLE
Compilation fail in KDE

### ISSUE THREAD

**Issue by Blad3forc3** [punesemu/puNES#217]

**Comment by Blad3forc3** [comment]
mappers/mapper_Coolgirl.c: In function ‘mapper02_cpu_wr_high’:
mappers/mapper_Coolgirl.c:1364:41: error: parameter name omitted
 1364 | INLINE static void mapper02_cpu_wr_high(WORD, BYTE value) {
      |                                         ^~~~
mappers/mapper_Coolgirl.c: In function ‘mapper03_cpu_wr_high’:
mappers/mapper_Coolgirl.c:1368:41: error: parameter name omitted
 1368 | INLINE static void mapper03_cpu_wr_high(WORD, BYTE value) {
      |                                         ^~~~
mappers/mapper_Coolgirl.c: In function ‘mapper04_cpu_wr_high’:
mappers/mapper_Coolgirl.c:1374:41: error: parameter name omitted
 1374 | INLINE static void mapper04_cpu_wr_high(WORD, BYTE value) {
      |                                         ^~~~
mappers/mapper_Coolgirl.c: In function ‘mapper05_cpu_wr_high’:
mappers/mapper_Coolgirl.c:1379:41: error: parameter name omitted
 1379 | INLINE static void mapper05_cpu_wr_high(WORD, BYTE value) {
      |                                         ^~~~
mappers/mapper_Coolgirl.c: In function ‘mapper08_cpu_wr_high’:
mappers/mapper_Coolgirl.c:1497:41: error: parameter name omitted
 1497 | INLINE static void mapper08_cpu_wr_high(WORD, BYTE value) {
      |                                         ^~~~
mappers/mapper_Coolgirl.c: In function ‘mapper10_cpu_wr_high’:
mappers/mapper_Coolgirl.c:1510:41: error: parameter name omitted
 1510 | INLINE static void mapper10_cpu_wr_high(WORD, BYTE value) {
      |                                         ^~~~
mappers/mapper_Coolgirl.c: In function ‘mapper11_cpu_wr_high’:
mappers/mapper_Coolgirl.c:1515:41: error: parameter name omitted
 1515 | INLINE static void mapper11_cpu_wr_high(WORD, BYTE value) {
      |                                         ^~~~
mappers/mapper_Coolgirl.c: In function ‘mapper18_cpu_wr_high’:
mappers/mapper_Coolgirl.c:1739:41: error: parameter name omitted
 1739 | INLINE static void mapper18_cpu_wr_high(WORD, BYTE value) {
      |                                         ^~~~
mappers/mapper_Coolgirl.c: In function ‘mapper30_cpu_wr_high’:
mappers/mapper_Coolgirl.c:2199:41: error: parameter name omitted
 2199 | INLINE static void mapper30_cpu_wr_high(WORD, BYTE value) {
      |                                         ^~~~
mappers/mapper_Coolgirl.c: In function ‘mapper37_cpu_wr_high’:
mappers/mapper_Coolgirl.c:2333:41: error: parameter name omitted
 2333 | INLINE static void mapper37_cpu_wr_high(WORD, BYTE value) {
      |                                         ^~~~
mappers/mapper_Coolgirl.c: In function ‘mapper35_cpu_rd’:
mappers/mapper_Coolgirl.c:2372:36: error: parameter name omitted
 2372 | INLINE static BYTE mapper35_cpu_rd(WORD, BYTE) {
      |                                    ^~~~
mappers/mapper_Coolgirl.c:2372:42: error: parameter name omitted
 2372 | INLINE static BYTE mapper35_cpu_rd(WORD, BYTE) {
      |                                          ^~~~
make[3]: *** [Makefile:2022: mappers/mapper_Coolgirl.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/media/ade/Temp/puNES/src/core'
make[2]: *** [Makefile:543: all-recursive] Error 1
make[2]: Leaving directory '/media/ade/Temp/puNES/src'
make[1]: *** [Makefile:402: all-recursive] Error 1
make[1]: Leaving directory '/media/ade/Temp/puNES'
make: *** [Makefile:343: all] Error 2

**Comment by punesemu** [comment]
Out of curiosity, which compiler do you use and which version?

**Comment by Blad3forc3** [comment]
gcc 10
