### ISSUE TITLE
Configuration windows do not fit on screen (cropped)  

### ISSUE THREAD

**Issue by XYZ964** [punesemu/puNES#218]
Hi there!
  
While trying to configure the emulator i have this issue with the new opened windows.
They dont fit on the screen and cant be resized:
https://i.postimg.cc/d3Rggz7p/cant-resize.jpg

As you can see, this didnt happen with version 0.107:
https://i.postimg.cc/mkW0Xbr7/0-107-OK.jpg

I do hope you can fix this problem, many thanks in advance and congrats on you excellent emulator.

**Comment by punesemu** [comment]
This depends on the high dpi support which is enabled by default.
You can test this version? https://www.dropbox.com/s/y02hhe1hsg68elb/punes.zip?dl=1

**Comment by XYZ964** [comment]
**This version works great! 
Windows are not cropped anymore and they can be perfectly resized.
Thanks a lot FHorse, if you want me to test the opengl version as well or sthg else dont hesitate to contact me.**

![Clipboard01](https://user-images.githubusercontent.com/73845659/172459186-fd4fffce-74a7-456a-8cb6-fe12aff29962.jpg)

**Comment by punesemu** [comment]
I will have to test the changes on some other configuration before committing them but thanks for the feedback.

**Comment by XYZ964** [comment]
Latest WIP works perfect!

Congrats and thanks a lot for your great emulator.

 

De: Fabio Cavallo (FHorse) ***@***.***> 
Enviado el: lunes, 13 de junio de 2022 5:23
Para: punesemu/puNES ***@***.***>
CC: Markus ***@***.***>; Author ***@***.***>
Asunto: Re: [punesemu/puNES] Configuration windows do not fit on screen (cropped) (Issue #218)

 

Closed #218 <https://github.com/punesemu/puNES/issues/218>  as completed via  <https://github.com/punesemu/puNES/commit/a990aa1ac4aeec4bd199c7dd9e1c07846f07c2fe> a990aa1.

**Comment by XYZ964** [comment]
Latest WIP works perfect!
Congrats and thanks a lot for your great emulator.

**Comment by punesemu** [comment]
Thx for the feedback. :beer:
