### ISSUE TITLE
Controller Input Delay

### ISSUE THREAD

**Issue by Schicksal88** [punesemu/puNES#22]
It is impossible to precisely control games with my controller.
Tapping the D-Pad does move you either 0 pixels or 3.
If I tap the directional buttons on the keyboard I can move 1 pixel at a time.
I tested it in The Legend of Zelda and Mario 1, but I don't think that it has something to do with a specific game at all.

This issue is on both 64bit 0.100 versions of puNES.
I'am using a PS2 controller with a converter and puNES recognises it as js0: PS Converter.

I also noticed that the button presses are recognised after I LET GO of the button while mapping them in the menu, keyboard buttons are recognised PUSHING them.

**Comment by jcdenton2k** [comment]
This issue should be closed.  Newest WIP will prove that puNES detects controller input perfectly and any delay is either in the original NES/Famicom game programming (some were terrible at this) or otherwise a hardware fault in the controller itself (old/faulty connections perhaps).

**Comment by punesemu** [comment]
You can try with the new WIP?
