### ISSUE TITLE
Mapper 396: Support for 2048 PRG Roms missing

### ISSUE THREAD

**Issue by negativeExponent** [punesemu/puNES#220]
(Realtec SPC001) Golden 16-in-1 {Multicarts}.nes, with a PRG Crc32 of 0xE1EB29C1 has a prg size of 4096, so outer PRG mask at : 
https://github.com/punesemu/puNES/blob/1bffb1e6fc763ace597fa4ed6c34d539c9f3bafe/src/core/mappers/mapper_396.c#L63

should be 0x0F instead of 0x07

**Comment by punesemu** [comment]
I followed the instructions given on [nesdev](https://www.nesdev.org/wiki/NES_2.0_Mapper_396) but they could actually be incomplete. Could you send me the rom?

**Comment by negativeExponent** [comment]
here are mapper 396 that i have:
[mapper_396.zip](https://github.com/punesemu/puNES/files/8944756/mapper_396.zip)

**Comment by punesemu** [comment]
If it were possible I would like to ask you a favor but I would prefer to do it via email. Can I contact you? If so, to which address?

**Comment by negativeExponent** [comment]
Discord, but i rarely go online

**negative#4809**
