### ISSUE TITLE
The generated configuration files are all in "My Documents", how to make the configuration files generated in the simulator directory?

### ISSUE THREAD

**Issue by kongmao45678** [punesemu/puNES#222]
The generated configuration files are all in "My Documents", how to make the configuration files generated in the simulator directory?

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES#keyboard-configuration:
"To run it in portable mode, rename the executable by adding the suffix _p. Examples: punes.exe -> punes_p.exe or punes64.exe -> punes64_p.exe"

**Comment by punesemu** [comment]
When I have a free moment I will implement this suggestion : https://github.com/punesemu/puNES/issues/201.
