### ISSUE TITLE
Don't crash when no audio output device available

### ISSUE THREAD

**Issue by liurui39660** [punesemu/puNES#227]
## What happened?

When starting puNES, it's frozen when no available audio output device.

## Reproduction

- In Windows Sound settings, disable or disconnect all playback devices.
- Start puNES.

## Expected behavior

puNES successfully starts, and can play games without audio.

## Actual behavior

puNES starts, but with a pop-up window titled "Error!" and with the message "ATTENTION: Unable to create XAudio2 master voice.". After clicking on "OK", puNES is frozen.

## Version

puNES 0.109 WIP, Commit r1829 11f19406, x86_64, OpenGL
Windows 10 Pro, 21H2, 19044.1889

**Comment by punesemu** [comment]
Thx for the report. These days I'm not at home, I'll be back on Thursday and I'll try to figure out what the problem is.
