### ISSUE TITLE
No audio on D3D9  builds after 20145f0

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#228]
I've tested the latest D3D9 builds on Windows 10 and I get no audio at all after this commit: 20145f0.

No audio:
https://github.com/punesemu/puNES/actions/runs/3060777563
https://github.com/punesemu/puNES/actions/runs/3067405955

Working audio:
https://github.com/punesemu/puNES/actions/runs/3017966309

<details>
<img src="https://user-images.githubusercontent.com/6733770/190654515-396faa86-d9cd-45da-a049-99991af685ca.png"/>
</details>

**Comment by punesemu** [comment]
I have tried on three different computers and cannot reproduce the problem. How many devices appear in the "Output Devices" list?

**Comment by punesemu** [comment]
OK, I think I understand what the problem is, try the last WIP.

**Comment by anewuser** [comment]
Thank you! That was enough to fix it.
