### ISSUE TITLE
Feature request: support for mapper 63

### ISSUE THREAD

**Issue by TCH68k** [punesemu/puNES#230]
I would like to run this ROM: http://oscomp.hu/depot/82-in-1.nes

**Comment by punesemu** [comment]
I have tested your rom and here it works. What's your problem?

**Comment by TCH68k** [comment]
Sorry, i was using the latest stable 0.109 and i did not know, that since then it got support. My apologies, you can close this as invalid.

**Comment by TCH68k** [comment]
However, i updated to the latest snapshot and now the emulator become unusable. Shift, Ctrl, Meta and Alt all turns on fast forward, instead of their assigned function (Shift = A, Ctrl = B, Meta = Turbo A, and Alt + Enter is used to switch to fullscreen.)

**Comment by TCH68k** [comment]
If i press one of them, it starts fastforwarding. If i press two of them, it stops fastforwarding.
How can i disable this?

**Comment by punesemu** [comment]
Thanks for reporting, I will try to reproduce the problem and correct it.

**Comment by TCH68k** [comment]
Here is my older config file: http://oscomp.hu/depot/input.cfg.xz
With this, this happens.

**Comment by punesemu** [comment]
Thank you very much but I was able to reproduce it and in my local branch I have already fixed the bug but I have not committed it yet because I have noticed another anomalous behavior with your assignment of the keys "SHIFT = A", "CTRL = B" and "Meta = Turbo A". I'm investigating this now.

**Comment by TCH68k** [comment]
Works even without setting the forward key, thanks.
