### ISSUE TITLE
Numpad numbers are recognized as ordinary ones in shortcut assigner, but not usable in the game

### ISSUE THREAD

**Issue by TCH68k** [punesemu/puNES#231]
For instance i click into "fast forward" field in the shortcuts' list and press numpad 0. It recognizes as simply 0. Which could be okay, but when i press numpad 0 in the game, nothing happens, while the normal 0 switches into fast forward.

This was working in 0.109.

**Comment by punesemu** [comment]
I have tried the QKeySequenceEdit to set the shortcuts but I am noticing that it has several limitations and I will probably go back to using the old management method for the association of the shortcuts.

**Comment by TCH68k** [comment]
Okay, it works again, thx.
However, it still recognizes numpad numbers as ordinary.
