### ISSUE TITLE
Migrating to CMake buildsystem

### ISSUE THREAD

**Issue by winterheart** [punesemu/puNES#234]
Hello!

I've noticed that punes now uses hybrid build system - autotools for main project and cmake for bundled libraries. Do you interested to completely migrate punes to cmake building? I can prepare initial cmake project that can handle all needed stuff like building, dependency handling and importing external projects.

**Comment by punesemu** [comment]
Hi, of course I'm interested. Switching to cmake would also allow me to use QT6.

**Comment by punesemu** [comment]
Winterheart I still wanted to thank you for your fantastic contribution, I appreciated it immensely. Now I just have to clean up the autotools infrastructure to complete the switch. Thanks again.

**Comment by punesemu** [comment]
I wanted to ask you for one last help, if possible. The only thing not yet implemented is the installation, the 'make install' with autotools. Could you help me implement it?

**Comment by winterheart** [comment]
Sure thing, will do it on this week.

**Comment by punesemu** [comment]
Thanks to you, I added [QT6 support](https://github.com/punesemu/puNES/commit/2af242f7e7e9712f961685ebaaf3cfd28d12c0a3) in a matter of minutes. I owe you at least 8 beers.
