### ISSUE TITLE
APU channel Square wave 1 is always disabled when I start puNES no matter what

### ISSUE THREAD

**Issue by sqrxz** [punesemu/puNES#240]
This is an annoying little issue but I cannot understand it
I have changed the setting of square wave 1 manually to be on in GUI, saved the setting and closed the program, when it starts again, it's disabled.
I started out using the program in non-portable mode, when I wanted to tweak the .cfg I found out about portable, set it to portable and moved the cfg files I had to the program's folder.
I have gone to the config file and looked at the APU channel, square 1 setting, and weirdly enough it was ON. I changed it's volume to 10 to see if it was actually working, the volume changed, but no matter what I set the value of ON/OFF it remains OFF.

EDIT: figured out how to search past issues. I add information requested there.
I am on win10 x86_x64 D3D9, "compiled on 12/28/21." 
I saw some troubleshooting suggestions by users on a previous thread, I will try that.
I downloaded the latest version. tried refreshing the puNES.cfg, the issue remains.
I tried changing a setting in the input.cfg that another user found to be a problem, it didnt work.
Refreshing the input.cfg finally made a difference. tried a few different combinatios of old and new puNES.cfg and input.cfg, it is the old input.cfg that makes the difference, refreshing the input.cfg and reconfiguring my joystick solved the issue. 

[puNES APUsetting issue.zip](https://github.com/punesemu/puNES/files/10047965/puNES.APUsetting.issue.zip)
attaching input.cfg that caused the issue (input issue) a working refreshed one with my controller (input working,cfg) and puNES.cfg

**Comment by punesemu** [comment]
I tried with the [WIP](https://github.com/punesemu/puNES#floppy_disk-work-in-progress-wip-builds) version with your configuration (input issue.cfg) but I was unable to reproduce the problem (which I thought I solved in the issue https://github.com/punesemu/puNES/issues/187). I consider it closed but you reopen it if it happens again.

**Comment by punesemu** [comment]
OK, I was able to reproduce the problem. I reopen the issue.

**Comment by punesemu** [comment]
I have done several tests and I was able to recreate the problem only with version 0.109 while with WIP it never occurs.
