### ISSUE TITLE
iNES2.0 header support

### ISSUE THREAD

**Issue by TakuikaNinja** [punesemu/puNES#242]
iNES2.0 headers should be supported to mitigate mapper conflation.
A notable example of this is with the StarTropics games. I believe a CRC/hash check is used to determine the mapper for these since the header conflates MMC6 with MMC3. However, this breaks when the games in question are modified (e.g. applying the [music fix](https://www.romhacking.net/hacks/2229/) to StarTropics). This issue has already been brought up in [Mesen](https://github.com/SourMesen/Mesen/issues/610) and I have produced a patch to fix it: [StarTropics - Mapper Fix](https://www.romhacking.net/hacks/4871/). It should hopefully be useful for verifying the header support. 
Additionally, including a tool to view/edit the header data like in Mesen & FCEUX would be helpful.

**Comment by punesemu** [comment]
> Additionally, including a tool to view/edit the header data like in Mesen & FCEUX would be helpful.

https://github.com/punesemu/puNES/commit/d65db2c2c1159939fab17cb52d195a7b1d8c63b2
