### ISSUE TITLE
Starting a FDS game from commandline semi-hangs the emulator

### ISSUE THREAD

**Issue by RokkumanX** [punesemu/puNES#245]
Hi!

So I decided to give puNES a well deserved update since June this summer and updated to WIP 0.110 r1938 and immediately noticed something was wrong in terms of loading a FDS game via commandline.

Long story short, I have made custom commandline launchers for all the systems I emulate which requires me just to input a number which corresponds to something like this:
If 14 then "C:\Games\Video Games\Consoles\Famicom Disk System\punes_p.exe" "C:\Games\Video Games\Games\Famicom Disk System\Zelda No Densetsu - The Hyrule Fantasy (Japan).fds"

Nothing fancy but saves me a great deal of time whenever I want to play something.

Anyway, when I start the game from within puNES itself the game loads immediately as it should, however if I were to start the game from my launcher the game "starts" as you can hear the sound and all but the screen is frozen in a white screen with a Windows loading circle like the program is not responding.

If I wait "patiently" the screen is showing the game roughly in about 1,5-2 minutes whereas the game loads correctly if started from puNES directly.

Also, regular Famicom/NES games is unaffected and works properly both from my launcher and in puNES directly, only FDS games is affected.

**Comment by RokkumanX** [comment]
puNES WIP 0.109 r1912 works perfectly with commandline

punNES WIP 0.109 r1932 crashes the emulator immediately when loaded from commandline and shows nothing

**Comment by punesemu** [comment]
Actually, I've changed a few things under the hood, and even if I've done several tests, I may have missed something. Many thx for the report.

**Comment by RokkumanX** [comment]
@punesemu 

Thanks for an excellent handling and response time, it now works as it should.
Much obliged!
