### ISSUE TITLE
Insert disk 1 side A at power-up/reset setting doesn't seem to do anything

### ISSUE THREAD

**Issue by RokkumanX** [punesemu/puNES#246]
I don't know if this is an issue or not but I'll use Mesen as a reference on how this setting works there.

In Mesen I usually uncheck this setting because I love how the Famicom Disk System BIOS animation plays and whenever I'm done/ready I press the key assigned to insert the disk and the game boots afterwards.

In puNES however, unchecking this setting doesn't seem to do anything and it plays the Famicom Disk System BIOS for a second and loads the game as if this setting was still checked.

I'm kinda expecting the same behavior as Mesen, the Famicom Disk System BIOS animation starts as if there were no disk inserted and then by pressing the assigned insert key the game will boot.

I might be overthinking this but that's what I'm expecting from the setting.

Thanks in advance!

**Comment by punesemu** [comment]
Try with the last WIP.

**Comment by RokkumanX** [comment]
Thank you very much, the behavior in WIP 0.110 r1942 is now matched the one in Mesen and everything works beautifully with both the Insert disk 1 side A at power-up/reset setting checked and unchecked.

Couldn't ask for more at this point regarding puNES, thank you very much for an extraordinary day in terms of FDS dedication!
