### ISSUE TITLE
[Wizards & Warriors III - Kuros...Visions of Power (Europe)] Possible GFX bugs with the door ?

### ISSUE THREAD

**Issue by BenjaminSiskoo** [punesemu/puNES#249]
When you go down and swing your sword, you can see some GFX bug on the door. I don't know if the behaviour is correct or not.

![puneswizards](https://user-images.githubusercontent.com/12481242/208453459-5837ee2b-3589-4c27-ac7e-603bb1a7a5c4.gif)

**Comment by punesemu** [comment]
On youtube I've finded this [video](https://youtu.be/VJH0kUk3cHo?t=47) and [this](https://www.youtube.com/watch?v=zSNiQhfWPDU&t=74s). If you notice you see the same glitches but I don't know if they are playing with an emulator or on a real console. It would have to be tested with a real NES but unfortunately I can't do it, I don't own one.

**Comment by BenjaminSiskoo** [comment]
Yup I saw. With FCE Ultra 2.6.3, there is no glitches. And glitches with Nestopia UE ^^

**Comment by punesemu** [comment]
I think it's very likely that the glitches are present on the actual console but I can't be sure.

**Comment by BenjaminSiskoo** [comment]
I think so, I guess I have to close the br !!!

**Comment by dragon2snow** [comment]
fceux 2.6.5 has the same problem!

**Comment by BenjaminSiskoo** [comment]
Ok, I close it. Thanks

**Comment by TakuikaNinja** [comment]
This is just the OAM scanline limit of 8 being reached because of the sword & doors (yes, the doors are sprites too), and the game not employing any kind of flickering strategy. This is normal behaviour.

**Comment by punesemu** [comment]
TakuikaNinja thx for the info.
