### ISSUE TITLE
[Request] User Chooses Save Directory

### ISSUE THREAD

**Issue by jcdenton2k** [punesemu/puNES#26]
I would like to be able to choose what directory to save/store my configuration and other files within.  I don't want to have them forced to sit around in my Documents folder.

Also, where the hell are my NES SRM save files?  I tried to save in Final Fantasy 1 and I did the save but I can't find the save file in the puNES directory at all!  What good is an NES emulator that forces me to use save states instead of emulating the built-in battery-backed save RAM like any other NES emulator!?

**Comment by punesemu** [comment]
> I would like to be able to choose what directory to save/store my configuration and other files within. I don't want to have them forced to sit around in my Documents folder.

Use the portable mode. Rename "punesXX.exe" in "punesXX_p.exe".
> Also, where the hell are my NES SRM save files? I tried to save in Final Fantasy 1 and I did the save but I can't find the save file in the puNES directory at all! What good is an NES emulator that forces me to use save states instead of emulating the built-in battery-backed save RAM like any other NES emulator!?

Also, where the hell is it written that I have to save my built-in battery-backed RAM saves with the ".SRM" extension?!? They have the ".prb" extension and are located in prb directory.

**Comment by jcdenton2k** [comment]
There's a significant lack of documentation for puNES and it might be nice to put down some of these more interesting bits for the benefit of others.  I appreciate the responses.

Because nearly every emulator ever made has been using the .SRM (save ram) file extension and it allows for these save files to be portable across emulators.

Considering that many people like to sync their save files across desktop and portable emulators, it is highly inconsiderate of any emulator authors to use a special custom save file format and then never tell people about it (another documentation issue).

What does PRB stand for?  Why was it chosen instead of .SAV or .SRM?  Is it compatible with those formats as in I can change the extension and it will function in other emulators?

I get having custom formats for emulation accuracy is nice, but the SAVE FILE of all things is something that should be universal across emulators of that specific system (NES/Famicom in this case).

**Comment by punesemu** [comment]
> There's a significant lack of documentation for puNES and it might be nice to put down some of these more interesting bits for the benefit of others. I appreciate the responses.

You're absolutely right, and sooner or later I will.
> What does PRB stand for?

PRG Ram Battery which is exactly what I save.
> What is really odd is that there's already a separate directory called 'save' and yet the SAVE files aren't going into the SAVE directory. So what's the purpose of that directory and why isn't it used?

I use the SAVE directory for the save state (from 0 to 9).

**Comment by jcdenton2k** [comment]
Thank you again for the info.  Much appreciated.

I've been encountering some odd resistance whenever I mention puNES as a more accurate alternative to FCEUX and someone always brings up the (nonexistant) input latency issue you fixed way back in v0.79 about two years ago.

If you were able to do some new re-testing and maybe upload a video comparing puNES with FCEUX side by side for input latency that might be useful when someone tries to slander puNES with that misinformation.  I'd do it myself but puNES has no 'input UI' which shows what buttons are being pressed on the NES pad while playing.

**Comment by CraigIst** [comment]
Converting saves are not working at all.
