### ISSUE TITLE
Enhancement: On-Screen Input Display

### ISSUE THREAD

**Issue by jcdenton2k** [punesemu/puNES#27]
I would like to see this implemented similar to how FCEUX already shows an input display that shows when the emulator detects input.

There are many continuing to criticize puNES for 'input latency' despite it being fixed in v0.79 so I would like to resolve this issue with some definitive proof that it isn't the emulator at fault.  It is far easier to do it with an accurate on-screen display.

>Display (Sub-Menu) -> Input Display
-The input display will display 1-4 pictures of a NES controller at the bottom of the screen.  When playing/recording a movie, these controllers will display the input that is captured in the file.

**Comment by punesemu** [comment]
Actually I have an On-Screen Input Display that use only during the execution of a TAS video. Can I add an option to display it even during normal use of the emulator.

**Comment by jcdenton2k** [comment]
@punesemu 

Yes, that would be fantastic!  Just a simple UI toggle option to allow us to use it with 'normal' use of the emulator.

Just need to make sure there is as close to ZERO delay as possible when it comes to 1:1 display of the button.  If I am using a wired keyboard and I press 'A' button in Super Mario Bros 1 then it should immediately cause Mario to jump in-game.  It has to be as close to zero-delay input latency as possible.

I need to prove that there is little to no input latency in puNES even with USB controllers so I am going to be testing this out and need an accurate display of how emulator detects input so that I can do this.

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/49958dc73218beb78201ec8fc0d3c2bf20e56115

Last 0.101 WIP
Windows:
https://dl.dropboxusercontent.com/u/21595068/punes32.wip.d3d9.zip
https://dl.dropboxusercontent.com/u/21595068/punes64.wip.d3d9.zip
https://dl.dropboxusercontent.com/u/21595068/punes32.wip.sdl.zip
https://dl.dropboxusercontent.com/u/21595068/punes64.wip.sdl.zip
Linux:
https://dl.dropboxusercontent.com/u/21595068/punes32
https://dl.dropboxusercontent.com/u/21595068/punes64

**Comment by jcdenton2k** [comment]
Would love to see these added to the releases page.  Will test these out and post back with updated information.

**Comment by punesemu** [comment]
>Save Battery RAM file every 3 mins (but how often will it save if this option is not selected?)

Without this option, the battery RAM it's saved when you close the emulator or change rom.

>PPU Overclock doesn't save even when doing 'Save Settings' manually.

PPU Overclock settings are per-gmae settings that is valid for the single ROM to which are applied. Load the game and will be automatically loaded.

>Disable Sepia Color on Pause' doesn't work when any NTSC Software Filters (Composite, S-Video, or RGB) are used since the filters override any potential Sepia Color.

https://github.com/punesemu/puNES/commit/0c3922b95df0a2c91e8b05b428cc1ba4ef00c9a9

>Two console output messages about QWidget::setMinimumsize: (/setInfoBar) Negative sizes (-340,0) are not possible. Also one for setMaximumsize with similar values.

This is not a bug. Are messages of QT lib that try to change the size of some elements of the window when it is still not visible.

>A console display appears when running the emulator that may confuse newbie emulator users. This should not appear as a separate window; expected behavior should be similar to the v0.100 release.

It's not a issue. This console is present only in WIP version and I use for debug purpose.

>I'm SO happy with the InputDisplay that when I make a YT video showing puNES has NO input latency I will make the haters EAT CROW! THEY WILL EAT CROW HAHA! =D

:)
> don't know why the 'Sepia on Pause' and 'Turned off Static' were added in. Have people actually been asking for those to be done as features? >_>

I simply added them because I like them. :)

>The UI is a bit of a mess with duplicated functionality so hopefully a proper unified UI can be planned that will have all the options easily accessible without having to dig through menus with careful mouse control.

This is also on my list of things to do.

**Comment by jcdenton2k** [comment]
According to Google Translate, you use Italian.  It is quite different from Spanish.  I'd like to request another addition to that ToDo list of yours: Change code comments from Italian to English.

There are many people that thought the Emulator itself was Italian-only because of this.  Just want to expand the audience a bit.  We can keep Italian-language documentation and comments but we should have English versions as well.
