### ISSUE TITLE
[Crash] NTSC Software Filters cause crash with certain OverScan values

### ISSUE THREAD

**Issue by jcdenton2k** [punesemu/puNES#28]
Happens on all release versions regardless of renderer (D3D9/SDL) or region (NTSC/Dendy/PAL).

Settings -> Video -> Software Filters -> Select NTSC RGB, NTSC S-Video or NTSC Composite
Settings -> Video -> Overscan -> Set borders

For the 'Down' value, enter any value less than 3 (such as 2 or 1 or 0).  Hit Apply or Preview.  Doesn't matter if you are doing for NTSC or PAL.  The emulator will immediately crash.

**Comment by punesemu** [comment]
Thanks for the report, I will try to figure out what the problem.

**Comment by jcdenton2k** [comment]
Thank you for looking into this!  :)

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/6030d27a0e96f7734d0e81733a3eeed1cd84a5b6

For the new WIP read https://github.com/punesemu/puNES/issues/27

**Comment by jcdenton2k** [comment]
I can confirm this bug was fixed with v0.101 WIP build linked above.
