### ISSUE TITLE
Dragon Buster - game freezes

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#281]
Dragon Buster freezes when I fall into this pit. This doesn't happen with NesHawk. I've reproduced it with these two ROMs:

* Dragon Buster (Japan) 
* Dragon Buster (World) (Namcot Collection, Namco Museum Archives Vol 1)

[save.zip](https://github.com/punesemu/puNES/files/10503488/save.zip)

![Dragon Buster (Japan)](https://user-images.githubusercontent.com/6733770/214687091-62233aa2-06a2-4448-b575-6c3ab6288ff6.png)

puNES 0.111 c347b7a D3D9
Windows 10

**Comment by punesemu** [comment]
Thx anewuser, I'll try to figure out what the problem is.

**Comment by punesemu** [comment]
You can try to play with this [WIP version](https://www.dropbox.com/s/y02hhe1hsg68elb/punes.zip?dl=1)?

**Comment by anewuser** [comment]
> You can try to play with this [WIP version](https://www.dropbox.com/s/y02hhe1hsg68elb/punes.zip?dl=1)?

Thank you. Everything seems to be working properly.
