### ISSUE TITLE
[Ballblazer (Japan)] Artefact on the top of the screen...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [punesemu/puNES#282]
Punes punes64.wip.d3d9 2023.01.2023

It seems it's not correct.

![ballblazer](https://user-images.githubusercontent.com/12481242/214850165-fc84eb6c-935b-49ba-9948-f14be0a62eed.gif)

**Comment by punesemu** [comment]
Try to see this [video](https://www.youtube.com/watch?v=qFduRt6uj2k). It should have been recorded on an original NES.

**Comment by BenjaminSiskoo** [comment]
Hey mate, I don't really know ^^

This video seems made with the real hardware too https://youtu.be/_tkwWD_BWWQ?t=418

**Comment by punesemu** [comment]
Hello Benjamin, honestly it doesn't look like a video recorded by an original console, but by an emulator. But it would take someone to try it on an original Famicon. Also remember the [overscan](https://www.nesdev.org/wiki/Overscan). 
> The NES [PPU](https://www.nesdev.org/wiki/PPU) always generates a 256x240 pixel picture. But not all of these pixels are visible on an NTSC TV, especially the top and bottom few scanlines.

There are many NES games where there are artifacts at the edges of the screen, the programmers knew they would not be visible on televisions. Try enabling overscan in the emulator.

**Comment by BenjaminSiskoo** [comment]
With the overscan, no more artefacts, Do we have overscan enabled every time or not ?

**Comment by punesemu** [comment]
It's a personal choice, I prefer without. If you want to emulate the effect of an old NTSC/PAL TV, enable it.

**Comment by BenjaminSiskoo** [comment]
Ok So I close this br :)
