### ISSUE TITLE
Unable to create a deb package from the compiled project

### ISSUE THREAD

**Issue by TCH68k** [punesemu/puNES#283]
Before these new buildsystems were introduced, with `checkinstall` i simply could make a deb package when the build was done. Now it simply fails by:
```
Installing with make install...

========================= Installation results ===========================
make: *** No rule to make target 'install'.  Stop.

****  Installation failed. Aborting package creation.

Cleaning up...OK

Bye.
```
How can i make a deb package out of it now?

**Comment by punesemu** [comment]
Hi TCH, can't you install via the cmake?
`cmake --build . --target install` or `cmake --install .`
I don't know how deb packages can be created but if I can help you, I'll gladly do it.

**Comment by TCH68k** [comment]
Of course i can. But that is not a package i can reinstall or remove. For instance if i encounter a bug, i may need to check if the previous version is affected. Sure, i can compile and install puNES versions all the time, but it is much more faster and convenient to simply remove/install packages.

As for deb packages, `checkinstall` can make them if there is a `Makefile` provided.
With the old build scheme it was no problem. Why was it necessarily to change it? To these terrible buildsystems?

**Comment by punesemu** [comment]
Initially I too had some problems with cmake but now I can say without any doubt that it has simplified my life a lot. The autotools was much more complex and making some changes to the Makefiles was never very simple, while with cmake everything is now simpler and more immediate. Searching with google I found two possible solutions:
* use (CPak)[https://cmake.org/cmake/help/latest/cpack_gen/deb.html#cpack_gen:CPack%20DEB%20Generator]
* don't use Ninja as build system but use the 'cmake -G "Unix Makefiles" ...' option to generate the classic Makefiles

The second seems to me the simplest. Have you already tried to use it?

**Comment by TCH68k** [comment]
The second method worked perfectly, thank you Fabio!

Please mention in the building instructions, that Ninja is actually not needed to build puNES, because a `Makefile` can be generated by CMake.

As for the autotools/Makefile combo vs. CMake, i believe that CMake is much more comfortable, but as a building dependency it is terrible (http://suckless.org/sucks/ see at "build systems"). If the OS the user uses contains an older CMake version than needed (or does not contain it at all), then the user will face a lot of trouble (and will spend a lot of time) until the required CMake will be complete. (I'm talking from experience here...)

And the Python-based buildsystems are even worse. First, you have to install dozens or hundreds of MB of Python stuff from the OS repo. Then, inside Python, you have to install even more now-out-of-the-OS-package-handler's-scope-stuff - including other Python-based package managers, just to get even more stuff - to breathe life into Meson or Ninja or whatever other Python-based buildingsystem... (Still talking from experience...)

So, it is definitely a good thing, that Ninja is not needed. Please mention it in the building instructions, that Ninja is optional. :)

As much these environments can make your life easier, as much they can make the user's harder. Autotools and `make` is most probably present at everywhere or if not, it only takes a simple `package-manager install autotools make` command to install them and `./configure && make && make install` is most probably will be understood by everybody, but a user who is not a programmer or a UNIX-hacker will be blocked from compiling puNES if he faces the troubles these buildsystems will create.

**Comment by punesemu** [comment]
> Please mention in the building instructions, that Ninja is actually not needed to build puNES, because a Makefile can be generated by CMake.

Done with https://github.com/punesemu/puNES/commit/4084bf80b5ad067b53f3cc1bbe27de67c3abf248.

I liked the autotools, even if it had several problems, but it was becoming difficult to maintain it using also external libraries that had already switched to other types of build systems, which instead I found much simpler with cmake (thanks again to Winterheart for his fantastic contribution). I'm not saying cmake doesn't have its flaws but so far the benefits I've found are far greater than the flaws found.
Regardless of the autotools vs cmake discussion I can consider this issue closed.

**Comment by TCH68k** [comment]
It's your decision.
As i said, i understand that for you the positive sides outweigh the negative ones. I just reflected the topic from the user's perspective, where it is exactly the opposite. (More accurately, there are no positive sides for the user.)
