### ISSUE TITLE
Falsion stutter

### ISSUE THREAD

**Issue by Skalt711** [punesemu/puNES#284]
Falsion, a Famicom Disk System game, experiences a stutter of random length that can happen at any moment during gameplay. Task Manager shows no anomaly. Normally the game has no stutter.

**Comment by Skalt711** [comment]
Going to correct myself, the slowdown emulation is wrong in Falsion. Normally the game will just run at a reduced speed while keeping music at full speed, but puNES emulates much more slowdown that stops the music - it's counted towards the lag counter. https://www.youtube.com/watch?v=BC7dIw2YXqs

**Comment by punesemu** [comment]
Hi Pippo, thanks for reporting. Can you take a test? Try disabling the option "Use fast forward when loading the disk/side" on the General Settings page and tell me if this fixe the problem. If so, I know where to start looking.

**Comment by Skalt711** [comment]
I'm not Pippo (I'm skalt711) and yeah, disabling fast forward fixes the issue. Increasing the amount of postrender scanlines happens to work around the issue as well.

**Comment by punesemu** [comment]
> I'm not Pippo (I'm skalt711)

I apologize skalt711, in addition to answering you I was writing two emails that contained many names and I got confused.
> Increasing the amount of postrender scanlines happens to work around the issue as well.

Thanks for the further information. I'll let you know as soon as I figure out what's causing the problem.

**Comment by punesemu** [comment]
I think I understand what the problem could be, could you try with this [version](https://www.dropbox.com/s/y02hhe1hsg68elb/punes.zip?dl=1) by enabling the option and disabling the postrender scanlines?

P.s. this is a D3D9 64bit version.

**Comment by Skalt711** [comment]
The custom version likely emulates the slowdown correctly, but instead of waiting to render a frame, it skips it altogether by duplicating the previous frame, then renders the next one as if there are extra postrender scanlines. I forgot that the music is always disabled when you fast forward. https://www.youtube.com/watch?v=Vkei1srAXm4

**Comment by punesemu** [comment]
I had health problems and could not continue to investigate the problem but now I can resume.

**Comment by punesemu** [comment]
Sorry for the long silence, can you try this [version](https://www.dropbox.com/s/y02hhe1hsg68elb/punes.zip?dl=1)?

**Comment by Skalt711** [comment]
Can confirm that the issue is fixed at last.
