### ISSUE TITLE
No audio on my surface pro (win 10 21H2)

### ISSUE THREAD

**Issue by Yuki001** [punesemu/puNES#285]
puNES 0.110 64bits opengl version
No sound on my surface pro. The OS is windows 10 home version 21H2 (19044.2486)
Audio settings only show "System Default" in Output Device dropdown box.   

Try mesen2 and it works with sound, so my audio device works correctly.

**Comment by punesemu** [comment]
I had health problems and could not verify the problem, now I can. I need some more information, let's start with your puNES.cfg file, can you send it to me?

**Comment by Yuki001** [comment]
Here is my config file. and setting window screenshots . thanks.
[puNES.cfg.zip](https://github.com/punesemu/puNES/files/10804298/puNES.cfg.zip)
![punes-audio](https://user-images.githubusercontent.com/13944639/220633912-d15c409c-35b3-4e60-83bc-1aa6b49dd0b7.jpg)
![mesen2-audio](https://user-images.githubusercontent.com/13944639/220633945-6e93c428-eb3e-4bf7-9fd5-c871b6a63a9d.jpg)

**Comment by punesemu** [comment]
I need some more information. I need you to do one thing for me, open a CMD and run [this version](https://www.dropbox.com/s/y02hhe1hsg68elb/punes.zip?dl=1) using the command line then send me the log messages it will show.

**Comment by Yuki001** [comment]
I run this exe and see the xaudio2 error.
The log : 

C:\Games\PuNES>punes.exe
* puNES (by FHorse) 0.111 WIP, x86_64, OpenGL, commit 2024
* folders
  config        : C:/Games/PuNES
  data          : C:/Games/PuNES
  temp          : C:/Users/Yuki/AppData/Local/Temp/puNES
* monitor 0     : LGD 12" - 2736x1824 - 0x0 (in use)
  res 0         : 2736x1824     59.000000  59.000000 *
  res 1         : 2736x1824     60.000000  60.000000
  res 2         :  640x480      59.000000  59.000000
  res 3         :  640x480      60.000000  60.000000
  res 4         :  800x600      59.000000  59.000000
  res 5         :  800x600      60.000000  60.000000
  res 6         : 1024x768      59.000000  59.000000
  res 7         : 1024x768      60.000000  60.000000
  res 8         : 1152x864      59.000000  59.000000
  res 9         : 1152x864      60.000000  60.000000
  res 10        : 1280x600      59.000000  59.000000
  res 11        : 1280x600      60.000000  60.000000
  res 12        : 1280x720      59.000000  59.000000
  res 13        : 1280x720      60.000000  60.000000
  res 14        : 1280x768      59.000000  59.000000
  res 15        : 1280x768      60.000000  60.000000
  res 16        : 1280x800      59.000000  59.000000
  res 17        : 1280x800      60.000000  60.000000
  res 18        : 1280x960      59.000000  59.000000
  res 19        : 1280x960      60.000000  60.000000
  res 20        : 1280x1024     59.000000  59.000000
  res 21        : 1280x1024     60.000000  60.000000
  res 22        : 1360x768      59.000000  59.000000
  res 23        : 1360x768      60.000000  60.000000
  res 24        : 1366x768      59.000000  59.000000
  res 25        : 1366x768      60.000000  60.000000
  res 26        : 1400x1050     59.000000  59.000000
  res 27        : 1400x1050     60.000000  60.000000
  res 28        : 1440x900      59.000000  59.000000
  res 29        : 1440x900      60.000000  60.000000
  res 30        : 1600x900      59.000000  59.000000
  res 31        : 1600x900      60.000000  60.000000
  res 32        : 1600x1200     59.000000  59.000000
  res 33        : 1600x1200     60.000000  60.000000
  res 34        : 1680x1050     59.000000  59.000000
  res 35        : 1680x1050     60.000000  60.000000
  res 36        : 1792x1344     59.000000  59.000000
  res 37        : 1792x1344     60.000000  60.000000
  res 38        : 1856x1392     59.000000  59.000000
  res 39        : 1856x1392     60.000000  60.000000
  res 40        : 1920x1080     59.000000  59.000000
  res 41        : 1920x1080     60.000000  60.000000
  res 42        : 1920x1200     59.000000  59.000000
  res 43        : 1920x1200     60.000000  60.000000
  res 44        : 1920x1440     59.000000  59.000000
  res 45        : 1920x1440     60.000000  60.000000
  res 46        : 2048x1152     59.000000  59.000000
  res 47        : 2048x1152     60.000000  60.000000
  res 48        : 2048x1536     59.000000  59.000000
  res 49        : 2048x1536     60.000000  60.000000
  res 50        : 2560x1440     59.000000  59.000000
  res 51        : 2560x1440     60.000000  60.000000
  res 52        : 2560x1600     59.000000  59.000000
  res 53        : 2560x1600     60.000000  60.000000
  res 54        : 1368x912      59.000000  59.000000
  res 55        : 1368x912      60.000000  60.000000
  res 56        : 1620x1080     59.000000  59.000000
  res 57        : 1620x1080     60.000000  60.000000
  res 58        : 2052x1368     59.000000  59.000000
  res 59        : 2052x1368     60.000000  60.000000
* common res
  0             : 2736x1824
  1             : 2560x1600
  2             : 2560x1440
  3             : 2052x1368
  4             : 2048x1536
  5             : 2048x1152
  6             : 1920x1440
  7             : 1920x1200
  8             : 1920x1080
  9             : 1856x1392
  10            : 1792x1344
  11            : 1680x1050
  12            : 1620x1080
  13            : 1600x1200
  14            : 1600x900
  15            : 1440x900
  16            : 1400x1050
  17            : 1368x912
  18            : 1366x768
  19            : 1360x768
  20            : 1280x1024
  21            : 1280x960
  22            : 1280x800
  23            : 1280x768
  24            : 1280x720
  25            : 1280x600
  26            : 1152x864
  27            : 1024x768
  28            :  800x600
  29            :  640x480
* opengl        : GPU Intel(R) Iris(R) Plus Graphics (Intel, 4.6.0 - Build 27.20.100.9621)
* opengl        : GL version 4.6 Compatibility
* opengl        : setting pass 0
* opengl        : setting pass 1
* opengl        : setting pass 2
* xaudio2       : error on create XAudio2 object
* softw bsize   : 178524 - 551
* softw limit   : 4408 - 15428

**Comment by punesemu** [comment]
> * xaudio2 : error on create XAudio2 object

Here's the problem, I can't create a XAudio2 object. In case the necessary dll is missing, can you try to install this directx package?
https://www.microsoft.com/en-us/download/details.aspx?id=35

**Comment by Yuki001** [comment]
I install directx and punes audio works perfectly. thank you.
