### ISSUE TITLE
Mapper 406 submapper 1 is broken

### ISSUE THREAD

**Issue by negativeExponent** [punesemu/puNES#287]
game fails to load

https://github.com/punesemu/puNES/blob/4084bf80b5ad067b53f3cc1bbe27de67c3abf248/src/core/mappers/mapper_406.c#L108

this line should be

`address = address ^ 0x6000;`

**Comment by negativeExponent** [comment]
thanks. now working.

**Comment by punesemu** [comment]
Thx to you for the report and for the fix.
