### ISSUE TITLE
Enhancement: Support for BPS soft-patching

### ISSUE THREAD

**Issue by jcdenton2k** [punesemu/puNES#29]
SNES9X recently added it in and having this available in puNES would get people away from IPS patches for certain translated ROMS that require large file sizes.

Basically the emulator makes a temporary new copy of the ROM, applies the BPS patch to it, and runs that temporary ROM right away.  It is more of a convenience tool for those on non-PC platforms such as mobile or (homebrew) console devices.

Relevant link with info & why BPS matters:
http://www.insanedifficulty.com/board/index.php?/topic/7296-bps-and-you-a-superior-patching-experience/

SNES9X implementation:
https://github.com/snes9xgit/snes9x/commit/b4f07bc9be7eeef9aa0baafb6ba82e9aad4f6369

**Comment by punesemu** [comment]
I'ts already on my TODO list.

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/cc4fae865adb0eb5ce60ddc64a9f3ab45241d45f
