### ISSUE TITLE
[WIP Builds] codec version outdated

### ISSUE THREAD

**Issue by eugene-s-nesdev** [punesemu/puNES#290]
I just downloaded the latest WIPs for D3D9 (punes32.wip.d3d9 / punes64.wip.d3d9)
These versions do not start on Win10

Error message:
avutil-57.dll, avformat-59.dll and avcodec-59.dll and swresample-4.dll - not detected

wip-package contains outdated versions:
avutil-56.dll, avformat-58.dll and avcodec-58.dll and swresample-3.dll

**Comment by eugene-s-nesdev** [comment]
So strange, because 29-january-2023 commit https://github.com/punesemu/puNES/commit/4084bf80b5ad067b53f3cc1bbe27de67c3abf248
works excellent

**Comment by punesemu** [comment]
Fixed with https://github.com/punesemu/puNES/commit/0c292a1ffd97e07f7ec9c43f27c151b0b65a04ec. Thx for the report.
