### ISSUE TITLE
[Request] Show current alignment status (when "randomize" or "increment" enabled)

### ISSUE THREAD

**Issue by eugene-s-nesdev** [punesemu/puNES#292]
When the Randomize Alignment checkbox is enabled in the settings, mesen shows the current alignment status in the log-window after each reset:

![mesen-align](https://user-images.githubusercontent.com/13199529/221409812-d3550963-b53e-43ec-be89-f720d521cffe.png)

I'm sure puNES should have a similar feature (for testing doesn't blindly)

**Comment by punesemu** [comment]
Hi Eugene https://github.com/punesemu/puNES/commit/68020fdd9c4949d32f64a269740b33e32cc84e8c

**Comment by eugene-s-nesdev** [comment]
Hi Fabio! Thank You, it works correctly.
