### ISSUE TITLE
Mapper 344: Double Dragon III broken gfx in GN-26 rom variant

### ISSUE THREAD

**Issue by negativeExponent** [punesemu/puNES#294]
![1677911253_2023_03_04_14:27:33](https://user-images.githubusercontent.com/54053706/222879948-12651efe-ceb9-4940-8ee8-a5dee94cea77.png)

CHR outer bank should not be masked out
https://github.com/punesemu/puNES/blob/master/src/core/mappers/mapper_GN26.c#L214

**Comment by punesemu** [comment]
Hi negativeExponent, can you send me this rom?

**Comment by negativeExponent** [comment]
[m344.zip](https://github.com/punesemu/puNES/files/10887982/m344.zip)

**Comment by punesemu** [comment]
Thx for the report.

**Comment by anewuser** [comment]
It might be a good idea to delete @negativeExponent's comment.

**Comment by punesemu** [comment]
You are right.
