### ISSUE TITLE
Awkwardly high pitched FDS wavetable voice in Falsion

### ISSUE THREAD

**Issue by Skalt711** [punesemu/puNES#295]
Self-explanatory title.

On FCEUX the FDS' wavetable channel is high pitched: https://mega.nz/file/2LY0FaiK#Fj-7TGCy1gANXI8tkmGMl903FJVcYdVMxlHfkQ4qJE8
On real hardware it plays with a normal, lower pitch: https://youtu.be/nb9HBcm_AQE?t=87
Haven't tested other FDS games.

**Comment by punesemu** [comment]
Can you try this [version](https://www.dropbox.com/s/y02hhe1hsg68elb/punes.zip?dl=1)?

**Comment by RokkumanX** [comment]
Hello, I don't know which of us you referred to but I will try out that version later tonight when I get the chance.

Thank you very much for all your hard work!

**Comment by punesemu** [comment]
I was referring to both. :wink:

**Comment by RokkumanX** [comment]
Chuck Norris approved! The intro in Zelda no Densetsu sounds normal again!

Domo arrigato.

**Comment by punesemu** [comment]
Thx for the first test but I've updated the [version](https://www.dropbox.com/s/y02hhe1hsg68elb/punes.zip?dl=1), you can try with this?

**Comment by Skalt711** [comment]
> Thx for the first test but I've updated the [version](https://www.dropbox.com/s/y02hhe1hsg68elb/punes.zip?dl=1), you can try with this?

It fixes the issue!

**Comment by RokkumanX** [comment]
I don't know what is fixed in the updated fixed version but the intro in Zelda no Densetsu sounds perfect to me nevertheless.

**Comment by punesemu** [comment]
Thanks to both of you for the support.
