### ISSUE TITLE
xBRZ 5x and 6x scaler

### ISSUE THREAD

**Issue by ADormant** [punesemu/puNES#3]
Could you add these higher multipliers to xbrz?
https://sourceforge.net/projects/xbrz/files/xBRZ/
https://github.com/gonetz/GLideN64/commit/daf18efabbae16454c83562456a6cc19b53255a1

**Comment by punesemu** [comment]
I'll do it.

**Comment by ADormant** [comment]
https://github.com/gonetz/GLideN64/commit/5bf7a4e4dea9bc7f1b0cb68db5781b386a5470b7

**Comment by ADormant** [comment]
@punesemu Any technical difficulties?
https://github.com/hrydgard/ppsspp/pull/8338/files
https://github.com/devinacker/bsnes-plus/pull/27/files
http://ngemu.com/threads/peteopengl2tweak-tweaker-for-peteopengl2-plugin-w-gte-accuracy-hack.160319/
http://ngemu.com/threads/peops-opengl-1-78-xbrz-scalers-mod.173953/

**Comment by punesemu** [comment]
No, no problem, in recent months the real life has occupied all my free time. Only yesterday I returned to the emulator. I intend to implement the two filters only that on my list of things to do there are a few things I want to do first.

**Comment by ADormant** [comment]
@punesemu  
> I returned to the emulator.

That's great to hear by the way of you ever decide to try tile replacement then GBE+ is already the best reference.
https://github.com/shonumi/gbe-plus/commits/master
https://github.com/shonumi/gbe-plus

**Comment by punesemu** [comment]
[xBRZ 5x and 6x scaler](https://github.com/punesemu/puNES/commit/329320eb2e575103b917fd8e58e1475377da20fe)
