### ISSUE TITLE
Xbox One Controllers Broke Again!

### ISSUE THREAD

**Issue by WizLizard** [punesemu/puNES#30]
I think the latest drivers Microsoft have released for the adapter has broken the previous fix. I can't configure them any more.

**Comment by punesemu** [comment]
Nooo, again?!? Damn microsoft... I need to re-find a xbox controller from someone.

**Comment by WizLizard** [comment]
I'm thinking that the new drivers fixed the previous issue the others had and now the fix you came up  with is causing problems lol.

**Comment by punesemu** [comment]
You can test this version?

https://dl.dropboxusercontent.com/u/21595068/punes32_d3d9.exe
https://dl.dropboxusercontent.com/u/21595068/punes64_d3d9.exe

**Comment by WizLizard** [comment]
@punesemu Thanks fixed, and hopefully for good lol.

**Comment by punesemu** [comment]
Ok, than I can commit the fix. Thanks.

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/e2620ec3c5b4fb42a7cad53c36635c9c078a0f09.
Updated the links of the WIP with the new builds.

**Comment by WizLizard** [comment]
@punesemu I'm sorry but I believe I made a mistake reporting this issue. It turns out that my xbox one controllers were malfunctioning due to having a direct input controller plugged in at the same time. Unplugging it and then testing the xbox one controller on puNES 0.100 there were no issues. You can probably revert the changes you made to the WIP. Again I apologize for the confusion.

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/24d1342186d1455657fb706e26866b611c3df777

**Comment by punesemu** [comment]
Added full support for the XInput https://github.com/punesemu/puNES/commit/e7226c67675487a12d3c20fc05c3b473b83e95ce. Try the new WIP.
