### ISSUE TITLE
punes-git won't start with ffmpeg 6 installed (memory access violation)

### ISSUE THREAD

**Issue by Gnatzelle** [punesemu/puNES#302]
Hi...

As the title says, i'm unable to start punes compiled from the master branch since ffmpeg 6 is installed on the system (v6 is needed for OBS Studio). if i build punes without ffmpeg-support, the error is gone and punes will start normally.

It was also pure speculation on my side that ffmpeg would cause the crash, cause if i started punes with the "--help" string, the GUI with the parameter-window would actually load, so it couldn't be a QT-Error or something.

Unfortunally i only get the "Memory access violation" message, but there is no dump or log or anything which would indicate what actually caused the crash.

Sorry if i couldn't be more specific :/

**Comment by punesemu** [comment]
Hi Gnatzelle, I was able to reproduce the problem. I will keep you informed.

**Comment by punesemu** [comment]
Please, try with the last commit.

**Comment by Gnatzelle** [comment]
I just realised that i didn't wrote which OS i'm using...it's Arch Linux btw. 
Note for myself...never writing Issue Reports again when i'm tired >.<

But...It's working again...thank you Fabio :)

**Comment by elektronicznypank** [comment]
I was to write about this issue. I use manjaro and also had those errors with a version with ffmpeg.
After last commit i successfully built puNES with ffmpeg 6.

**Comment by punesemu** [comment]
Thanks to both of you for the feedback. :beers:
