### ISSUE TITLE
Fast forwarding after muting the audio produces a crackling sound

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#303]
Hello. Please check if you can reproduce this:

* Set keyboard shortcuts for `Enable audio` and `Fast forward  (hold button)`
* Restart puNES
* Start a game 
* Mute the audio

Every time I press the `Fast forward  (hold button)` shortcut, I hear a crackling sound. This doesn't happen if I start puNES with the audio on mute.

Windows 10
puNES 64-bit WIP (D3D9)

**Comment by anewuser** [comment]
@eugene-s-nesdev Hi. Can you reproduce this?

**Comment by eugene-s-nesdev** [comment]
Do you mean a single click/pop sound when pressing and releasing the fast forward shortcut?
I was able to replicate that. It's a very minor problem though.

**Comment by anewuser** [comment]
Thank you. I just wanted to make sure that this wasn't a driver bug. It isn't a critical issue, but it is a recurring annoyance to me because I usually run puNES with the audio muted and use that shortcut often, so every time I unmute it temporarily, I have to restart the program not to keep hearing those clicks.

**Comment by punesemu** [comment]
These days I don't have the time to dedicate myself to the emulator, as soon as I can I'll try to understand what the problem is.

**Comment by punesemu** [comment]
Sorry for the wait, I'll try to understand what the problem is. I will keep you informed.

**Comment by punesemu** [comment]
Can you try the latest WIP?

**Comment by anewuser** [comment]
Thank you!
