### ISSUE TITLE
mapper 342 (Coolgirl) typo

### ISSUE THREAD

**Issue by negativeExponent** [punesemu/puNES#306]
possible typo in https://github.com/punesemu/puNES/blob/master/src/core/mappers/mapper_Coolgirl.c#LL2326C5-L2326C19
line should apply on prg_bank

see: https://github.com/TASEmulators/fceux/blob/master/src/boards/coolgirl.cpp#L1853

also, you might be interested in recent update regarding handling of mapper 23 address decoding, as it seems most current dump using such mapper were using wrong flags:
https://github.com/TASEmulators/fceux/issues/638#issuecomment-1538181930

**Comment by punesemu** [comment]
Fixed with 009dc37 and c9de664.
