### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by possiblyneal** [punesemu/puNES#311]
Great emulator!! There are many things I absolutely love about this emulator. Thanks for your hard work.

I have a few suggestions that I think would make the experience better:

I've corrected my mistake here and opened separate issues. 

Thanks :)

**Comment by anewuser** [comment]
Please always file a separate GitHub issue for each feature request or bug report you want to post. Lists with unrelated ideas make it harder for everyone to discuss and keep track of them.

**Comment by possiblyneal** [comment]
Created separate issues to avoid confusion.
