### ISSUE TITLE
GPU Shader "CRT With Curve" + Software Filter "NTSC RGB" = vertically flickering image

### ISSUE THREAD

**Issue by TCH68k** [punesemu/puNES#318]
I would like to use GPU Shader "CRT With Curve" with Software Filter "NTSC RGB", but if i do, the entire screen keeps moving up and down by a few (or one?) pixels. Is this intended? Or is it a bug? If it is not a bug, can it be turned off, or this is unavoidable with this combination? Also Software Filters "NTSC Composite" and "NTSC S-Video" are keep blinking with this GPU Shader.

**Comment by TCH68k** [comment]
Any idea?

**Comment by punesemu** [comment]
>I would like to use GPU Shader "CRT With Curve" with Software Filter "NTSC RGB", but if i do, the entire screen keeps moving up and down by a few (or one?) pixels. Is this intended? Or is it a bug? If it is not a bug, can it be turned off, or this is unavoidable with this combination?

It's the combination of the two modes, I can't do anything about it, although I must admit that that slight flickering makes the image even more "realistic" for me.

>Also Software Filters "NTSC Composite" and "NTSC S-Video" are keep blinking with this GPU Shader.

Try decreasing the value of the scanlines of the two Software Filters.

**Comment by TCH68k** [comment]
> It's the combination of the two modes, I can't do anything about it, although I must admit that that slight flickering makes the image even more "realistic" for me.

I've never seen CRTs flickering like this; phase alternation yields in a different type of flickering: a slight vibration, but not the screen visibly jumping up and down. Still, if it's not possible, then not possible.

> Try decreasing the value of the scanlines of the two Software Filters.

Thanks, decreasing it on the NTSC RGB filter solved the blinking. (The same on the CRT shader did not, it just made the screen darker.)
