### ISSUE TITLE
Old display problems

### ISSUE THREAD

**Issue by eugene-s-nesdev** [punesemu/puNES#32]
Tested also on Win 10 with 1280x1024 old non-widescreen display.

When pixel aspect ratio is 1:1 or 8:7 (NTSC) - punes work good both in window and fullscreen
When pixel aspect ratio is 5:4 or 11:8 (PAL) - fullscreen doesn't show anythihg. Only black screen is visible.

**Comment by punesemu** [comment]
Fixed in https://github.com/punesemu/puNES/commit/dbcc206263dad6efd04acd6a409785f09eb45563
