### ISSUE TITLE
Kubuntu 23.04

### ISSUE THREAD

**Issue by Blad3forc3** [punesemu/puNES#320]
Hi, Ive compiled punes with qt6 and it appears to compile fine but when i run it all i get is the outline of the window and nothing rendered inside.

**Comment by anewuser** [comment]
Does the [Flathub version](https://flathub.org/apps/io.github.punesemu.puNES) work for you?

**Comment by Blad3forc3** [comment]
Yes the flathub version works

**Comment by punesemu** [comment]
Sorry if I'm only replying now but it's been a difficult few months, only from today I have the chance to get back to work on the emulator. However it is very strange, I installed kubuntu 23.04 on a virtual machine and the emulator started normally. I would need more information to be able to analyze the problem better.

**Comment by Blad3forc3** [comment]
Thanks.
I have tried compiling punes numerous times since and every time it compiles without errors but the same thing a window opens with no contents just an outline. Ive tried with qt5, qt6 no difference. When running from the command line i do get this particular error but i have noc lue what is causing it
▶ puNES (by FHorse) 0.111, x86_64, OpenGL
▶ folders      
  config        : /home/ade/Emulators/NES
  data          : /home/ade/Emulators/NES
  temp          : /tmp/puNES
▶ opengl        : GPU NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 (NVIDIA Corporation, 4.6.0 NVIDIA 535.104.05)
▶ opengl        : GL version 4.6 Compatibility
▶ opengl        : setting pass 0
▶ opengl        : setting pass 1
▶ opengl        : setting pass 2
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM default
▶ playback open : No such file or directory

**Comment by Blad3forc3** [comment]
Just an update, you can close this as i was running the program from a shortcut and not specifying the folder path to the assets the program needs in the folder to run

**Comment by punesemu** [comment]
Thank you very much, then I consider the issue closed.
