### ISSUE TITLE
Can't load rom via command line with flatpak

### ISSUE THREAD

**Issue by bmsuseluda** [punesemu/puNES#321]
Hello together,

i installed the flatpak version of puNES in version 0.110.
When i start the emulator and choose a rom via the menu, everything runs fine, but when i try to start the rom via command line with
`flatpak run io.github.punesemu.puNES "/home/username/Documents/Emulation/NES/Europe/Battletoads (E).nes"`

With other emulators the path to the rom works just fine.
Do i have to do something special?

thanks in advance

**Comment by punesemu** [comment]
Sorry if I'm only replying now but it's been a difficult few months, only from today I have the chance to get back to work on the emulator. Thanks for the report, I'll do some tests and keep you updated.

**Comment by punesemu** [comment]
Ok, I figured out why it doesn't work from the command line. Being a sandbox environment, Flatpak does not allow access to system directories unless you specify it in the command line:
`flatpak run --file-forwarding io.github.punesemu.puNES @@ "/home/username/Documents/Emulation/NES/Europe/Battletoads (E).nes" @@`

**Comment by bmsuseluda** [comment]
thanks for the investigation. i think there has to be another way because other emulators from flathub work just fine without additional parameters.

**Comment by punesemu** [comment]
But do the other emulators (flatpak version) work by double clicking on the rom icon or using the command line?

**Comment by bmsuseluda** [comment]
they work in both ways

**Comment by punesemu** [comment]
As for the double click, I understood what it could depend on (just edit the .desktop file) but from the command line I don't understand how it can work without "--file-forwarding". Can you tell me an emulator? And can you also write me the command line you use to start it specifying the rom?

**Comment by bmsuseluda** [comment]
every emulator i tried, e.g. duckstation, pcsx2, blastem, mednafen, works the same.
flatpak run _flatpakid_ "_pathToTheRom_"

**Comment by punesemu** [comment]
Thanks so much, I'll try to figure out why.

**Comment by punesemu** [comment]
Ok I understood why it didn't work. In these days I will update the flatpack package with the necessary changes. Thanks so much for the report.

**Comment by punesemu** [comment]
If you want test the new package look here : https://github.com/flathub/io.github.punesemu.puNES/pull/4

**Comment by bmsuseluda** [comment]
this sounds great. im looking forward to it. unfortunatly im not at home for several days and can`t test it.
thanks for your effort

**Comment by bmsuseluda** [comment]
it works. thank you :)
