### ISSUE TITLE
Astral World - Illegal Opcode 0x02 at 0x007E

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#322]
Hello. [Astral World](https://www.romhacking.net/hacks/8091/) (a SMB ROM hack) works on other emulators, but puNES ab41bc1 shows this error message: `Illegal Opcode 0x02 at 0x007E`.

**Comment by punesemu** [comment]
Sorry if I'm only replying now but it's been a difficult few months, only from today I have the chance to get back to work on the emulator.

**Comment by anewuser** [comment]
Thank you for fixing it. I hope everything's going well with you now!
