### ISSUE TITLE
Saves convertions is not working.

### ISSUE THREAD

**Issue by CraigIst** [punesemu/puNES#323]
Saves files and saves states from other NES emulators are not working at all even if you change the extensions to prb and pgs. How this is possible?

**Comment by punesemu** [comment]
Sorry if I'm only replying now but it's been a difficult few months, only from today I have the chance to get back to work on the emulator. Emulator savestates are not compatible. Each emulator has its own format and variables.

**Comment by CraigIst** [comment]
What about the normal save sav. and srm.? This is the only reason why I don't use Punes for now because I can't transfer my saves from FCEUX. My saves from FCEUX are working fine on most emulator. I saves from other emulators can be transfered on PUnes i will use Punes for sure.

**Comment by CraigIst** [comment]
> The .sav files were never compatible, the .srm files were probably compatible (although I never tested). In 0.111 WIP I actually changed the format making it no longer compatible but it's something I can work on to make them compatible again. What version are you using, windows or linux?

.sav where compatible before. I am on windows 10 64 bits. Could be great to make everything compatible once again. Thanks!

**Comment by CraigIst** [comment]
Even the old saves (prb) of Punes 0.107 are not compatible anymore with the last version of punes. Something broke in the last update...   Save files are not the same size in both versions...

**Comment by punesemu** [comment]
Hi Craigst, if you don't mind I will use you as a tester, do you use the opengl or d3d9 version?

**Comment by CraigIst** [comment]
> Hi Craiglst, if you don't mind I will use you as a tester, do you use the opengl or d3d9 version?

Sorry for the late reply. I use d3d9 version but the opengl version have the same issue. Thank you.

**Comment by punesemu** [comment]
This a test version (D3D9 Win64) [punes.zip](https://www.dropbox.com/s/y02hhe1hsg68elb/punes.zip?dl=1), can you try with this?

**Comment by CraigIst** [comment]
> This a test version (D3D9 Win64) [punes.zip](https://www.dropbox.com/s/y02hhe1hsg68elb/punes.zip?dl=1), can you try with this?

I just Tested and this is working fine once again! So hopefully everything come back to normal in the next  64 bits version!  But a new issue appear in this test... The fast foward option is not working anymore... Many Thanks!

**Comment by punesemu** [comment]
>I just Tested and this is working fine once again!

OK, so what I thought was right. Thanks so much for the feedback.

>The fast foward option is not working anymore... 

This is a debug version compiled without optimizations therefore very slow, it's normal that fast forward does not work. If it works in the [WIP](https://github.com/punesemu/puNES#floppy_disk-work-in-progress-wip-builds-) version then there are no problems.

**Comment by punesemu** [comment]
I can consider this issue closed.

**Comment by CraigIst** [comment]
> I can consider this issue closed.

Some games still have some issues after testing like StarTropics 1 and 2 by the way. Emulator is not saving in the right format for those game like the other games before.

**Comment by punesemu** [comment]
By using the nes20db.xml the emulator is much more precise in using the sizes of PRGROM, PRGRAM, CHRROM and VRAM actually used by the rom. Startropics 1 and 2 use a PRGRAM of 1024 bytes and the prb file used by the emulator is of that size, without the nes20db.xml it would use a PRGRAM of 8kB which is probably the one used by FCEUX. I implemented the use of nes20db.xml to make the emulator even more precise.

**Comment by CraigIst** [comment]
> By using the nes20db.xml the emulator is much more precise in using the sizes of PRGROM, PRGRAM, CHRROM and VRAM actually used by the rom. Startropics 1 and 2 use a PRGRAM of 1024 bytes and the prb file used by the emulator is of that size, without the nes20db.xml it would use a PRGRAM of 8kB which is probably the one used by FCEUX. I implemented the use of nes20db.xml to make the emulator even more precise.

Well I don't understand anything about coding but like I said all the previous version of Punes are working fine with the saves of all games :)
