### ISSUE TITLE
Gradius II - unplayable on 0.111 WIP

### ISSUE THREAD

**Issue by CaptainLancer** [punesemu/puNES#324]
Ship explodes immediately after respawning
▶ puNES (by FHorse) 0.111 WIP, x86_64, D3D9, commit 2065
  folder        : D:/puNES/roms
  format        : iNES 1.0
  nes20db       : yes
  console type  : Regular NES/Famicom/Dendy
  CPU timing    : NTSC NES
  NES mapper    : 25
  submapper     : 1 *
  mirroring     : horizontal
  PRG RAM       : 2048 *
  PRG 8k rom    : 16   [ C71D4CE7 131072 ]
  CHR 4k vrom   : 32   [ 537B6F6A 131072 ]
  sha1prg       : 1f5a56391af6a1570d4376de117ecc8f67586630
  shachr        : 7c63a0f2df6996f49aa7ada6ff21572d45435132
  CRC32         : 5ADBF660
  CPU/PPU alig. : PPU 1/3, CPU 0/11
  Note          : * different values than the header

![Gradius II (Japan)_000002](https://github.com/punesemu/puNES/assets/133787347/edb9b93e-7dcb-4b33-8003-041ce11377e5)

**Comment by punesemu** [comment]
Hi, thx for the report. Please try the latest WIP.

**Comment by CaptainLancer** [comment]
Game's running fine after the changes. Many thanks!

**Comment by punesemu** [comment]
With these two commits (https://github.com/punesemu/puNES/commit/c9de664c6cd150a7b677abc362793f950a1a2fa8 and https://github.com/punesemu/puNES/commit/3be91cc2416127992f11535dd7546fbe58f89826) I have made heavy changes to the emulator core and have also introduced several bugs that I am solving as I find them. Reports like yours are greatly appreciated, thanks again.
