### ISSUE TITLE
puNES not full screening properly with sideways monitor 

### ISSUE THREAD

**Issue by Dionicio3** [punesemu/puNES#329]
I'm trying to use puNES as my main NES emulator on my Steam Deck, however there seems to be an issue when it comes to sideways displays. As you may know, the Steam Deck's screen is rotated 90° CCW in software, and this seems to mess up the emulator's full screen mode. I tested it with an external monitor and it full screens fine on that one 

EDIT: I should note I'm using v0.110 from Flathub
![IMG_20231024_162652_config](https://github.com/punesemu/puNES/assets/61460279/37158810-73e8-4fbf-aa4f-85c6862e8caa)

**Comment by punesemu** [comment]
Hi Dionicio3, many thx for the report. I think I understand what the problem could be and I should have solved it in my personal brach but I have no possibility of testing it on a steam deck as I don't have it. Any ideas on how we could do this?

**Comment by Dionicio3** [comment]
If you're able to make an appimage, I can run and test it

**Comment by punesemu** [comment]
Try this [puNES-x86_64.AppImage](https://www.dropbox.com/scl/fi/enicrtel1ljvgx3lex1es/puNES-x86_64.AppImage?rlkey=yayrnqj47v6c5e55egxl4bsyl&dl=1).

**Comment by punesemu** [comment]
Have you had a chance to try it?

**Comment by Dionicio3** [comment]
Apologies about the delay, I got kinda busy. Unfortunately, it doesn't seem to fully fix the issue, as now it's way too zoomed in
![IMG_20231028_141152_config](https://github.com/punesemu/puNES/assets/61460279/e1c44c62-3691-4df2-a301-dfa0ff3f335d)

**Comment by punesemu** [comment]
Don't worry, I don't have much time either. I'm trying to recreate the problem but it's not easy without having a steam deck. If it doesn't bother you, I'll have you do some more tests as soon as I have news.

**Comment by punesemu** [comment]
Can you tell me what the fullscreen resolution is? 1280x800?

**Comment by Dionicio3** [comment]
yes it's 1280x800

**Comment by punesemu** [comment]
I can't reproduce the "zoom" problem and I can't think of any reason why the image should be enlarged. Can you pass me your "puNES.cfg" configuration file?

**Comment by punesemu** [comment]
I installed the SteamOS used with the deck on a virtual machine and I wasn't able to recreate the problem on this either. Can you run the AppImage from a terminal? If so, I will prepare a debug version for you and you will have to pass me the log messages and the puNES.cfg file.

**Comment by Dionicio3** [comment]
I'll try it out tomorrow, but for now, you should try setting the VM to a vertical resolution (technically the Steam Deck is 800x1280, then turned sideways in software). You might be able to replicate it like that

**Comment by punesemu** [comment]
With a resolution of 800x1280 I have no problem, this makes me think that it is the software rotation that creates it and it is the only thing that I cannot reproduce since I have no idea how it is done by the steam deck.

**Comment by punesemu** [comment]
Please can you try this version? [puNES-x86_64.AppImage](https://www.dropbox.com/scl/fi/8ygpm6hpv9s9qk531jf6y/puNES-x86_64.AppImage?rlkey=5k0r9xp6c14t69s7kqa6mqvm7&dl=0)

**Comment by Dionicio3** [comment]
Sorry for the late response (again). This build displays correctly when "Use integer scaling" is enabled, but otherwise still displays zoomed in. I would upload a picture, but for whatever reason GitHub isn't letting me

**Comment by Dionicio3** [comment]
Also, I'm just running it from double clicking from within Dolphin File Manager

**Comment by punesemu** [comment]
>Sorry for the late response (again).

This is not a problem, indeed, thank you for the feedback. To solve problems I can only rely on your tests.

>This build displays correctly when "Use integer scaling" is enabled, but otherwise still displays zoomed in. I would upload a picture, but for whatever reason GitHub isn't letting me

Ok, so we solved a problem. One step at a time.

**Comment by punesemu** [comment]
I will bother you again to do some more tests.

**Comment by Dionicio3** [comment]
Alright, sounds good

**Comment by punesemu** [comment]
I've update the AppImage, can you try this ? [puNES-x86_64.AppImage](https://www.dropbox.com/scl/fi/my83loop1904a06lhbqfv/puNES-x86_64.AppImage?rlkey=n6gtcns8ljgio4ihwhmw7d1t7&dl=1)

**Comment by Dionicio3** [comment]
Everything seems to be working in fullscreen now, awesome

**Comment by punesemu** [comment]
Great, I'll do some more tests and then commit the fix.

**Comment by punesemu** [comment]
I can consider this issue closed.

**Comment by punesemu** [comment]
However, I am very pleased to know that the emulator also works on steam deck, thanks for the good news.

**Comment by punesemu** [comment]
Thanks for introducing me to AppImages, now it will be possible to download the [WIP](https://github.com/punesemu/puNES#floppy_disk-work-in-progress-wip-builds-) always updated to the latest commit even for those who do not want or cannot compile the sources.

**Comment by Dionicio3** [comment]
Oh no problem, glad I was able to help out with this
