### ISSUE TITLE
[Bug] NTSC filter causes 'red line' w/OverScan

### ISSUE THREAD

**Issue by jcdenton2k** [punesemu/puNES#33]
When you use any NTSC software filter (Composite, S-Video, RGB) with any OverScan values, a 'fuzzy' bright red line will always appear at the bottom of the display.  It appears more prominently with OverScan values of at least 8 Top and 8 Bottom or larger.

There seem to be many bugs related to the NTSC filters, eh?  :)

**Comment by punesemu** [comment]
I had already noticed (the bug was introduced with fixes committed these days). I will fix after I made windows version UTF8 compliance (https://github.com/punesemu/puNES/issues/31).

**Comment by punesemu** [comment]
Fixed in https://github.com/punesemu/puNES/commit/fc6a1668ff47731d7cb3c5d11c9ac5e100b768af.
The latest WIP at (https://github.com/punesemu/puNES/issues/31).
