### ISSUE TITLE
Changing palette settings affects NTSC RGB filter

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#331]
Hello. Please try to reproduce this:

1. Download the latest Windows D3D9 build
2. Open a game and enable the NTSC RGB software filter 
3. Go to the `Palette` tab and click on `Reset palette`

Result: the visual affects change to something like the NTSC Composite filter, even though the `Filters` tab stays the same. This is fixed by closing the game and then re-opening it, or clicking on `Reset parameters to defaults`.

puNES 8ea5cb7a D3D9
Windows 10

**Comment by punesemu** [comment]
Yes, I can reproduce the problem, I will keep you updated.

**Comment by punesemu** [comment]
Try the last WIP.

**Comment by anewuser** [comment]
I mentioned the reset option just as an example of a palette change. The issue is still present when I pick another palette from the drop-down menu:

![palette](https://github.com/punesemu/puNES/assets/6733770/7d95c35d-4557-46cf-b84f-3fdfa6c37aca)

**Comment by punesemu** [comment]
Sorry for the delay. Now I should have it definitively fixed.

**Comment by anewuser** [comment]
Thank you!
