### ISSUE TITLE
Vs. System Palette issue

### ISSUE THREAD

**Issue by Chipsum** [punesemu/puNES#332]
There is a problem with puNES emulating Goonies (VS)
![image](https://github.com/punesemu/puNES/assets/37517008/f343475f-47b3-4d66-af63-e02c1a622021)

`puNES version: v0.110`
ROM:
`File SHA-1: 4CBF42BCD642A0B85FC17869CD1DE1C43B1A06EC`
`File CRC32: 6C6DFC4F`
`ROM SHA-1: 730AFCD33209469D4F2B2B0ABBF86A22AA052609`
`ROM CRC32: 74F713B4`

**Comment by anewuser** [comment]
Hey. Your ROM works fine for me with the [latest WIP build](https://github.com/punesemu/puNES#floppy_disk-work-in-progress-wip-builds-). Please always test it out before filing new issues.

**Comment by Chipsum** [comment]
I was completely unaware of that I am so sorry !
