### ISSUE TITLE
Adjust default PAL overscan values according to hardware tests.

### ISSUE THREAD

**Issue by eugene-s-nesdev** [punesemu/puNES#335]
Hi Fabio.
I did hardware tests on PAL systems some years ago.
So, minor tweaking of default values needed:

![overscan](https://github.com/punesemu/puNES/assets/13199529/69fe7a02-8371-4525-8e9b-587088f8160a)

1,0,2,2 for PAL/Dendy instead of 8,8,8,9

**Comment by punesemu** [comment]
Hi Eugene, I completely trust your work.

**Comment by eugene-s-nesdev** [comment]
TV-tuners and all my CRT's give equal values:
![hw](https://github.com/punesemu/puNES/assets/13199529/58f5bf2f-f247-42fc-a9fd-912f1a8c8ce9)

**Comment by punesemu** [comment]
I can consider this issue closed.
