### ISSUE TITLE
Super 1997 4-in-1 [p1] flickering

### ISSUE THREAD

**Issue by vicde** [punesemu/puNES#337]
Super 1997 4-in-1 [p1] 

Game - Eliminator boat
awards ceremony after the end of the race is flickering

**Comment by anewuser** [comment]
@vicde Please attach a save state when you report such issues. Have you checked if this also happens with the original ROM?

**Comment by vicde** [comment]
Since it's a pirate rom, may be this is a bad dump or something like this. I think you can close this issue. Thanks for support.

**Comment by anewuser** [comment]
@punesemu If you want to look into it, here's a save state:

[Super 1997 4-in-1 [p1].zip](https://github.com/punesemu/puNES/files/13312996/Super.1997.4-in-1.p1.zip)


[Super 1997 4-in-1 [p1].webm](https://github.com/punesemu/puNES/assets/6733770/b1563fe3-4c8c-4733-afb5-5d056a346c06)



This doesn't happen with the original ROM.

**Comment by punesemu** [comment]
Hi @vicde, thx for the report, I'll try to take a look at it in my mapper implementation but being a pirated rom it's very likely that it's a bug in the rom itself.

**Comment by punesemu** [comment]
I haven't found any errors in my implementation of the 219 mapper. I consider this issue closed at least until someone checks the rom on real hardware.
