### ISSUE TITLE
Snail Hop - Illegal Opcode 0x02 at 0x0009

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#339]
Hello. [Snail Hop](https://libra-bits.itch.io/snail-hop-nes) (an aftermarket game) has graphical glitches on puNES and crashes after you move right. This doesn't happen on Mesen 2.0.

puNES:
![puNES](https://github.com/punesemu/puNES/assets/6733770/410505c7-1529-4d51-ac13-4c98fb70c19f)

Mesen 2.0:
![Mesen](https://github.com/punesemu/puNES/assets/6733770/8be72f17-3d43-4821-a54d-c92d68b13805)

puNES D3D9 4ce1d714 
Windows 10

**Comment by punesemu** [comment]
I should have fixed it.

**Comment by anewuser** [comment]
Thank you!
