### ISSUE TITLE
Request: Release new puNES updated binary builds from source on a schedule

### ISSUE THREAD

**Issue by jcdenton2k** [punesemu/puNES#34]
So the WIP builds for v0.101 were posted in this thread:
https://github.com/punesemu/puNES/issues/27#issuecomment-258989631

So my question is when a non-WIP build will be released as an updated build?  We haven't had a proper release updated build since April of this year.  It would be better to have an updated build every month but even every 3 months will work.

**Comment by jcdenton2k** [comment]
No response?  O_O

**Comment by punesemu** [comment]
I'm sorry, I'm working hard to make the emulator utf8 compatible and do not have much time.  Your idea is something realizable.

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES#wip
