### ISSUE TITLE
Swords and Runes - unplayable ROMs

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#340]
Hello. The moving icon/character never appears on [Swords and Runes](https://www.solegooseproductions.com/?page_id=16) and [Swords and Runes III](https://www.solegooseproductions.com/?page_id=649) (aftermarket games). This doesn't happen on Mesen 2.0.

puNES:
![puNES](https://github.com/punesemu/puNES/assets/6733770/b0917a90-de41-4872-9d28-ae70023e7ba5)

Mesen 2.0:
![Swords and Runes (USA) (Aftermarket) (Unl)_001](https://github.com/punesemu/puNES/assets/6733770/cb366ea3-ff87-4f5f-9293-a92ac459ddc4)

puNES D3D9 4ce1d71
Windows 10

**Comment by punesemu** [comment]
Fixed with 82b1285. Thx for the report.
