### ISSUE TITLE
Nuked-OPLL core update (sync with upstream)

### ISSUE THREAD

**Issue by eugene-s-nesdev** [punesemu/puNES#341]
Hi Fabio. I guess this info will be interesting:

https://github.com/nukeykt/Nuked-OPLL/commits/master
https://github.com/nukeykt/VRC7dump/commits/master

`\puNES-master\src\core\mappers\opll.c`
is outdated a bit (1.0.1 instead of 1.0.2)

**Comment by punesemu** [comment]
Many thx Eugene, updated.
