### ISSUE TITLE
Nintendo Campus Challenge 1991 - "mapper 555 not supported"

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#342]
Hello. Are MAME mapper implementations useful for you? It supports Mapper 555. 

The No-Intro ROM can be launched with this command: `mame.exe nes -cart "Z:\Nintendo Campus Challenge 1991 (USA) (Competition Cart) [b].zip"`  ("To play, press start on controller 2" - assigned to the number `2` key itself by default).

Here's the relevant code: https://github.com/mamedev/mame/blob/63fdf58bac60f72cd64eeeee1af6eb7d43bcc301/src/devices/bus/nes/event.cpp#L172

**Comment by punesemu** [comment]
Added.

**Comment by anewuser** [comment]
Thank you for adding it. The three games in the challenge are working, but the text overlay is displaying random (mostly Chinese) characters:

![screenshot](https://github.com/punesemu/puNES/assets/6733770/88a67722-97e0-4caf-8a14-8946c6ad865b)

**Comment by punesemu** [comment]
Try the last WIP.

**Comment by anewuser** [comment]
The challenge timer is now working properly, but a new 40:00 timer is displayed over the end screen: 
[p02.zip](https://github.com/punesemu/puNES/files/13368716/p02.zip).

Some other notes:

* If you die on Dr. Mario, it gets stuck on the "Game Over" screen for the rest of the challenge until the timer runs out ([p01.zip](https://github.com/punesemu/puNES/files/13368620/p01.zip)), but this is likely the expected behavior. It also happens on MAME.
* Interestingly, having the zapper plugged into the second controller port automatically skips the title screen. Also reproduced on MAME.

**Comment by punesemu** [comment]
>The challenge timer is now working properly, but a new 40:00 timer is displayed over the end screen

Fixed with 5470623.

**Comment by punesemu** [comment]
Thanks to your report I discovered a serious bug in the save states, I was not saving some variables correctly. I fixed it in my personal branch, after I apply the patch on github the old savestates will no longer be compatible.
