### ISSUE TITLE
Thinking Game Collection - "mapper 170 not supported"

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#343]
Hi. This mapper is missing too:

No-Intro ROM: `Fujiya Famicasse Series 3 - Thinking Game Collection (Japan) (En) (Unl)`
Mesen 2.0: https://github.com/SourMesen/Mesen2/blob/master/Core/NES/Mappers/Unlicensed/Mapper170.h
FCEUX: https://github.com/TASEmulators/fceux/blob/master/src/boards/170.cpp

**Comment by punesemu** [comment]
Added.

**Comment by anewuser** [comment]
Thank you.
