### ISSUE TITLE
Firehawk - unplayable ROMs

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#344]
Hello. `Firehawk (USA) (Unl)` and `Firehawk (Europe) (Unl)` glitch out at the beginning of the first level on puNES:

![Firehawk (USA) (Unl)_000001](https://github.com/punesemu/puNES/assets/6733770/abfdad2b-9ddb-43a0-89b6-23310fa3101d)

Mesen 2.0:

![Firehawk (USA) (Unl)_000](https://github.com/punesemu/puNES/assets/6733770/c3db13d9-e075-4fc2-874f-d3833a8d7dc4)

puNES D3D9 7acc1fe
Windows 10

**Comment by punesemu** [comment]
Fixed.

**Comment by anewuser** [comment]
Thank you!

**Comment by punesemu** [comment]
I thank you for the thorough beta testing.
