### ISSUE TITLE
Some layout fixing in Arabic

### ISSUE THREAD

**Issue by Chipsum** [punesemu/puNES#347]
Hi :D

When choosing Arabic language, the layout changes from LTR to RTL, which is perfect.

Except for these controls, must stay LTR

![Screenshot 2023-11-25 005112](https://github.com/punesemu/puNES/assets/37517008/1ad41239-5ade-4e3d-a7f6-1f47702c5e91)
![Screenshot 2023-11-25 005122](https://github.com/punesemu/puNES/assets/37517008/29bff11b-8077-45ca-b5fd-0040d0e84c42)
![Screenshot 2023-11-25 005125](https://github.com/punesemu/puNES/assets/37517008/f78ddab4-4645-41fe-bb9c-46980ffbb038)

Thanks

**Comment by punesemu** [comment]
Hi Chipsum, please try the last WIP.

**Comment by Chipsum** [comment]
Excellent as always Fabio, Well done ! ❤️

**Comment by Chipsum** [comment]
@punesemu I am so Sorry I forgot these ones:

The virtual keyboards, Subor and Family basic keyboards
the controls in red
![image](https://github.com/punesemu/puNES/assets/37517008/d14dd978-efc4-44b5-9e2d-74414d863653)
![image](https://github.com/punesemu/puNES/assets/37517008/72e383cc-d9ab-4a68-aa4d-a09bb344a9d3)
