### ISSUE TITLE
Mapper 153 glitches

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#348]
Hello. `Famicom Jump II - Saikyou no 7 Nin (Japan)` glitches out on puNES:

![Famicom Jump II - Saikyou no 7 Nin (Japan)_000001](https://github.com/punesemu/puNES/assets/6733770/0a8d2786-c394-42df-a7f7-6ef97ca04b16)

Nestopia UE 1.52.0:

![Famicom Jump II - Saikyou no 7 Nin (Japan)_002](https://github.com/punesemu/puNES/assets/6733770/e3cc4988-1712-4360-a068-4bd93bc4b6c3)

puNES D3D9 b05c105
Windows 10

**Comment by punesemu** [comment]
Fixed. Thx for the report André.
