### ISSUE TITLE
Request: AutoSave SaveGame files from 180 seconds to 5 seconds

### ISSUE THREAD

**Issue by jcdenton2k** [punesemu/puNES#35]
First referenced here: https://github.com/punesemu/puNES/issues/20

I'd like the limit to be shortened from 180 (!) seconds to a more reasonable 5 seconds.  I don't know of any other emulator that takes that long to write save data and there's a great deal that could mess up in 180 seconds if it gets lost.

Please lower the auto-save option from 180 seconds to 5 seconds if possible.  Thanks!

**Comment by jcdenton2k** [comment]
I'd also love it if the 'PRB' files were renamed to 'SAV' files which are standard across every other NES emulator that is released.

It would be nice to make it as frictionless as possible to switch to puNES.

**Comment by punesemu** [comment]
> Please lower the auto-save option from 180 seconds to 5 seconds if possible. Thanks!

Three minutes, in my experience, is adequate time. There are several reasons that led me to make this decision for example using the emulator on a usb pen where writing every 5 seconds is not a good idea.

> I'd also love it if the 'PRB' files were renamed to 'SAV' files which are standard across every other NES emulator that is released.

I'll think about it.

**Comment by jcdenton2k** [comment]
I understand your reasoning, but perhaps notice what is in your own punes.config file:

`[system]
# possible values: disabled, gamegenie, cheatslist
cheat mode=disabled
# possible values: 2x, 3x, 4x, 5x
fast forward velocity=2x
# possible values: yes, no
pause when in background=no
# possible values: pal, ntsc, dendy, auto
preferred mode=auto
# possible values: yes, no
save battery ram file every 5 sec=yes
# possible values: yes, no
save settings on exit=yes`

**Comment by punesemu** [comment]
It's only a typo but I could add an option. For now I have other priorities, but I'll think.
