### ISSUE TITLE
Gall Force broken by automatic switch

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#351]
Hello. `Gall Force - Eternal Story (Japan).fds` starts pausing by itself as soon as the first level starts when `Switch the disk/side automatically` is checked in the puNES settings.

puNES D3D9 https://github.com/punesemu/puNES/commit/98d13f60e974222bf1f8626190826182de572baf
Windows 10

**Comment by punesemu** [comment]
This rom is not compatible with the autoswitch features. To be able to create the features I simulate the eject and insert of the floppy image but this is the first game I've found that pauses the game every time the eject is performed. For games with this control the features must be disabled.

**Comment by anewuser** [comment]
>this is the first game I've found that pauses the game every time the eject is performed.

Thank you. I haven't found any other case like this either.

**Comment by anewuser** [comment]
The translation hack is broken too: `Gall Force - Eternal Story (Japan) [T-En by Gil Galad v1.0].fds`.

**Comment by punesemu** [comment]
Hi André, when you have time can you try the latest WIP (0f84dea)?
