### ISSUE TITLE
Disk System graphical glitches

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#352]
Hello. I've encountered these graphical glitches with puNES:

- [x] `Akuu Senki Raijin (Japan) (Disk Writer)` - glitchy loading screen before the "Select name" screen. It looks fine on Nestopia UE.

![Akuu Senki Raijin (Japan) (Disk Writer)_000002](https://github.com/punesemu/puNES/assets/6733770/b6ae88c1-8af0-44ef-a5a1-99b8fc2c3a4b)

- [x] `Time Twist - Rekishi no Katasumi de... - Zenpen (Japan)` - jumpy textboxes. They look fine on Nestopia UE. The image below is a static screenshot just to illustrate what I mean by "textboxes":

![Time Twist - Rekishi no Katasumi de  - Zenpen (Japan)_000001](https://github.com/punesemu/puNES/assets/6733770/9fcd8871-cbf7-424a-a1f5-19c554a0cf4c)

- [x] `Topple Zip (Japan)` - major graphical glitches in the middle of the screen after starting the first level. Not always reproducible.

![Topple Zip (Japan)_000001](https://github.com/punesemu/puNES/assets/6733770/72c32b12-c355-4a84-9905-149db9210ad5)

puNES D3D9 8a6ed11
Windows 10

**Comment by punesemu** [comment]
Try the last WIP (20b26f482462f376fc3c292048fd9ccfea9ea959).
>`Topple Zip (Japan)` - major graphical glitches in the middle of the screen after starting the first level. Not always reproducible.

I think it might be a bug in the game and not the emulator.

**Comment by anewuser** [comment]
`Akuu Senki Raijin (Japan) (Disk Writer).qd` sometimes looks fine with 30170cb0, but other times even the HUD is glitchy:

![Akuu Senki Raijin (Japan) (Disk Writer)_000001](https://github.com/punesemu/puNES/assets/6733770/d69f2296-33f0-4e56-a8ad-d4642fb6c6b0)

This isn't caused by save files. I deleted all puNES folders and restarted it before testing it again.

**Comment by punesemu** [comment]
Please Try the last WIP (fe10203).

**Comment by anewuser** [comment]
This game seems to be always loading correctly now. Thank you!

**Comment by anewuser** [comment]
Sorry, can you check the beta ROM too? `Akuu Senki Raijin (Japan) (Beta) (1987-06-10).fds`.

For the sake of documentation, `Chitei Tairiku Ordola (Japan)` has a flashing horizontal line on its loading screens, but this happens on real hardware too: https://youtu.be/2Kyv_zYEP-w?t=1125 .

**Comment by punesemu** [comment]
Hi André, when you have time can you try the latest WIP (d913e3b)?
