### ISSUE TITLE
Show a fast forward icon

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#354]
Since sometimes it's not clear whether puNES is fast-forwarding, it'd be nice to have an icon on the screen. This can also be useful for people who accidentally toggle it with the default keyboard shortcut.

**Comment by CraigIst** [comment]
Fot some reason the fast foward option in the last version is extremely slow compared to the versions before. The fast foward before was lighting fast and now run the game like something 25% faster only...

**Comment by punesemu** [comment]
>Since sometimes it's not clear whether puNES is fast-forwarding, it'd be nice to have an icon on the screen. This can also be useful for people who accidentally toggle it with the default keyboard shortcut.

Added, try the last WIP.

>Fot some reason the fast foward option in the last version is extremely slow compared to the versions before. The fast foward before was lighting fast and now run the game like something 25% faster only...

I can't reproduce the problem, what version are you using?

**Comment by anewuser** [comment]
>Added, try the last WIP.

Thank you!

**Comment by punesemu** [comment]
I'm not sure if I'll use another icon but at least the feature is implemented.

**Comment by punesemu** [comment]
>>Fot some reason the fast foward option in the last version is extremely slow compared to the versions before. The fast foward before was lighting fast and now run the game like something 25% faster only...
>
>I can't reproduce the problem, what version are you using?

No updates, closed.
