### ISSUE TITLE
Mapper 354

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#355]
Hello. Mapper 354 isn't supported by puNES yet. There's information for developers and a sample ROM file on the NesDev.org forum: https://forums.nesdev.org/viewtopic.php?p=284763#p284763.

Example implementation: https://github.com/negativeExponent/fceux/blob/master/src/boards/354.cpp

**Comment by punesemu** [comment]
Added, thx for the report.

**Comment by anewuser** [comment]
Buon Natale!

**Comment by punesemu** [comment]
Thank you so much, Merry Christmas to you too!
