### ISSUE TITLE
Input display showing Left + Right and Up + Down even when they are disabled

### ISSUE THREAD

**Issue by ChessMan14** [punesemu/puNES#358]
I use puNES to speedrun Super Mario Bros. 3 and one of the rules for this game is that L + R and U + D are not permitted. The option in settings to not permit L + R and U + D works for the actual input, but the input display still show that I'm doing the illegal inputs. For some reason, the input display does not show the the left + right if you are holding down.

For example:
![image](https://github.com/punesemu/puNES/assets/93461310/ae883f4a-47c9-4772-9378-c02e7177febf)

In this image I'm holding Left and Right on my keyboard and the game is only registering one direction, but the input display show me as pressing both.

![image](https://github.com/punesemu/puNES/assets/93461310/997c9cf7-131b-4823-a6fe-e0e1a62936b9)

In this image I'm holding down Left, Down and Right and the display is working as intended (blocking out the right input).

Note that this is using version 0.111 on Arch Linux and I'm using xwayland for puNES.

**Comment by punesemu** [comment]
Thx for the report, please try with last WIP.

**Comment by ChessMan14** [comment]
Yes this has fixed it, thank you.
