### ISSUE TITLE
Using Meta button of keyboard for gamepad button works erroneously

### ISSUE THREAD

**Issue by TCH68k** [punesemu/puNES#359]
If you try to use the Meta key for any gamepad button, then the following happens. At detecting, it prints some garbage characters:
[http://oscomp.hu/depot/puNES_input_button_turbo_b_detected.png](http://oscomp.hu/depot/puNES_input_button_turbo_b_detected.png)
Though it works and you can use it without problems. When you quit, in `~/.config/puNES/input.cfg` the variable `P1K TurboB` contains `ៀ?` (0xe19f803f in hexa).

After restart, the Meta button no longer works. If you now open the config panel again, then it shows an empty field there:
[http://oscomp.hu/depot/puNES_input_button_turbo_b_first_restart.png](http://oscomp.hu/depot/puNES_input_button_turbo_b_first_restart.png)
After quit, in `input.cfg`, `P1K TurboB` contains nothing.

After the second restart, it shows that the button is configured for the `Q` button:
[http://oscomp.hu/depot/puNES_input_button_turbo_b_second_restart.png](http://oscomp.hu/depot/puNES_input_button_turbo_b_second_restart.png)
And at quit, `P1K TurboB` is indeed set to `Q` in `input.cfg`.

If you try to edit `input.cfg` and set `P1K TurboB` to `Meta`, then it keeps the value correctly, but the button is not working in the emulator.

**Comment by punesemu** [comment]
I can't reproduce the problem on any Linux system I have available. What version of Qt does your distribution use? I remember that this problem was due to a QT bug which was later fixed although I don't remember in which version.

**Comment by punesemu** [comment]
Please, can you try with the last commit (56f4ddd)?

**Comment by TCH68k** [comment]
Yes, it works perfectly.  Now it detects Meta as Meta and stores it as that and can reload it. (Although it makes no distinction between the left and right Meta, but i can live with that.) Thanks.

When will v111 be released?

**Comment by punesemu** [comment]
I need to complete some other tasks first. I can't tell you when I'll release a new version.
