### ISSUE TITLE
M547 wram bank select bit is incorrect

### ISSUE THREAD

**Issue by negativeExponent** [punesemu/puNES#363]
https://github.com/punesemu/puNES/blob/aa4085babbd52378312dd5d61cf4fc021b301277/src/core/mappers/mapper_547.c#L233C76-L233C76

wram bank  select  should be bit 3 instead of bit 7
https://www.nesdev.org/wiki/NES_2.0_Mapper_547

**Comment by punesemu** [comment]
Fixed, thx for the report.
