### ISSUE TITLE
Check if support for D3DX9 is installed

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#365]
Hi. When someone tries to run puNES (D3D9) on a clean Windows install without installing the required DirectX End-User Runtime first, he/she gets an error message saying something like `d3dx9_43.dll is missing from your computer`:

![d3dx9_43.dll is missing](https://github.com/punesemu/puNES/assets/6733770/cb103c92-6ea1-4626-862d-6248d3c660d7)

To make things easier and safer for everyone, can you make puNES check if the runtime is already installed, and then link to https://www.microsoft.com/download/details.aspx?id=35 if it is not? I'm thinking of something like this .NET dialog box:

![ScreenToGif](https://github.com/punesemu/puNES/assets/6733770/e71143b1-8b45-499e-a1b9-24fe2847146a)

**Comment by punesemu** [comment]
>To make things easier and safer for everyone, can you make puNES check if the runtime is already installed, and then link to https://www.microsoft.com/download/details.aspx?id=35 if it is not?

Now, if they are not installed, the error message contains the clickable link to the Microsoft page to download them.

**Comment by anewuser** [comment]
@punesemu  Thank you. I was also going to create a separate issue about recommending the DXD9 build if the system doesn't support the minimum required OpenGL version.  Currently, it gives this error on my Pentium P6200 laptop:

<details>
<summary>OpenGL error</summary>

![puNES](https://github.com/punesemu/puNES/assets/6733770/0c54846f-64e4-4804-ae9d-1a84ed86ef72)

</details>
