### ISSUE TITLE
Very low FPS while recording videos (D3D9)

### ISSUE THREAD

**Issue by anewuser** [punesemu/puNES#366]
Hello. puNES becomes sluggish when I try to record videos using a Ryzen 5700u laptop with a D3D9 build (either the latest build or v0.110) on Windows 10 21H2, no matter what video format I choose. 

This doesn't happen with the OpenGL builds, and I was able to record videos in the past with much slower Intel laptops. I can also record videos on this new laptop just fine using BizHawk on D3D9 mode with both its AVI writer and its FFmpeg writer.

Is there anything I can do to troubleshoot this?

**Comment by punesemu** [comment]
Hmmmm, I can't reproduce the problem on my computer, I'm also trying with virtual machines but I still can't reproduce it, I'll try on my office laptop. So, if I understand correctly, you have the same problem with version 0.110 and only in the D3D9 version. Do you still have one of your old Intel laptops? If so, could you try video recording on that and let me know?

**Comment by anewuser** [comment]
Yes, this was recorded with a Pentium P6200 and the latest puNES build:

https://github.com/punesemu/puNES/assets/6733770/8e0a19e3-3ca7-410a-8cc1-2cef72d215f5

I've reinstalled some drivers on the AMD laptop and the puNES performance is now better, but recording videos with the D3D9 build still causes a high CPU usage (over 20%, while the OpenGL version stays under 10%) and the output is still not smooth:

https://github.com/punesemu/puNES/assets/6733770/5e35e4da-1ba5-402f-b5a1-18167a97cd7b

Also, if I try to record another game after making a video on this laptop, it outputs a file with no video track. It just records the audio. I have to restart puNES to create a new video.

If you can't reproduce any of these issues, maybe it's better not to spend any more time on this. People affected by it can just use OpenGL instead.

**Comment by punesemu** [comment]
>Also, if I try to record another game after making a video on this laptop, the D3D9 build outputs a file with no video track. It just records the audio. I have to restart puNES to create a new video.

Fixed with [c360583](https://github.com/punesemu/puNES/commit/c3605836cadcf0d25c107b5477e060eb8c20f19e).

**Comment by punesemu** [comment]
Hi André, can you test this [version](https://www.dropbox.com/s/y02hhe1hsg68elb/punes.zip?dl=1)?

**Comment by punesemu** [comment]
Updated the [version](https://www.dropbox.com/s/y02hhe1hsg68elb/punes.zip?dl=1).

**Comment by anewuser** [comment]
I tried the new v0.111 release and the executable on Dropbox, and both output glitchy videos like the example on #373.

The OpenGL version still works.
