### ISSUE TITLE
Mapper 422 ( and variants): At least 1 cart has broken graphics

### ISSUE THREAD

**Issue by negativeExponent** [punesemu/puNES#367]
![2024-01-30T13:05:18,523239303+08:00](https://github.com/punesemu/puNES/assets/54053706/1b192c68-2a6c-4e7e-98e2-9834e2a7832d)

chr needs updating:
https://www.nesdev.org/wiki/NES_2.0_Mapper_534
rom for convenience (just remove when your done with test): 
[(AB-199) AB 一簇 10-in-1.nes.zip](https://github.com/punesemu/puNES/files/14093034/AB-199.AB.10-in-1.nes.zip)

**Comment by negativeExponent** [comment]
it appears that the update broke some mapper 422 boards and both in 126(there's only 2 carts). so not sure what NRS' notes about this change since its already on nesdev.

**Comment by punesemu** [comment]
Thanks for the report, I missed the note on bit 5. You are right by inverting bit 5 there are problems with the chr in some dumps 422 and the two 126 but it could depend on what is reported in the note on nesdev `Older dumps do not take this inversion into account.`. To make everything work I can recognize which dumps need inversion to manage them.

**Comment by negativeExponent** [comment]
ic. i missed that last note of the inverted bit (took the glance, never read it whole). thanks for the clarification. so older dumps are bad then.

**Comment by punesemu** [comment]
I have integrated the inversion of bit 5 by disabling it for the old dumps in order to still make them playable.
