### ISSUE TITLE
How do I integrate puNES's audio generation into my Godot game?

### ISSUE THREAD

**Issue by Abdullah-Ajeebi** [punesemu/puNES#371]
How do I integrate puNES's audio generation into my Godot game?

**Comment by punesemu** [comment]
Hi Abdullah-Ajeebi, sorry but I don't understand what you mean. To generate the audio I emulate the NES [APU](https://www.nesdev.org/wiki/APU) which is driven by the game code running through the NES [CPU](https://www.nesdev.org/wiki/CPU) emulation.

**Comment by punesemu** [comment]
To fork on github this is the [documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo), while if you want to clone the repository with git you can do it with the command `git clone https://github.com/punesemu/puNES`, regarding Godot, I'm sorry but I can't help you, I don't know him and I don't know how it works.
