### ISSUE TITLE
Is video recording working ?

### ISSUE THREAD

**Issue by Chipsum** [punesemu/puNES#373]
Hi.
I was reviewing the translation, I had to record a video to see how translation is, but I discovered that it's not working for me.
I am using the latest artifact
https://github.com/punesemu/puNES/actions/runs/7970782065/artifacts/1258796368

Tried all formats, they are all **black** except mp4 which is glitchy

https://github.com/punesemu/puNES/assets/37517008/6158cf50-9a11-479d-84be-75006de1d55c

**Comment by punesemu** [comment]
Which version are you using? Linux? Windows? 32 bit? 64 bit? D3D9? OpenGL?

**Comment by Chipsum** [comment]
@punesemu last artifact I did put the link above.
it's w64 D3D9

**Comment by punesemu** [comment]
Can you try with OpenGL version?

**Comment by Chipsum** [comment]
@punesemu Yep it works fine with OpenGL.

**Comment by punesemu** [comment]
I'm curious, can you try with version 0.110 D3D9?

**Comment by Chipsum** [comment]
Not working.
So it does have something to do with my end I think...

**Comment by punesemu** [comment]
Read this issue #366, it's similar to this. It may depend on the video card driver and its compatibility with Directx9. Unfortunately, if I cannot reproduce the problem it is extremely difficult to debug it.

**Comment by Chipsum** [comment]
Yeah Fabio I know it's difficult without reproducing, in a matter of fact I was just checking my Arabic translation for the next release then got myself with the issue of the video.
I will read #366 and try to find also what's going on on my end.
With that being said, I will close the issue and come back with another one later if it was an issue.
I apologize for the wasted time too.
🙏

**Comment by punesemu** [comment]
You didn't waste my time and I thank you again for the translation.

**Comment by Chipsum** [comment]
You know that you don't need to thank me for that, Your work is wonderful and I thought at least I must give back to community.
Well done Fabio! really well done ! :)

**Comment by punesemu** [comment]
Hi Chipsum, can you test this [version](https://www.dropbox.com/s/y02hhe1hsg68elb/punes.zip?dl=1)?

**Comment by punesemu** [comment]
Updated the [version](https://www.dropbox.com/s/y02hhe1hsg68elb/punes.zip?dl=1).

**Comment by Chipsum** [comment]
@punesemu Yes Fabio it's working ! :D
