### ISSUE TITLE
[0-to-X (USA) (Numbered Edition) (Aftermarket) (Unl)] Illegal opcode...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [punesemu/puNES#374]
punes 0.111 - 64 Bits - d3d9

![image](https://github.com/punesemu/puNES/assets/12481242/f9cd425a-6af2-4176-b963-a769238b6af7)

**Comment by Chipsum** [comment]
Works fine with me, Probably a corrupt ROM.
![image](https://github.com/punesemu/puNES/assets/37517008/b10d1f49-52ee-4461-a2d0-dbf4f3b3999f)

**Comment by BenjaminSiskoo** [comment]
I tried anotyehr rom, same results to me : 0-to-X (USA) (Numbered Edition) (Aftermarket) (Unl)

**Comment by BenjaminSiskoo** [comment]
Thanks for your help

It looks like the same ?!?

![image](https://github.com/punesemu/puNES/assets/12481242/4ccc4920-47b0-4b6d-964e-7d4180f56559)

**Comment by punesemu** [comment]
Hi, can you send me the rom?

**Comment by Chipsum** [comment]
Use this to provide your ROM's hash:
https://www.romhacking.net/hash/

Mine is:
```
Database match: not found
Database: No-Intro: Nintendo Entertainment System (v. 20210216-231042)
File SHA-1: 481908F1BE3C9A0FA53212F7C3A19293824EB08A
File CRC32: 57B99EE9
ROM SHA-1: 814C557007967B76452ED3532440EE5DEFF9AA96
ROM CRC32: B72EC677
```

```
Platform: Nintendo Entertainment System
Format: iNES
External Header: Yes
File size: 524304 ($80010)
Rom size: 524288 ($80000)
```

```
CHR banks: 0
PRG banks: 32
Battery backed: Yes
Mapper: #111 ($6F)
Mapper name: unknown
Mirroring: horizontal
Region: NTSC
Trainer present: No
VS Unisystem: No
Placechoice 10: No
NES 2.0: No
```

**Comment by Chipsum** [comment]
This is the rom I used:
[0-to-X (USA) (Numbered Edition) (Aftermarket) (Unl).zip](https://github.com/punesemu/puNES/files/14412272/0-to-X.USA.Numbered.Edition.Aftermarket.Unl.zip)

**Comment by BenjaminSiskoo** [comment]
> Hi, can you send me the rom?

Same mail that you dens me for the translation ?

**Comment by BenjaminSiskoo** [comment]
[0-to-X (USA) (Numbered Edition) (Aftermarket) (Unl).zip](https://github.com/punesemu/puNES/files/14412276/0-to-X.USA.Numbered.Edition.Aftermarket.Unl.zip)

**Comment by Chipsum** [comment]
Your ROM did work as well 🤔

**Comment by BenjaminSiskoo** [comment]
> This is the rom I used: [0-to-X (USA) (Numbered Edition) (Aftermarket) (Unl).zip](https://github.com/punesemu/puNES/files/14412272/0-to-X.USA.Numbered.Edition.Aftermarket.Unl.zip)

Same problem illegal opcode with your rom !!!

**Comment by punesemu** [comment]
The rom works here, but I have a doubt, I see that it has 8k of PRG NVRAM, I don't want you to have a corrupt file. Delete "0-to-X (USA) (Numbered Edition) (Aftermarket) (Unl).prb" in the prb folder.

**Comment by BenjaminSiskoo** [comment]
> The rom works here, but I have a doubt, I see that it has 8k of PRG NVRAM, I don't want you to have a corrupt file. Delete "0-to-X (USA) (Numbered Edition) (Aftermarket) (Unl).prb" in the prb folder.

It works

**Comment by punesemu** [comment]
Mistery solved :+1: .

>Can I close the BR ?

Yes.

**Comment by punesemu** [comment]
Thanks to both of you for the support.

**Comment by BenjaminSiskoo** [comment]
Thanks guys
