### ISSUE TITLE
Mapper 561 typo in submapper 6/7

### ISSUE THREAD

**Issue by negativeExponent** [punesemu/puNES#375]
submapper 6 support is broken. PRG bank is suppose to be from the latch (m561.reg} instead of prg regs.

```
memmap_auto_wp_8k(0, MMCPU(0x8000), m561.reg & 0x0F, TRUE, wr);
memmap_auto_wp_8k(0, MMCPU(0xA000), m561.reg >> 4, TRUE, wr);
```
instead of
```
memmap_auto_wp_8k(0, MMCPU(0x8000), m561.prg[0], TRUE, wr);
memmap_auto_wp_8k(0, MMCPU(0xA000), m561.prg[1], TRUE, wr);
```
submapper 7 has the same issue, but i have no roms to test it on.
this is probably a typo in nesdev's docs.

**Comment by punesemu** [comment]
Hi negativeExponent, can you send me some roms that use submapper 6? I don't have any.

**Comment by negativeExponent** [comment]
heres all the mapper 561 i have. the ones starting with Nxx should be mostly submapper 6

[mapper_561.zip](https://github.com/punesemu/puNES/files/14468742/mapper_561.zip)

**Comment by punesemu** [comment]
Many thx.

**Comment by Chipsum** [comment]
Which rom there are many, tried a lot but hard to find submapper 6

**Comment by punesemu** [comment]
Thanks Chipsum, but thanks to those sent by negativeExponent I have already found the ones that interest me.

**Comment by punesemu** [comment]
Fixed, thx for the report.
