### ISSUE TITLE
New NSFe Player: Song title scrolls outside player window

### ISSUE THREAD

**Issue by nelsonhef** [punesemu/puNES#376]
Hi, first congratulations for the new 0.111 release. The new NSFe player has a issue if the song title needs to scroll inside the player window. It doesn't start and end at edges of the player window but instead, starts and end at the edges of the application window. This happens for instance with the Ninja Gaiden NSFe as the following screenshot shows.

![Clipboard_03-02-2024_01](https://github.com/punesemu/puNES/assets/87081197/be8f0c13-6e1e-43bf-96d6-9b1cc9c6628f)

puNES version: 0.111 (release)

**Comment by Chipsum** [comment]
Same
![image](https://github.com/punesemu/puNES/assets/37517008/71adb1a2-3a74-4d4b-82f4-340646dbd95f)

**Comment by Chipsum** [comment]
Same
![image](https://github.com/punesemu/puNES/assets/37517008/e814772a-8e0a-4b6f-bd62-8bf05fac7a32)

**Comment by punesemu** [comment]
Thx for the report, can you try the new WIP?

**Comment by Chipsum** [comment]
@punesemu Fixed I think ?

https://github.com/punesemu/puNES/assets/37517008/e2ec043b-fc09-464e-a45d-12f0bf1d6a1e

**Comment by punesemu** [comment]
Thanks to your video I fixed another bug ([49586cd](https://github.com/punesemu/puNES/commit/49586cd33c5b5c9bcf3ed71ba1f820d26e59aa26)), when the song was changed part of the title of the previous song could remain in the box.
Many thx Chipsum, now I can close this issue.

**Comment by punesemu** [comment]
Many thx for the report @nelsonhef.
