### ISSUE TITLE
New NSFe Player: Can't load some song titles and wrong playlist count 

### ISSUE THREAD

**Issue by nelsonhef** [punesemu/puNES#377]
Hi!
 
puNES 0.111 and latest WIP can't load some song titles and replace them with the default "<?>" title. In the attached logs, also the "ripper" tag does not load properly.

[puNES 0110 Log.txt](https://github.com/punesemu/puNES/files/14474024/puNES.0110.Log.txt)
[puNES 0112 WIP 2264 Log.txt](https://github.com/punesemu/puNES/files/14474026/puNES.0112.WIP.2264.Log.txt)

**Comment by nelsonhef** [comment]
Also, i've spotted that the total count of songs in the playlist is always equals to "playlist + 1"

puNES 0.110
![puNES 0110](https://github.com/punesemu/puNES/assets/87081197/574ff683-e45a-4962-8403-1e4a19dd4219)

puNES 0.112 WIP
![puNES 0112 WIP 2264](https://github.com/punesemu/puNES/assets/87081197/f3bf8e6f-ed27-4f42-87d9-6cb3272eece4)

**Comment by punesemu** [comment]
Thanks for the reports, they are very useful to me. I'll take a look tomorrow to see what the problem is.

**Comment by punesemu** [comment]
Can you try the last WIP?

**Comment by nelsonhef** [comment]
It's fixed. Tried the WIP of commit f69283d with the reported NSFe and a lot of others and all loaded the metadata correctly. Thanks!
