### ISSUE TITLE
AppImage: First run wizard defaults to unwriteable config files location

### ISSUE THREAD

**Issue by nelsonhef** [punesemu/puNES#378]
Hi!

The AppImage puNES 0.110 and later first run wizard default choice for config files leads to an unwriteable folder resulting in an error. Selecting the "User profile location" works as expected. Maybe, for the AppImage, just bypass the wizard and defaults to the XDG folders directly.

OS: Linux Mint 21.3 Cinnamon

![Captura de tela de 2024-03-03 20-57-01](https://github.com/punesemu/puNES/assets/87081197/b53144fc-ccd5-4723-b96b-63addf51dba8)

![Captura de tela de 2024-03-03 21-10-13](https://github.com/punesemu/puNES/assets/87081197/4db4ab64-f72b-4bbf-b1f8-572038905554)

**Comment by punesemu** [comment]
Done, can you test the last WIP?

**Comment by nelsonhef** [comment]
Fixed with commit 1395af9. Thanks!

**Comment by punesemu** [comment]
Thank you for the report.
