### ISSUE TITLE
NSF returns Unknown OPcode F2@E002

### ISSUE THREAD

**Issue by gabricrn2** [punesemu/puNES#383]
I was testing some files and this one didn't play (it played ok in an older version):

Running_out_of_time_final.nsf by nu11

it returns me the "unknown op F2 at E002" error and doesn't play. I confirmed it can play in other players like NSFPlay.
I also couldn't compile to test this in the last main branch.

[nosound.zip](https://github.com/punesemu/puNES/files/14527142/nosound.zip)

**Comment by gabricrn2** [comment]
Tested in the WIP build. It doesnt work but the error is diferent: "Unknown op F2 at F2F2"

**Comment by punesemu** [comment]
Hi @gabricrn2, thx for the report. I managed to reproduce the problem and I'm trying to understand where it comes from.

**Comment by punesemu** [comment]
If you want, you can try the new WIP.

**Comment by gabricrn2** [comment]
It's working correctly! Thanks!
