### ISSUE TITLE
N163 sampler volume question (NSFs attached)

### ISSUE THREAD

**Issue by eugene-s-nesdev** [punesemu/puNES#389]
Hi Fabio. I find the volume balance of the N163 too loud, it is very different from the Famitracker. 
Mesen for some reason also has a very loud N163, but it has volume sliders for adjusting every extra-soundchip separately.

I don't know unfortunately what volume values real hardware has.
Maybe the problem is in Famitracker levels. 
But here are a couple of NSFs where this problem can be clearly heard:

[n163nsfs.zip](https://github.com/punesemu/puNES/files/14733999/n163nsfs.zip)

Reference videos:
https://youtu.be/N6cP4gQmpi4?si=YtkX62MY0KEYNIwD
https://youtu.be/lE967V7Zve4?si=SnPJIMQ6upVKx6i3

*update:
Rainwarrior's lastest NSFPlay (ver2.6) has default N163 volume levels like puNES and Mesen,
so i guess, this is Famitracker inaccuracy again.

**Comment by Gumball2415** [comment]
FT's mixing is based on jsr's original research, which isn't necessarily accurate when it comes with two or more chips.

Dn-FT 0.5.0.0+ has a new setting that applies NSFe `mixe` standard which is based on NSFPlay's default values. to enable, go to Module properties -> Hardware-based mixing

**Comment by punesemu** [comment]
Hi @eugene-s-nesdev, sorry if I'm only replying now. I took a look but I found the levels correct, in the uncertainty I think I will leave them like this.

**Comment by eugene-s-nesdev** [comment]
Hi Fabio, I sure your levels are correct (they're same as Mesen and NSFPlay), so it's Famitracker issue.
