### ISSUE TITLE
m176: submapper1 issue in new dumps

### ISSUE THREAD

**Issue by negativeExponent** [punesemu/puNES#394]
submapper1 is incorrect in some newer dumps.

https://github.com/punesemu/puNES/blob/e1516fcefe3dcc9710ae85cce0f536fd2d9fdcd6/src/core/mappers/mapper_176.c#L216
this should be
`if ((mode == 0) && ext) {`

ditto (but no ext check)
https://github.com/punesemu/puNES/blob/e1516fcefe3dcc9710ae85cce0f536fd2d9fdcd6/src/core/mappers/mapper_176.c#L226

then 500xreg[0] is initialized to back to zero like it was before.

**Comment by punesemu** [comment]
Hi @negativeExponent, please can you send me some of these new dumps?

**Comment by negativeExponent** [comment]
here:
[m176_new.zip](https://github.com/punesemu/puNES/files/14943040/m176_new.zip)

it should be the games in the alternate menu

**Comment by punesemu** [comment]
As usual, thank you @negativeExponent.
