### ISSUE TITLE
TAS System; Where is it?

### ISSUE THREAD

**Issue by ChessMan14** [punesemu/puNES#397]
After looking through the source code of this repo, I've seen numerous pieces of code that refer to a TAS system and support for fm2 files. However, I can see nowhere in the application where you can select a tas file or any options to restart a movie, pause playback etc. Am I just being stupid or has this simply not been fully implemented yet?

**Comment by punesemu** [comment]
Hi @ChessMan14 sorry if I'm only answering now, you can start the fm2 files directly by loading them from the "File->Open" menu.

**Comment by ChessMan14** [comment]
Ok thank you, I see how it works now. On a side note, the tas desyncs very quickly. This may be due to the tas being made on a old fceux version (2.2.3).

**Comment by ChessMan14** [comment]
Today I tested the tas system with the newest version of fceux and it worked
