### ISSUE TITLE
Xbox One Controller wont work. 

### ISSUE THREAD

**Issue by Lee91x** [punesemu/puNES#40]
In the Input Configuration , It see's the controller as 'js0: Controller (Xbox One For Windows) but
i can't map any keys. 

Xbox 360/One controller have a dedicated API called 'XINPUT',  Why is the Windows build
missing this crucial API .    I don't want to use my Xbox One Controller with DINPUT or SDL
as they are buggy on Windows 10.

**Comment by punesemu** [comment]
You have tried the WIP version?

**Comment by Lee91x** [comment]
0.101 WIP doesn't work either, due to lack of Xinput

**Comment by jcdenton2k** [comment]
Lee, I don't know what your issue is but my Logitech F310 (in Xinput Mode) works fine with both D3D9 and SDL 64-bit and 32-bit builds.
Make sure you have the Xbox drivers installed from Microsoft as well.  They help.

**Comment by punesemu** [comment]
Added full support for the XInput https://github.com/punesemu/puNES/commit/e7226c67675487a12d3c20fc05c3b473b83e95ce. Try the new WIP.
