### ISSUE TITLE
Famicom Network Controller (HVC-051)

### ISSUE THREAD

**Issue by upintheairsheep** [punesemu/puNES#400]
The Famicom Network Controller is essentially an overclocked Famicom controller with 16 extra buttons, which is pretty easy to implement, given that no emulator supports it. [Reverse engineering work](https://www.raphnet.net/divers/famicom_network_controller_hvc_051/index_en.php).

**Comment by negativeExponent** [comment]
FCEUX already have this (not sure if it works as i dont have a rom to test it with)
https://github.com/TASEmulators/fceux/blob/master/src/input/fns.cpp

**Comment by punesemu** [comment]
Thanks for the info @upintheairsheep. By any chance, do you have a rom that could be used to test support?

**Comment by upintheairsheep** [comment]
Nevermind, already emulated.
