### ISSUE TITLE
Celeste Mario doesn't run // MMC5 accuracy issue

### ISSUE THREAD

**Issue by UzixLS** [punesemu/puNES#402]
Celeste Mario (https://www.romhacking.net/hacks/7915/) doesn't run on latest puNES version (0.111):

![изображение](https://github.com/punesemu/puNES/assets/1556813/3d52e780-98e5-47a5-9eac-d34cca7b9484)

**Comment by punesemu** [comment]
Fixed 61406ec, I missed it when rewriting the mapper, thanks so much for the report.

**Comment by outusuke** [comment]
Is there any estimate on when we will have a new release?

**Comment by punesemu** [comment]
Unfortunately I don't have time to dedicate to the emulator at the moment but until I finish rewriting the DMA management (next month I should be able to have some free time) I don't think I'll publish a new release. In the meantime you can use the WIP or you can compile the sources updated to the latest commit.
