### ISSUE TITLE
A humble suggestion/request to allow use of shaders on top of software filters in next build

### ISSUE THREAD

**Issue by nice-useles-person** [punesemu/puNES#41]
I am not a developer but I made this account here just in order to thank you for making this great emulator. I discarded all other emulators when I found this much better in every aspect. It is amazing in its current state but there is just one request.
I wish we could enable shaders on top of Software filters. For example, I would definitely like to use xBRZ 6x to upscale the image using CPU but then apply CRT Scanlines shader to upscaled image using GPU. I have this configration in snes9x and it works really well to give a very crisp look but puNES currently allows only use of software filters or shaders one at a time. SO, Its leaves us with a choice between HD image quality and nostalgia.
I believe other people will also like the resulting graphics when they will try this. So, I hope my request is not too odd. here is a screenshot comparison of four settings from snes9x running contra 3.
1. No filter, No shader
2. Only Scanline shader
3. Only xbrz 6x filter
4. scanline shader after xbrz 6x

![no filter no sahder](https://cloud.githubusercontent.com/assets/26537640/24092467/44c53c4e-0d70-11e7-9329-8e8e5075003a.png)
![only scanline shader](https://cloud.githubusercontent.com/assets/26537640/24092468/44c9d9d4-0d70-11e7-8450-d631c9b099d8.png)
![only xbrz 6x filter](https://cloud.githubusercontent.com/assets/26537640/24092469/457d5bee-0d70-11e7-8eee-f4e3e78c2d47.png)
![scanline shader after xbrz 6x](https://cloud.githubusercontent.com/assets/26537640/24092470/4588a986-0d70-11e7-8306-3ddad472e904.png)

So, I am awaiting a response on this suggestion. Hopefully, it will not be a hard task, 
Have a Good Day...! :)

**Comment by nice-useles-person** [comment]
Here is a more clear comparison...!
![side by side comparison](https://cloud.githubusercontent.com/assets/26537640/24093003/8e9f92f8-0d73-11e7-84a3-db15a9383cce.png)

**Comment by punesemu** [comment]
What version do you use? Windows or Linux? D3D9 or OpenGL?

**Comment by nice-useles-person** [comment]
Windows 64-bit D3D version...!

**Comment by punesemu** [comment]
I've implemented the feature but I can't commit the changes because first I have to complete another thing. Probably next week.

**Comment by nice-useles-person** [comment]
Thank you very much... I am eagerly waiting...!

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/fd5625a2a00f951765c56a245ed98318848ee617
https://github.com/punesemu/puNES/commit/76999753473129fa6ae2ff4008c2e8ba947588f4

Keep in mind that some shaders are designed for an unfiltered input image (256x240), so applying them to a image manipulated by a software filter (double, triple, quadruple etc compared to the original) the results may not be the ones expected.

**Comment by nice-useles-person** [comment]
You are right but again there is always a solution...  A "Shader Scaling" option may be implemented just like in Retroarch to bring out the desirable results with almost any shader... And may be even shader stacking like retroarch can be implemented in puNES easily... But again I am not a programmer... So, Thankyou for doing this...! :)

**Comment by nice-useles-person** [comment]
You are right but again there is always a solution... A "Shader Scaling" option may be implemented just like in Retroarch to bring out the desirable results with almost any shader... or you can even consider a proper shader stacking system like retroarch... But again I am not a programmer... So, Thankyou for doing this...! :)

I tested the new build with the new configuration and it seems to be running fine and surprisingly the output is exactly as expected... :)

Here are a few screenshots from "Mitsume ga Tooru" on new puNES build for comparison, Please view them at 100% zoom level to get the true picture.

1. No filter No Shader
2. Only CRT Scanline Shader
3. Only xBRZ 6x Filter
4. xBRZ 6x and CRT Scanline Shader
5. Side by Side Comparison

![1 no filter no shader](https://cloud.githubusercontent.com/assets/26537640/25237243/877e4458-2603-11e7-9534-4df88b744a4d.png)
![2 only crt scanline shader](https://cloud.githubusercontent.com/assets/26537640/25237244/877f3f48-2603-11e7-938d-86d25e9f8f23.png)
![3 only xbrz 6x filter](https://cloud.githubusercontent.com/assets/26537640/25237242/877e3116-2603-11e7-9c65-2b8893dc9be3.png)
![4 xbrz 6x filter and crt scanline shader](https://cloud.githubusercontent.com/assets/26537640/25237245/87825dcc-2603-11e7-8fbd-1bb4dce3267e.png)
![5 side by side comparison](https://cloud.githubusercontent.com/assets/26537640/25237246/87a486ea-2603-11e7-941d-c8610ebde702.png)


There is no performance hit from using filters and shaders at the same time but even at 60 frame/sec there is quite a bit of input lag when using xBRZ 6x with or without shaders. So, I suggest to add multi-threaded versions of xBRZ filters. I have seen this implementation in a Kega Fusion rpi plugin and it practically eliminated input lag completely without any problem. I really wish someone would provide an updated 6x xBRZ v1.4 multi-threaded rpi plugin for Kega Fusion as it will benefit even more than NES graphics. Here is how it is configured in Kega Fusion interface.

![kega fusion 4xbrz mt](https://cloud.githubusercontent.com/assets/26537640/25237261/9251ab22-2603-11e7-85cd-9ff4c7a9d93e.png)
