### ISSUE TITLE
Implementation of Multi-Threaded version of xBRZ software filters to reduce latency/improve performance at higher multiplier i.e 6x xBRZ.

### ISSUE THREAD

**Issue by nice-useles-person** [punesemu/puNES#44]
First of All, I wish I could hug you for responding to my previous suggestion so quickly. I spent quite some time on the emulator today and noticed that using xBRZ 6x introduces a significant input lag even when frame rate is stable at 60 frames/second. Emulation looks smooth to play but the input delay is very unpleasant in some games.
I understand that there is a computational cost for using a high multiplier but I noticed that puNES does not create more than 9% CPU load even with xBRZ 6x filter and CRT shader enabled  on my old laptop which has a 3rd gen quad-core i7 @3.4 GHz. So, this makes me believe that the xBRZ filter is not using multiple threads to maximize the performance. I use xBRZ 6x in Snes9x and xBRZ 4x in Kega Fusion emulaor and each of them creates about 22% CPU load and there is no input delay at all. I don't know about Snes9x but Kega fusion rpi plugin for xBRZ 4x has two versions, a multi-threaded one that creates more CPU load(about 23%) and a non-Multi-threaded version that creates less CPU load(13-15%). Initially I used to prefer non-MT version for less CPU load but when I tried MT version, I instantly realized the response to input became instantaneous. The additional CPU Load is totally worth it.
Sorry for such a long boring story but the point is that these filters really improve the look of games but introduce a significant latency to the input. So, I think using a Multi-threaded version (that probably divides the image in horizontal slices equal to number of threads and assigns them each to a thread) can definitely solve this issue. I don't know if it is more easy to just replace the old xBRZ code with Multi threaded code and compile a separate build i.e "Windows x64 D3D MT" or to add Multi-Threaded versions to the existing filters menu like Kega Fusion plugins. 
![9251ab22-2603-11e7-85cd-9ff4c7a9d93e](https://cloud.githubusercontent.com/assets/26537640/25254228/f42cfb8c-263d-11e7-9e32-69a399fa1ea5.png)

So, Your kind response is awaited here...!

**Comment by punesemu** [comment]
I'll see what I can do.

**Comment by nice-useles-person** [comment]
Thanks 👍 , I will keep checking...!

**Comment by punesemu** [comment]
try the last WIP https://github.com/punesemu/puNES/commit/5ca82c51f87b57673a1371a8e9980cb76c7125f9

**Comment by nice-useles-person** [comment]
Have you implemented multit-hreaded version or done some other optimization...?

**Comment by nice-useles-person** [comment]
Thank you... I tested a few games using multi-threaded xBRZ 6x filter and curved CRT shader enabled on my laptop and I am glad to announce that it solved the input latency issue completely... Now, It does not even feel like an emulation, it feels like playing with original Famicom on a very high quality CRT Television...!
![super mario bros _000001](https://cloud.githubusercontent.com/assets/26537640/25317907/ff92b70e-289b-11e7-8411-eef9e33bf5e0.png)
