### ISSUE TITLE
Overscan option does not work in current testbuild

### ISSUE THREAD

**Issue by OrangeChicken16** [punesemu/puNES#45]
Hello I just wanted to report a bug. The overscan option does not work in fullscreen in current testbuild. Thank you and goodbye.

**Comment by punesemu** [comment]
Thanks for the report but what version do you use? Windows, Linux, D3D9, SDL, 32bit or 64bit? I did some tests on my computer and everything seems to work properly. Can you be a little more specific?

**Comment by OrangeChicken16** [comment]
I am using the 32 Bit version on Windows 7. It is when I change the overscan options to Set Borders to Left 0 and Right 0 and Turn Default Value ON and I leave it on Default

**Comment by punesemu** [comment]
I will start from the assumption that you are using the D3D9 version. The results I get with the D3D9a 32bit version are as follows:
without Overscan
![super_mario_bros_000001](https://cloud.githubusercontent.com/assets/14859058/25692297/b6dfb594-30a1-11e7-82b2-ee0e6881db13.png)

with overscan enabled (8 Up, 8 Down, 0 Left, 0 Right)
![super_mario_bros_000002](https://cloud.githubusercontent.com/assets/14859058/25692301/b9af0fa4-30a1-11e7-868b-e21fc473764a.png)
If you see the black borders up and down than the overscan works well. Unlike before, the image now has black borders (and no longer the zoomed image).

**Comment by OrangeChicken16** [comment]
Yes I am using the D3D9 version, sorry I forgot to mention that. How can I have the image fit the screen with the overscan on now? Just like before.

**Comment by punesemu** [comment]
With the new video management, for now, it's not possible.

**Comment by TesterNes** [comment]
Hello. Related to the new video management, could it be possible adding a button for old overscan method(zoomed image) as well you did it with "disable new menu management"? overscan zoomed based was the only solution I found in the other releases to get rid of an error with SDL full screen scale artefact at 256x240 native output(arcadevga).

**Comment by punesemu** [comment]
I'll see what can I do.

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/817ee40e3f454ca132ef49db6dc8803602a741ec
Try the last WIP.
