### ISSUE TITLE
hide mouse cursor option needed

### ISSUE THREAD

**Issue by jjfmz42015** [punesemu/puNES#50]
hide mouse cursor option needed.

useful with modern lightguns.

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/90bb2c59ea82cceb571549604ff1fd27a16dcdd7
You can test in the new [WIP](https://github.com/punesemu/puNES#wip)

**Comment by jjfmz42015** [comment]
Works! Thanks so much!!
