### ISSUE TITLE
Teenage Mutant Ninja Turtles (USA) graphics issue

### ISSUE THREAD

**Issue by jjfmz42015** [punesemu/puNES#53]
in Teenage Mutant Ninja Turtles (USA) during the intro, when it displays the 4 turtle tiles, corruption at top of screen.

Does not occur on FCEUX and Nestopia.

**Comment by retro-wertz** [comment]
you are looking at overscan portion(vertical in this case) where its
usually hidden on crt TV's and default cropped in fceux.

just make sure in puNES than Overscan is enabled and there is at least a
value of 8 for Up and Down in Overscan borders.
