### ISSUE TITLE
"-Fullscreen yes" or start in fullscreen causes tearing even with vsync on. 

### ISSUE THREAD

**Issue by TesterNes** [punesemu/puNES#55]
Os: Win7 64.
Graphics: AMD R9 280x. 
Punes: 0.102 win64 SDL

Vsync seems to be broken if you start the program in fullscreen mode, resulting in bad frame pacing or tearing, depending on your desktop(enabling aero)/graphic card(force vsync) configuration cause is not punes vsync anymore.
You can fix this issue manually: exit from fullscreen mode on the fly and disable/re-enable the vsync option. 
Come back to fullscreen again and see the change.

**Comment by punesemu** [comment]
I know it's been a while, but could you try the last WIP?

**Comment by punesemu** [comment]
No response.
