### ISSUE TITLE
Software Filters "NTSC XXXXXXX" shrink the width of the screen

### ISSUE THREAD

**Issue by trebor68** [punesemu/puNES#56]
Utilizing 0.102 and happening under both the SDL and D3D versions, Software Filters "NTSC XXXXXXX" shrink the width of the screen; rather, the same screen size/width should be maintained.

The narrowing of the screen occurs in a window, but even more severely fullscreen. It does not happen with the other Software Filters: Scale #X, Hq#X, xBRZ #X, and xBRZ #X MT; they do not change the size/width of the display in either a window or fullscreen. The narrowing screen width only happens with: NTSC Composite, NTSC S-Video, and NTSC RGB

**Comment by punesemu** [comment]
Fixed with https://github.com/punesemu/puNES/commit/16cf48a98c77a66e8da8a52b726e16088bce11a2
