### ISSUE TITLE
Full screen resolution vs desktop

### ISSUE THREAD

**Issue by ghost** [punesemu/puNES#59]
Needs option to set different full screen resolution vs desktop. 

Example on my 4k 55 inch tv i keep desktop at 1280x720 using shaders or scanlines at this resolution looks like a mess but at 4k much higher res looks great but dont want my desktop at 4k because everything is too tiny.

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/7666b7260732da3b3cc6158a343eb8b3e958e3ef
