### ISSUE TITLE
no fps display option

### ISSUE THREAD

**Issue by jjfmz42015** [punesemu/puNES#60]
no fps display option

**Comment by jjfmz42015** [comment]
punes doesnt seem to have a function to display frames per second. Can this be added in the future possibly?

I usually like to leave that on in emulators so I know if the system is emulating at full speed

**Comment by jjfmz42015** [comment]
or an option to show if emulation is at 100% speed?

**Comment by jjfmz42015** [comment]
I guess no chance of adding FPS?

**Comment by punesemu** [comment]
I'll do it in one of the next commits.

**Comment by jjfmz42015** [comment]
awesome. thanks!

**Comment by punesemu** [comment]
Added with https://github.com/punesemu/puNES/commit/dc7fbf3b09e6239309cb2458e0964ef128be7c15
