### ISSUE TITLE
OpenBSD

### ISSUE THREAD

**Issue by ibara** [punesemu/puNES#62]
Hi --

Thanks for making a separate branch. It's much easier to stick to one workflow instead of having to transition back and forth between the mailing lists and GitHub.

With the latest checkout, puNES compiles and and even runs fine. I played some Metroid and everything worked, including audio.

However, when quitting puNES, there's a segfault. Even building with `-O0 -g`, the backtrace is incomplete, but I'm adding it here in case it is helpful to you.

[punes.txt](https://github.com/punesemu/puNES/files/2300650/punes.txt)

**Comment by ibara** [comment]
Unfortunately this doesn't fix the problem, and the backtrace is the same.
It is possible that this is something within Qt5 itself; let me try to build with Qt4 and see if the problem still occurs.

**Comment by punesemu** [comment]
Maybe It's better that first I pass on -current. I'm still with OpenBSD 6.3 which installs the qt5-5.9.4 while in the -current there are 5.9.6. I must put myself in the same condition as yours to see if I can replicate the problem.
