### ISSUE TITLE
infringement

### ISSUE THREAD

**Issue by tecan** [punesemu/puNES#63]
im not sure but the picture of the nes controller in the controller config should have a different picture it might be infringing on the patent. remove the words nintendo and start and select and it should be ok.

**Comment by tecan** [comment]
https://ibin.co/4HgZECJRsIYY

**Comment by tecan** [comment]
also one should probably give instructions how to modify a 3rd party controller such as the usb ones on ebay by cutting out the start / select part of the sticker, and by reversing the button order of the start and select buttons for controller config(maybe a predefined controller config for legal 3rd party clones).

**Comment by tecan** [comment]
also there is a bug with the usb clone controllers that dont permit up/down left right at the same time without it sticking to a direction. pulls to the right or left and gets stuck like that.

**Comment by RokkumanX** [comment]
@punesemu 

I made some changes to the Nes_controller.svg but I had to save it as .png
This solves the infrigement problems @tecan addressed with removal of the Nintendo logo and I also replaced the fonts to Segoe UI.

![Nes_controller](https://user-images.githubusercontent.com/50436544/57979821-081be280-7a23-11e9-9f42-8805da7ba962.png)

**Comment by punesemu** [comment]
Hi RokkumanX, can you send me the SVG? I need the image in that format.

**Comment by RokkumanX** [comment]
Here you go @punesemu 

[Nes_controller.zip](https://github.com/punesemu/puNES/files/3195071/Nes_controller.zip)

**Comment by punesemu** [comment]
Sorry but your svg is empty. I tried to open it with gimp and with another image viewer and the result was identical.

**Comment by RokkumanX** [comment]
OK, I could open it in Internet Explorer and the result above came up.
Hold on, I will try to correct it.

**Comment by RokkumanX** [comment]
I'm sorry to say @punesemu that I don't know how you have made your .svg file originally, because I just saved the .svg file in your repository as a .png and worked with it in PhotoShop CS 6, saved it as .png and converted it online with an .png to .svg converter.

If you actually open the attached .svg in IE and then right click selecting View Source you'll see that the code is slightly different than your original .svg file.

I have no clue to how to fix this? And you are right it's blank in Gimp.

**Comment by RokkumanX** [comment]
@punesemu 

I installed Inkscape and created this:

[Nes_controller.zip](https://github.com/punesemu/puNES/files/3195474/Nes_controller.zip)

Looks, good and opens in Gimp fine!

**Comment by RokkumanX** [comment]
I created a pull request and the result sure looks good to me:
https://github.com/RokkumanX/puNES/blob/patch-1/src/gui/designer/pics/Nes_controller.svg

It's ready to merge at any time!

**Comment by tecan** [comment]
you need to remove the red lettering to another color or change the order of the start and select button. it should be done in code too. it was part of the patent stipulation they described what it looked like.

**Comment by RokkumanX** [comment]
I will fix this as soon as I get home @tecan
I have the right softare now so it's easy.

Thanks for the headup!

**Comment by RokkumanX** [comment]
Is this good enough @tecan 
https://github.com/RokkumanX/puNES/blob/patch-1/src/gui/designer/pics/Nes_controller.svg

![Nes_controller](https://user-images.githubusercontent.com/50436544/58030621-29fa8f80-7b1f-11e9-984d-0b8abf61a23d.png)

**Comment by punesemu** [comment]
Dark blue on dark gray is not very readable. A light color would be better.

**Comment by RokkumanX** [comment]
@punesemu 

https://github.com/RokkumanX/puNES/blob/patch-1/src/gui/designer/pics/Nes_controller.svg

![Nes_controller](https://user-images.githubusercontent.com/50436544/58073287-73d88980-7ba2-11e9-941b-f074094a8107.png)

**Comment by RokkumanX** [comment]
So what's happening guys? The only thing I have heard so far from you is things that needs to be changed and what not.

It literally feels like talking to yourself at this point.

Should I take the silence that you are so unhappy with the result that you simply won't bother answering or should I take the silence and interpret it for something good?

I know real life can be busy at times, but 5 days without any answer or feedback? Even at work I wouldn't even treat my enemies like this.

If I don't hear from you I can't know if the work I've done is good or bad and if I don't know that well then I can't do much more than talking to myself.

At least I tried and made my part fixing this....

**Comment by punesemu** [comment]
First of all, I thank you for your help and for your work, I like SVG and I will use it. As for the lack of feedback these days, it is due solely to the lack of time. As I wrote 5 days ago in another comment, during the week due to a new job I have no free time to devote to the emulator and unfortunately not even to the community, I can do it only during the weekend and it is only for this reason that I answer you only today.

**Comment by RokkumanX** [comment]
That's all I wanted to hear man, thanks a lot!

**Comment by tecan** [comment]
looks good to me thanks for working on PUNES its the best looking NES Emu i've used.

**Comment by RokkumanX** [comment]
I don't think the position of Select and Start causes any infringement problems, a lot of different controllers (non-Nintendo) use the same layout for Select and Start and I never heard Nintendo or any other company complained about it.

Swapping it around would only confuse end-users, no other controller that I have seen or laid eyes on have Start and then Select.

In every gamers mind it's Select and Start, it's not trademarked in any way.

However the old Nes_controller.svg did indeed cause infringement issues using the same colors and logo as the original controller.

The end result now is different.

**Comment by RokkumanX** [comment]
This issue can now be closed, it's been resolved since https://github.com/punesemu/puNES/commit/f326c4c9bf7df645e2b138fac23e626e7ca13156
