### ISSUE TITLE
HiDPI issue

### ISSUE THREAD

**Issue by tildearrow** [punesemu/puNES#65]
When operating puNES in a HiDPI monitor, only the bottom left side is covered by the emulator's output. The rest is transparent:

[![punesbug.png](https://i.postimg.cc/PrtgYM3X/punesbug.png)](https://postimg.cc/DmMpK13H)

**Comment by tildearrow** [comment]
Sorry for the late response.

I really doubt it is an OpenGL driver issue. I think it's more of an issue in the Qt GUI code. But here you go:

1. Arch Linux
2. KDE Plasma 5.14
3 and 4.
```
~$ glxinfo | grep OpenGL
OpenGL vendor string: X.Org
OpenGL renderer string: Radeon Vega Frontier Edition (VEGA10, DRM 3.26.0, 4.18.5-rt3-1-rt-bfq, LLVM 7.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.3.1
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.5 (Compatibility Profile) Mesa 18.3.1
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 18.3.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

**Comment by punesemu** [comment]
I can not reproduce the problem. Can you delete (or rename) the configuration file puNES.cfg which is in the /[HOME]/.puNES directory and try again?

**Comment by tildearrow** [comment]
Tried doing that. It does not work.
Here is an easy way to reproduce it:

```
QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCALE_FACTOR=2 ./src/punes
```

**Comment by punesemu** [comment]
> QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCALE_FACTOR=2 ./src/punes

Thanks, now I can reproduce the problem. I will keep you updated.

**Comment by punesemu** [comment]
You can apply this patch and test if works?
https://gist.github.com/punesemu/7555b958e94c3299d616c8fbdbf24193

**Comment by tildearrow** [comment]
This works perfectly!

**Comment by punesemu** [comment]
Fixed with https://github.com/punesemu/puNES/commit/bb64e828f72f1cd4ce5fb9ca05e89023092caede. Thx again for the report.
