### ISSUE TITLE
Graphical problem with filters

### ISSUE THREAD

**Issue by LuismaSP89** [punesemu/puNES#66]
Today I tested the new puNES v 0.103, and there´s a graphical problem with the filters. This problem started with the build from 8/18/18 as you can see in the images attached.

There is a problem with some of the sprites. You can see in the numbers, specially the zeros:

![sin titulo](https://user-images.githubusercontent.com/12205048/51188608-94d05b80-18de-11e9-82b8-0b617acb694f.jpg)
![sin titulo2](https://user-images.githubusercontent.com/12205048/51188899-28099100-18df-11e9-87f6-00a16c3c050f.jpg)
![sin titulo3](https://user-images.githubusercontent.com/12205048/51189330-1bd20380-18e0-11e9-87a6-eb7576bbe790.jpg)
![sin titulo4](https://user-images.githubusercontent.com/12205048/51189367-31dfc400-18e0-11e9-95b2-c24e978f1e83.jpg)

Using 6xbrz
Config:
[puNES.zip](https://github.com/punesemu/puNES/files/2760121/puNES.zip)

**Comment by punesemu** [comment]
Hi, thx for the report. I should have solved the problem, can you try this version? [puNES D3D9 X64](https://www.dropbox.com/s/mmzma4gyd4knli7/punes.exe?dl=0)

**Comment by LuismaSP89** [comment]
Thanks to you for your quick fix, now it works perfect ; )
Closing.
