### ISSUE TITLE
I've found 2 bugs in the latest release v0.103

### ISSUE THREAD

**Issue by xZabuzax** [punesemu/puNES#69]
Hello, I would like to report 2 bugs that I've found in the latest version v0.103 and the latest Wip release as well, I suppose most of you should be aware of this by now.

1st Bug:

The version v0.97 said this in the changelog: (eliminated the setting "Hide the mouse cursor." Now the mouse cursor is hidden automatically after two seconds of inactivity of the mouse. Appears again to mouse movement.)

However, this is not working in the latest version v0.103 and latest Wip release, the mouse cursor is not hiding anymore so I'm forced to move the cursor to the corner of the screen to hide it myself.

2nd Bug:

Pressing the "Switch Sides" hotkey while playing a NES game will pause the game and the only way to un-pause it is switching between Full Screen or Windowed. (Note: in the latest Wip release this issue is even worse because I can't un-pause the game anymore so I'm forced to restart the emulator)

**Comment by punesemu** [comment]
Hi xZabuzax, can you tell me which version do you use (x32 or x64, OpenGL or D3D9)?

**Comment by xZabuzax** [comment]
Sorry for not providing that info before, I'm using the x64 OpenGL version in Windows 7 Ultimate with Service Pack 1.

________________________________

**Comment by xZabuzax** [comment]
I've responded you in the email but I will respond here again just in case.

I'm using the x64 OpenGL version in Windows 7 Ultimate with Service Pack 1.

**Comment by punesemu** [comment]
Try this version please [punes.exe](https://www.dropbox.com/s/65hp4o57heetecj/punes.exe?dl=0).

**Comment by xZabuzax** [comment]
> Try this version please [punes.exe](https://www.dropbox.com/s/65hp4o57heetecj/punes.exe?dl=0).

I can confirm that both issues are fixed with that build. Thanks mate!

**Comment by punesemu** [comment]
Fixed with commits https://github.com/punesemu/puNES/commit/15f8bc28884c5c58f68b846fb5b2c8ac1f9ac551 and https://github.com/punesemu/puNES/commit/cb74624a80ca4cafba5bbacb3fbda31a781bae35. Thx for your report .
