### ISSUE TITLE
The "Start/Stop WAV" hotkey can't be changed, edited nor disabled

### ISSUE THREAD

**Issue by xZabuzax** [punesemu/puNES#70]
I'd like to report another bug that I forgot to mention which also happens in the new version "0.104": the "Start/Stop WAV" hotkey can't be changed, edited nor disabled so it will always be enabled, this is the only hotkey that has this issue. Even if you change or disable that hotkey in the configuration file "input.cfg" it will always reset to the default key which is "Alt+V" every time you open the emulator. BTW, I'm using "puNES win64 OpenGL".

[img]https://i.imgur.com/4r7KPR0.jpg?1[/img]
[img]https://i.imgur.com/QCZU9CU.jpg[/img]

**Comment by punesemu** [comment]
Hi xZabuzax, fixed in https://github.com/punesemu/puNES/commit/2726c9f65e82e7fc0dbadc1035e1af5a0d01df34.
Do you mind open another ticket for the other two requests?

**Comment by xZabuzax** [comment]
> Hi xZabuzax, fixed in [2726c9f](https://github.com/punesemu/puNES/commit/2726c9f65e82e7fc0dbadc1035e1af5a0d01df34).
> Do you mind open another ticket for the other two requests?

Thanks mate, I've created another ticket for those features.

I don't use Github and I don't know where I should have created that request ticket but I created it in the "Issues" tab. If that was the wrong tab to create the ticket then hopefully another person can move that ticket to the right tab.
