### ISSUE TITLE
Nuke.YKT's VRC7 instrument dump 

### ISSUE THREAD

**Issue by eugene-s-nesdev** [punesemu/puNES#71]
Instruments was dumped by NukeYKT some days ago

https://github.com/bbbradsmith/nsfplay/commit/2541a7f544d625870afcd712416d5228f95f6c61
https://github.com/bbbradsmith/nsfplay/commit/072cb73b779eb49235335486a1be5d269d36cf8f

https://github.com/TASVideos/fceux/commit/45dcb3e2426641775e89c6a984481787ffb543ab

Tech Info:
https://freenode.irclog.whitequark.org/~h~yamahasynths/2019-03-15#24228789;
https://siliconpr0n.org/archive/doku.php?id=vendor:yamaha:opl2#ym2413_instruments

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/c06e60b69ea0a46d1a95e0b5312dcc3a9f2401e6
Sorry for the "little" delay.
