### ISSUE TITLE
POP when NSF song start

### ISSUE THREAD

**Issue by eugene-s-nesdev** [punesemu/puNES#72]
1. Load NSF, it will play
2. Stop it by pressing "A"
3. Play song again by pressing "Start" - and you'll hear pop/click

**Comment by punesemu** [comment]
Hi Eugene, what a pleasure to read you. I understand what the problem is, but I don't like the solution I adopted and I need to find a better one.

**Comment by punesemu** [comment]
Fixed in https://github.com/punesemu/puNES/commit/0fa6c4a38d4a4314a823298d27b455f4a46dc023.
