### ISSUE TITLE
Deleted cheat(s) after restart puNES

### ISSUE THREAD

**Issue by slacknk** [punesemu/puNES#74]
0. Run puNES 31a490bc (0.104.14_git20190408) [Qt-5.9.6]
1. Load ROM/Game (File - Open ROM)
1. Go Settings - Cheats and add new cheat, and Save settings and close window Settings
1. Cheat active, Close punes (File - Exit)
1. After Exit/Close in dir $HOME/.puNES/cheat/ file Name_GAME.xml create
1. Run puNES and! xml-cheat_file delete =( Plz fix is it

For testing: Milon's Secret Castle (U) [!] - cheat, [example](https://github.com/libretro/libretro-database/blob/master/cht/Nintendo%20-%20Nintendo%20Entertainment%20System/Milon's%20Secret%20Castle%20(USA)%20(Game%20Genie).cht): Infinite Energy: SZNSLZSA
- And one_moment/more.info - Tried on 0.102_qt4 woks fine,

~upd ~cont.bug-menu cheat (2)
 If a game load and cheat(s) added - from this status start a new game from puNES
cheat-xml-file copy last cheat status in new cheat file ($HOME/.puNES/cheat/)

**Comment by punesemu** [comment]
Thanks for the report. I will keep you updated.

**Comment by punesemu** [comment]
Can you try this [patch](https://gist.github.com/punesemu/2e0c45a774060a3fb0f053ad87d1eccc) please?

**Comment by slacknk** [comment]
NoPrblm, Tried on 0791ff1a
> patch -p1 --verbose < ../punes_fix_save_cheats.patch

works fine, but new moment - cheats don't save last active status: 
[un]enable, I'm about

0. Run punes, Load ROM, 
1. add 2 cheat: 1_cheat - enable, 2 - unable -- puNES inform about 1 active cheat
1. RESTART emulator or RELOAD ROM in puNES (File - Last ROMs) -- all added cheats inactive
1. and in HOME$/.puNES/cheat/Name_GAME.xml for all `<cheat enabled="">`

**Comment by punesemu** [comment]
I've updated the [patch](https://gist.github.com/punesemu/2e0c45a774060a3fb0f053ad87d1eccc). Can you try this revision?

**Comment by slacknk** [comment]
thx, all works with 0791ff1a +  punes_fix_save_cheats_v2.patch

**Comment by punesemu** [comment]
Commit the fix (https://github.com/punesemu/puNES/commit/ca398d0905a7acc8fe7409d6c08220ffc36db8c7). Thx for the report and for your help.
