### ISSUE TITLE
Request: option for preventing vertical stretch in fullscreen

### ISSUE THREAD

**Issue by TCH68k** [punesemu/puNES#75]
Currently if i switch to fullscreen on 1920x1080, then it scales up the NES screen to 1152x1080, but that distorts the image. If there would be an option to prevent this and would only scale up with the specified integer scaler (e.g 4x to 1024x960), that would be great.

**Comment by TCH68k** [comment]
I made a patch for this: http://oscomp.hu/depot/punes_center_in_fullscreen.patch

Can be activated by "punes --center-in-fullscreen=yes" or setting "center in fullscreen=yes" in "punes.cfg"

**Comment by punesemu** [comment]
Hi TCH, well done with the patch. I was thinking of integrating your code into the "stretch in fullscreen" option. When enabled it would stretch the image across the screen, if not enabled the image would always be centered. What do you think about it?

**Comment by TCH68k** [comment]
I agree, that is the logical way. (I just did not wanted to break any current behaviour of the emulator, hence the approach of the patch).

**Comment by punesemu** [comment]
[This](https://gist.github.com/punesemu/7d80bb4c682cd37e1c525c8efbdbe2e2) is your lost weight patch.

**Comment by TCH68k** [comment]
Great. Thanks for including.

**Comment by punesemu** [comment]
https://github.com/punesemu/puNES/commit/008455ebf8af4af9dd62f43ff4fed888e3e44049. I beg your pardon TCH, for the hurry I forgot to thank you for the patch in the commit description.

**Comment by TCH68k** [comment]
No problem.

**Comment by punesemu** [comment]
Hi @TCH68K, in many have asked me to put the vertical stretch in the fullscreen so with the commit https://github.com/punesemu/puNES/commit/c0a4a7d4f0b99766b57bdd3db0c7b3649bdff059 I added a new option to enable the integer scaling (by default it's disabled). Enable it.

**Comment by TCH68k** [comment]
I've already noticed the commit and enabled it, but thanks for notifying me.
