### ISSUE TITLE
input delay since 0.103

### ISSUE THREAD

**Issue by TCH68k** [punesemu/puNES#78]
I'm experiencing an input delay of ~0.1 second in the current git version of puNES and also in 0.103 and 0.104. It does not appear in 0.102.

Also the delay is not seem to be immediate, but apparently it is slowly growing with the time spent in the game. After half a minute it becomes obvious.

Here is a saved state: http://oscomp.hu/depot/KabukiQF_input_delay.pns
Try to make the jumping part ahead.

**Comment by TCH68k** [comment]
This is quite bothersome; renders some timing-critical games entirely unplayable. Is there some kind of "pre-buffering" in puNES? For audio, for video, for anything...?

**Comment by punesemu** [comment]
During the week I cannot dedicate myself to the emulator. Next weekend I will try to recreate the problem to better understand the situation.

**Comment by punesemu** [comment]
I can't reproduce the problem. I tried with your save state and tried other games but I don't find any input delay with the passage of time. I would like to try using the configuration you use, could you send me the puNES.cfg?

**Comment by TCH68k** [comment]
Yes, here it is, along with input.cfg: [url]http://oscomp.hu/depot/punes_config.tar.gz[/url]

**Comment by punesemu** [comment]
I still can't reproduce the problem. Do me a favor, compile the emulator at the last commit https://github.com/punesemu/puNES/commit/0fbf1d0e636a49d5f63b4b4d17579b94d458d65a, enable the "Text on screen" and "Input display" options and visually check if you can sense the input delay.

**Comment by TCH68k** [comment]
I tried it and the controller visuals were synchron to the game. But i still sense the delay itself. I've just tried it with Mario; i pushed the LShift very quickly and my hand long left the button by the time Mario started to ascend from the ground.
However it is not consistent. I cannot find a way to reproduce it obviously, not even for myself, i just keep falling at the edges.

I will do a MM1 longplay with 0.102 and 0.105 soon and compare my errors. If they are the same, then i am imagining the entire thing. But i cannot reproduce it in 0.102 so far.

**Comment by punesemu** [comment]
What you see in the input template is exactly what is read by the CPU in the controller register $4016.

**Comment by TCH68k** [comment]
The delay definitely exists. I've just made a short video, where i tested 0.102 and 0.105-1063. In 0.102 it had no delay, in 0.105 i simply feel the difference. Also, in 0.102 i had no problems with compton running, but in 0.105 i had to disable it (see before and after 4:30), because the screen lagged. But the delay persists with or without the compositor.

The video is here: http://oscomp.hu/depot/punes_delay.mkv

**Comment by RokkumanX** [comment]
You might be on to something @TCH68k 
Can you check this issue please #81 

Ever since 103 > things have started to run bad but in 102 < things are good

Can you also reproduce the symptoms in that issue?

**Comment by punesemu** [comment]
I'll take a look at the video and keep you updated. I will also try to reproduce the problem you have with the compton.

@RokkumanX  the two issues are not linked. With the 0.103 release several things have changed in the emulator, the abandonment of the SDL, the introduction of the QOpenGLWidget for the creation of the OpenGL context, the introduction of the graphics management and the loop of the emulator, the GUI rewriting have been very significant changes that have also introduced several bugs that were partially solved in 0.104 and others in 0.105WIP. The issue we're discussing here is something that I can't replicate on my computer and that may depend on several factors.

**Comment by RokkumanX** [comment]
The only reason I thought the issues were connected was because of potential jittery/stuttery flow which I am experiencing that could cause input delays.

It happens for me with 103 >

**Comment by TCH68k** [comment]
@RokkumanX: No i have not encountered any corrupted graphical tiles, but as i noted above, i do experience other types of rendering glitches with an enabled compositor since v0.103 which are visible in my video.

@punesemu:

1. I do not know which particular option you have meant, but to be sure, here is my compton.conf and my xorg.conf:
http://oscomp.hu/depot/compton.conf
http://oscomp.hu/depot/xorg.conf

2. Yes i do. I only enabled the visual gadgets for the test runs, normally i turn all of them off.

An idea: I've been told before, that you have rewritten the entire threading system of puNES between 0.102 and 0.103; perhaps it is a thread racing issue what i am experiencing right now? Just a blind shot, but worths a shot.

**Comment by punesemu** [comment]
@RokkumanX : mine wasn't an attack on you, you were right to think so, I just explained to you why the two issues are not connected.
@TCH68k : thx for the conf, I hope to be able to reproduce the problem with this.
As for your idea, you might even be right, I'll try on some other computer hoping to see if I can sense the delay.

**Comment by punesemu** [comment]
@TCH68k can you try this patch https://gist.github.com/punesemu/2bab4349dd3e2d3141e560248b0a29a6? I don't know if it corrects your problem with the compton but surely it corrects one that I found.

**Comment by TCH68k** [comment]
Unfortunately nothing has changed. With compton enabled it is still lagging.

**Comment by punesemu** [comment]
Unfortunately we have to keep trying. Update sources to commit https://github.com/punesemu/puNES/commit/6ddc214fb476a4ae14c90c71b8e90d8bfbb9b490 then apply the patch https://gist.github.com/punesemu/2bab4349dd3e2d3141e560248b0a29a6. I've disabled gfx threading.

**Comment by TCH68k** [comment]
Again, no avail. Both the render and input lags are still persists.

**Comment by punesemu** [comment]
Ok, another try, besides having disabled the gfx thread, I have also disabled the use of internal dublebuffering, https://gist.github.com/punesemu/2bab4349dd3e2d3141e560248b0a29a6.

**Comment by TCH68k** [comment]
Still no difference, aside from the screen blinking due to the lack of double buffering.

**Comment by punesemu** [comment]
Another shot. With this patch I disabled the use of both threads: emulator loop and gfx https://gist.github.com/punesemu/2bab4349dd3e2d3141e560248b0a29a6.

**Comment by TCH68k** [comment]
No change.

In the meantime, just to test myself about the input lag, i've backported the center screen patch to 0.102 and change the defined NAME constant to puNES-old, built a different package, with different prefix, so now i have both 0.102 and 0.105-1064 installed. I also made a savestate at the same point as before in Kabuki: Quantum Fighter, but now in 0.102 to be able to load in both versions. And then i tried to make the jump section in each version. Video is here: http://oscomp.hu/depot/punes_delay.mkv

I did double check myself, so i compared the jumping parts of the video frame-by-frame. Apparently, in both versions, whenever the yellow light of button "A" starts to glow, Quantum immediately reacts in 0-2 frames. Still, i could manage to do all the jumps in 0.102 three times in a row and zero times in 0.105. Which means, even the display shows the button states delayed. The buttons get readed with a delay. I cannot show this on a video, so i cannot prove it.
One could say, that i pressed the buttons in time in 0.102 and i failed to time precisely in 0.105, but the game is "in my hand memory": i tried to do the same moves with the same timings in both cases - in fact, this is why and how i noticed this delay in the first place - otherwise i would just assume, that i pressed the button too late and would tried to press it sooner...but my hand "remembers" the length and timing of the button pressing.

Was SDL responsible for the input before? Or the input was handled by Qt4/Qt5 all the time?

**Comment by punesemu** [comment]
I used the SDL only for the OpenGL context, for the input I always used the QT4 / QT5. Meanwhile we have established that threads are not the problem. Since you also notice the problem in the 0.103 version, the thing to do would be to try all the commits between the two versions to understand which one generated it. I know it's hard work but nothing else comes to mind. If I can reproduce the problem I'll do it.

**Comment by punesemu** [comment]
Thinking about it, we could also use the xnee utility (https://www.gnu.org/software/xnee/) to save mouse and keyboard input and replay it between the two versions to see if this delay really exists.

**Comment by TCH68k** [comment]
I think our search for the culprit is over: it is the Qt5.
I've just rebuilt 0.102 with Qt5 and the delay appeared. If i run the Qt4 version, then the input delay disappears. So this input delay issue exists before 0.103 as well, but since Qt5 became sovereign since 0.103 and i have always built puNES with default options, it eluded my attention, i am sorry for that.

The screen did not lagged with compton though, but that is not surprising, since you have explained, that versions preadating 0.103 are using SDL render.

**Comment by punesemu** [comment]
Ahhh, ok then all depends from the QT5. Don't have the option to update QT5? Maybe I can't reproduce your problems because my libraries are up to date. If I remember correctly there were some problems with OpenGL solved with QT 5.10, but I could be wrong.

**Comment by TCH68k** [comment]
Not easily, due to the infinite incompetence of the Debian Team, which culminated in the adoption of systemd (and wiring it as a dependency into packages, in the most insane and unnecessary places), but their dependency handling were always undescribably terrible. For instance in Debian, you cannot just install "packagexy-dev:amd64" and "packagexy-dev:i386" together - which contains the linkable object files for the corresponding architecture - for they had to put the header files in both, thus conflicting them. Instead of separating it to "packagexy-dev-headers:all" and "packagexy-dev-objects:i386/amd64/whatever". And they still continue to do this practice, after decades and still not realizing, that it is useless. So, if you want to cross compile, you had to get the i386 devel package and extract only the objects from it and pour them among the other objects, avoiding APT/DPKG entirely...

Another eclatant example - which in fact is ontopic here - that they tend to wire in exact package versions as dependencies, making impossible to get a package from newer Debian versions. If you want to update an application, then it will require a library which does not exists in your system and cannot be installed. If you want to update a library, then updating it, will break tons of applications and other libraries. To remain ontopic: i cannot just install the Qt5 libraries from Buster or Sid, because it will only yield an endless chain of conflicts and package breakages...

Now, i can install a more up-to-date Qt5 directly to somewhere of course. I did it for a long time, but that also ended up in conflicts, because if i do not want to rebuild every single Qt5 dependent application in the repository with the new Qt5, then i have to keep 5.7.1 in the system too. And one portion of the applications will not build with the newer Qt5, if the older one is on the system. But maybe there is a way, but i just could not found it. But even if i would try, some applications will not build with the new one, even if the older one is not in the system, because they simply cannot find it, because their dependency handling (usually did by pkg-config) does not have it registered. But maybe there is a way, but i just could not found it...

I still have Qt 5.10.1 in /opt/. I just tried to build puNES with it, by adding it's paths to PATH, but puNES kept building with 5.7.1, used and registered by the system. Is there any way to override this? If yes and that would solve this problem, then maybe i would bite the bullet, eviscerate Qt5 5.7.1 from the system, along with the dependent applications and try to update to 5.10.1 or an even more up-to-date Qt5.

**Comment by punesemu** [comment]
Small guide to compile with Qt5 different from those installed in the system:
```bash
wget http://download.qt.io/archive/qt/5.12/5.12.3/submodules/qtbase-everywhere-src-5.12.3.tar.xz
tar xvfJ qtbase-everywhere-src-5.12.3.tar.xz
cd qtbase-everywhere-src-5.12.3
./configure -prefix=/opt/Qt5-5.12.3
make
make install
cd ..

wget http://download.qt.io/archive/qt/5.12/5.12.3/submodules/qtsvg-everywhere-src-5.12.3.tar.xz
tar xvfJ qtsvg-everywhere-src-5.12.3.tar.xz
cd qtsvg-everywhere-src
/opt/Qt5-5.12.3/bin/qmake
make
make install
cd ..

git clone https://github.com/punesemu/punes
cd punes
./autogen.sh
./configure --with-qt-lib=/opt/Qt5-5.12.3/lib --with-qt-bin=/opt/Qt5-5.12.3/bin --with-qt-include=/opt/Qt5-5.12.3/include
make
LD_LIBRARY_PATH=/opt/Qt5-5.12.3/lib src/punes
```

**Comment by TCH68k** [comment]
I knew how to install Qt5, what i did not know is how can i tell puNES, where it is.

I've installed the precompiled Linux amd64 of Qt5.12.3 via the online installer and told puNES it's place. I've got equivalent results: neither the screen lag, nor the input delay did not gone. Perhaps it is a Qt5 setting in my system?

**Comment by punesemu** [comment]
Sorry, I didn't mean to offend you.
Update sources to commit https://github.com/punesemu/puNES/commit/c17d672f379b58dee478ddf1c887a22940b35f62 then apply the patch https://gist.github.com/punesemu/263f5ba4f24ac6c0f2d3de4e568ce1b9.

**Comment by TCH68k** [comment]
You did not, i just elaborated further.

No change again.

However i discovered something today. I played with OpenBSD in VirtualBox6 all day and when i first compiled with your new patch, i thought you got it, because the delay was gone. But then, i started my local 0.105-1064 and the delay was gone there too. Something in VirtualBox6 fixed the delay system-wide. Entirely. I encountered this earlier, but then i did not know what could cause it, but now i think, it is VirtualBox6, because it is the second time when i run VBox and then the delay disappears.

But now, when i try to reproduce this purposely, i cannot. Whatever causes this, it must be configurable.

**Comment by TCH68k** [comment]
Okay, i finally debugged it and found the root of the cause. It was not using VirtualBox what fixed it, but using DOSBox and not DOSBox itself, but my resolution setting script.

Little explanation:
After over three decades of CRT usage, i bited the bullet and bought an ASUS VG279. It has the native resolution of 1920x1080, so most retro stuff which uses small resolutions are looks blurry on it. The solution was a script (available here: http://oscomp.hu/depot/setres) what calculates the nearest integer multiplier for aspect-correct zooming of the given screenmode and switches into that mode. Now, in my script i had the refresh rate properly set to 144 Hz, but when my desktop booted, the nVidia driver - which was set to auto - set it to 60 Hz. And that was the cause both for the input delay and the screen lag. And whenever my script ran to set the screen for StarCraft, DOSBox or whatever, it unintentionally fixed both the input delay and the screen lag in puNES.

I would say that Qt5 was innocent all along, but considering that the Qt4/SDL version of puNES worked perfectly along with a refresh rate of 60 Hz, it seems that something is still wrong with this particular Qt5 setup. I don't know if it's Qt5 itself, or puNES not sets something in Qt5 which would prevent this, but at least now we can reproduce the problem on other machines too.

**Comment by punesemu** [comment]
As for the 0.102 version, I use the same identical code for both QT4 and QT5, there is absolutely no difference but you had the problem if compiled with QT5. I'm more inclined to think it's something about QT5. Unfortunately I don't have an nvidia as a video card, I don't know how to reproduce it anyway.

**Comment by TCH68k** [comment]
You do not? I thought you are also use nVidia, since puNES have a build config option [i]with-opengl-nvidia-cg[/i], but then, you had no means to test the result of that build option, right?

**Comment by punesemu** [comment]
Cg ([Wikipedia](https://en.wikipedia.org/wiki/Cg_(programming_language))) is a high-level shading language developed by Nvidia which can be used with any video card that supports opengl.

**Comment by TCH68k** [comment]
I see, i did not know that. I thought it is a driver-specific option.

Well, then i think we cannot do more until you obtain an nVidia card. Unless you have some other ideas and instructions for me, for further testing. At least now we know what produces the problem, we only don't know why.

**Comment by punesemu** [comment]
As soon as I can test with an nvidia card I will update the issue.

**Comment by jjfmz42015** [comment]
I have a laptop with Nvidia 525m and desktop with GT730 I can run tests on if you like

**Comment by punesemu** [comment]
@jjfmz42015 thanks for the availability but in this case it's necessary for me to be able to reproduce the problem.

**Comment by jjfmz42015** [comment]
> @jjfmz42015 thanks for the availability but in this case it's necessary for me to be able to reproduce the problem.

Any time. I get a lot of fun use out of puNES and if there is any way I could ever help I would be more than glad to.

**Comment by punesemu** [comment]
I will reopen it when I have an nvidia card.
