### ISSUE TITLE
104 screen glitches

### ISSUE THREAD

**Issue by jjfmz42015** [punesemu/puNES#81]
Version 100,101,102 fine.

Now version 103 & 104. screen shows the odd glitch now and then.

good way to see it play Super Mario bros. while playing 1-1 and 1-2 the random glitching ill happen every so ofter

**Comment by RokkumanX** [comment]
Do you have any screenshots of the issue in action? Just so I have a fair idea of what to look after when I try this out.
Anything special you have to do to trigger these glitches?

**Comment by jjfmz42015** [comment]
Unfortunately not yet.
Hard to do as the glitch flashes on and off briefly.


Like a corrupt screen tile or something.

Does it with every single game. Was easiest to notice it on SUper Mario Bros and 1943.


Playing either game for 5 to 10 min will have multiple glitches.

Tested again this morning on a different machine and still 103/104 do it 102 and lower dont.

Did something change in how graphics are rendered after 102?

Ill try and make a video after and point out where to look at what time in the video.

**Comment by RokkumanX** [comment]
OK, I might be able to try this out later today. Back in the 104 WIP days I don't recall seeing these glitches but I always use the OpenGL version/build of puNES.

**Comment by RokkumanX** [comment]
There is definitely something off here, I could see small glitchy lines on/off in Super Mario Bros. and also the flow of the game felt jittery/stuttery somehow.

Very hard to document, but very easy to reproduce and this were with 105 WIP.

I will continue to test older versions like you have @jjfmz42015

**Comment by RokkumanX** [comment]
Yep 103 > is acting weird and 102 < is OK
102 is the last SDL version before OpenGL and with the old GUI system it seems.

I never tested newer versions thoroughly enough to notice this but now I can't let it go.
The glitchy lines appears occasionally but the jittery/stuttery flow happens more frequently.

I'm using basically the same options and settings from 102 < in 103 >

**Comment by RokkumanX** [comment]
According to this there is 76 commits made between 102 and 103

https://github.com/punesemu/puNES/compare/v0.102...v0.103

That narrows down this issue a little bit, but it's hard to say which of these 76 commits is the culprit.

**Comment by punesemu** [comment]
The issues https://github.com/punesemu/puNES/issues/78 is not connected to this. The graphic glitch was introduced by the commit https://github.com/punesemu/puNES/commit/862db2868a0d808eee7429bdda698a4a54e5aa50. If in src/core/cpu_inline.h you comment lines : 1069, 1075, 1076, 1077, 1078 and 1080 (1079 should not be commented), you will see that the glitch will no longer occur. Of course this is not the solution to the problem that deserves to be studied more carefully. I hope to have some free time over the weekend.

**Comment by jjfmz42015** [comment]
@RokkumanX so happy you were able to duplicate it. I only said something because I figured it might have gone un noticed. I actually used .104 a bit before noticing as crazy as that may seem now. For the time being I have been using .102 and it never happens here. I wish I knew how to help some more.

Thanks for taking the time to listen and try.

**Comment by RokkumanX** [comment]
Don't mention it, I love puNES!

It's been a part of my life for almost 6 years and I want it to be the perfect most accurate NES emulator and @punesemu is one heck of a genius to pull it off.

Hopefully this will be fixed in the near future!

**Comment by punesemu** [comment]
Nice enthusiasm and thanks for the compliments :beer:. I will correct the problem these days.

**Comment by jjfmz42015** [comment]
I love puNES here as well. Its my go to NES emu since I discovered it. Only reason I reported the bug.

Currently running .102 and happy as possible with it.

**Comment by punesemu** [comment]
Hello guys, could you try this version with games where you encountered the problem and let me know the result?
https://www.dropbox.com/s/cx98s7c4ojkr8mj/punes64_d3d9.exe?dl=0

**Comment by RokkumanX** [comment]
I will try this out tomorrow @punesemu 
I'll report back as soon as possible!

**Comment by RokkumanX** [comment]
And the results are in:

The glitchy lines appears to be gone and the jittery/stuttery flow also gone, feels like playing on 102

I tested to play through 1-1 and 1-2 in Super Mario Bros. and didn't notice anything out of the ordinary.

**Comment by punesemu** [comment]
Very good, thanks @RokkumanX

**Comment by RokkumanX** [comment]
Glad to hear that you might have solved the issue @punesemu 

Nice controller picture you got these days in Input configuration by the way :smile:

**Comment by jjfmz42015** [comment]
Just saw all this. Downloaded. Will test when I get home tonight as well.

**Comment by jjfmz42015** [comment]
its fixed!!

**Comment by punesemu** [comment]
Fixed in commit https://github.com/punesemu/puNES/commit/44767acbbc1ba6f73195dd9b6612574f841b0088.

**Comment by jjfmz42015** [comment]
Does this mean a release soon with this fix?

**Comment by jjfmz42015** [comment]
Nevermind. I'm dumb. You have a wip link on here. Thanks.
