### ISSUE TITLE
A/V micro stuttering

### ISSUE THREAD

**Issue by michal-kubicki** [punesemu/puNES#82]
- puNES 0.104 and the latest beta
- Windows 10 Pro 64bit 1903 on XPS 15 9560 i7-7700HQ 16GB RAM
- Intel driver: 26.20.100.6890
- NVIDIA driver: 430.86

After upgrading Windows to the 1903 version puNES "developed" almost perfectly recurring A/V micro stuttering. I have recorded a video, have a look at [https://youtu.be/jDwe3YvjG2U](https://youtu.be/jDwe3YvjG2U) Never mind the stuttered video/game play, that's due to screen recording software limitation. The game play is smooth but every few seconds I experience a micro stutter. I used SysGauge to monitor puNES performance. As you can see on the video, the CPU usage is low but the page fault rate is high and the micro stuttering seems to be occurring and connected to the page fault spikes. I have tested a few other games but the micro stuttering is not related to a specific game.

**Comment by punesemu** [comment]
Hi Michal, let me understand, did you have the problem before the windows upgrade? This reminds me of a similar problem that someone else found to be related to the Windows 10 game mode.

**Comment by michal-kubicki** [comment]
No I did not. I was messing with configuration but I could not track down the source of the stuttering, so I run puNES from another account. It works perfectly, no fault rate spikes. I logged back into my standard account and run the emu as an administrator. Again, it works without any problems. Finally, I have deleted punes config directory and let the emu to recreate it. I have a zip archive with the old config, if I replace the new one with the old one, I get the micro stuttering back. [Here it is](http://www.filedropper.com/punes) if you want to have a look.

**Comment by punesemu** [comment]
Probably the audio option "Buffer size factor" which in the old configuration was set to 9. The larger its value the larger the audio buffer that can lead to audio lag and sync problems with some sound cards.

**Comment by michal-kubicki** [comment]
I did change to 9 thinking it might be related to audio sync/hardware but the problem was already there.

**Comment by punesemu** [comment]
I don't see anything in your old configuration file. I tested it on my computer and it works perfectly.

**Comment by punesemu** [comment]
For now I close it, if there will be other information we can reopen it.
