### ISSUE TITLE
bad (?) NSF crashes puNES with SIGSEGV

### ISSUE THREAD

**Issue by TCH68k** [punesemu/puNES#84]
The following NSF file
http://oscomp.hu/depot/Castlevania.nsf
causes SIGSEGV in puNES. Both in 0.102 and 0.105.

The file may be corrupt, but it should not cause segmentation fault.

**Comment by punesemu** [comment]
The file is not corrupt but has a wrong extension, it should be .nsfe since it's in that format. However I have [fixed](https://github.com/punesemu/puNES/commit/ba7891a0820afecf105b7384a676a996ee77de9f) the sigfault and now I also check the case of wrong extension.

**Comment by TCH68k** [comment]
It's working.

(I've updated the hungarian translations in the meantime.)

**Comment by punesemu** [comment]
About the translation, with the commit https://github.com/punesemu/puNES/commit/b8fe62cdc0eb80015c15221c0d64f3d04494f40b I've modified the management of the translations, if you want to try the changes you have made just change the ts file and recompile the emulator to get the updated translation.

**Comment by TCH68k** [comment]
What do you mean; should i directly make changes to the TS file, or you mean you've just automated the importing of the TS from Crowdin to GitHub?

**Comment by punesemu** [comment]
No, I didn't create an automatism to import directly from crowdin. You can download the updated ts file from crowdin, copy it to src/gui/designer/translation and do the 'make'.
