### ISSUE TITLE
Request: disabling the hotkeys that I don't use

### ISSUE THREAD

**Issue by xZabuzax** [punesemu/puNES#85]
This feature is very simple, it would be nice if I can disable the hotkeys that I don't use. By default they are enabled with their default hotkey but I don't use all of them so I only want to use some hotkeys and disable the rest.

This can be fixed easily by adding a button that clears a specific hotkey or by adding a "clears all hotkey" button in the configuration window (this is much easier), once they are disabled I can just enable the ones I use by adding my specific hotkey. If an user press the "clears all hotkey" button by mistake then they can simply enable the default hotkeys by pressing the "reset to defaults" button again.

**Comment by punesemu** [comment]
Try last commit https://github.com/punesemu/puNES/commit/4eab6761c398c58ca689b68efc1de7903c681d91.

**Comment by xZabuzax** [comment]
Excellent!, this issue has been resolved, thanks mate!
