### ISSUE TITLE
Bug: Configuring the "Decimal key (.)" in the 2nd controller is not working

### ISSUE THREAD

**Issue by xZabuzax** [punesemu/puNES#86]
As the title suggest, the Decimal key never worked properly in this emulator, I use that key in the 2nd controller for "Start". If you configure it the first time it works as intended but once you quit the emulator and open it again then it doesn't work anymore.

Here's a picture of the key I'm talking about:
https://imgur.com/1gHikPO

Note: This issue has happened in all the versions of puNES including the newest version: "v0.105"

**Comment by punesemu** [comment]
Fixed with commit https://github.com/punesemu/puNES/commit/b3e4e83973a4c3e8879d24787bd050d216eb1034. WIPs will be ready when the badge near to [WIP](https://github.com/punesemu/puNES#wip--) is green.

**Comment by xZabuzax** [comment]
Thanks mate, even though this bug was minor is always nice to see them fixed.
