### ISSUE TITLE
Bug: There's a bug with the mouse cursor when you press the hotkey for "Hard Reset"

### ISSUE THREAD

**Issue by xZabuzax** [punesemu/puNES#87]
When you are in fullscreen the mouse cursor hides automatically and that's good but once you press the "Hard Reset" hotkey the game will reset but the mouse cursor will appear and won't hide automatically anymore. To hide the mouse cursor again you need to go to windowed mode and drag the mouse cursor out of the puNES window and then press the hotkey for fullscreen again.

Note: This issue is happening in the latest version: "v0.105"

**Comment by punesemu** [comment]
Fixed with commit https://github.com/punesemu/puNES/commit/cbd53ac35a9f8fb6fc52f73983181bad2d8af703. Try the last WIP.

**Comment by xZabuzax** [comment]
> Fixed with commit [cbd53ac](https://github.com/punesemu/puNES/commit/cbd53ac35a9f8fb6fc52f73983181bad2d8af703). Try the last WIP.

I can confirm that the issue is fixed in the latest WIP. Is there a way to disable that CMD window in those versions? I rather use the WIP version that has this issue fixed but that CMD window is a bit of a turn off.

I can't seem to find the option to turn it off in the configuration file.

**Comment by punesemu** [comment]
WIPs are debug versions and it's important that there is CMD window to get informations. You can always compile the emulator yourself by following the instructions on the emulator's GitHUB page (README.md) to get a version without the CMD window.

**Comment by RokkumanX** [comment]
@punesemu 

There is a possibility actually to make an option in the GUI to hide the CMD window, DeSmuME and pcsx2 have an option to hide the CMD/console window.

I don't think it would be hard to implement, and users could be able to choose whether to see it or hide it at any point.

**Comment by nice-useles-person** [comment]
I also think it is a good idea to make console window optional in both debug and release versions. The people who are technical enough to understand information in console window will hopefully be technical enough to turn on debug mode from options. This is a standard practice in many software to give an option of debug mode in settings.

**Comment by punesemu** [comment]
I'll think about it. For now I can consider this issue closed.

**Comment by punesemu** [comment]
I integrated the AppVeyour service that allows me to automatically compile the WIP versions as soon as I commit to github, I won't have to worry about doing it manually any more, the new WIPs don't have the debug window, you can download and use those for now.

**Comment by xZabuzax** [comment]
> I integrated the AppVeyour service that allows me to automatically compile the WIP versions as soon as I commit to github, I won't have to worry about doing it manually any more, the new WIPs don't have the debug window, you can download and use those for now.

Excellent, thanks mate!
