### ISSUE TITLE
No more linux native version?

### ISSUE THREAD

**Issue by mrdeathjr28** [punesemu/puNES#88]
Since some before releases dont appear punes native

punes native come back?

**Comment by punesemu** [comment]
It's easy to compile the sources but if you have difficulties I can help you. Write me here (or if you prefer, in private) any doubt or question.

**Comment by mrdeathjr28** [comment]
@punesemu 

main issue for compile in my case is qt dependencies because punes ask for more updated qt libs compared default qt libs with ubuntu 18.04

**Comment by punesemu** [comment]
Why do you say this? What problems do you have during the compilation? The 32bit windows version are compiled with QT 5.6.3 without problems.

**Comment by punesemu** [comment]
Also on the virtual machine where I made some test with OpenBSD, the QT are precisely the 5.9 and also in this case compile the emulator smoothly.

**Comment by mrdeathjr28** [comment]
@punesemu because dont found qt libraries (64bit build), however is possible compile sdl version?

**Comment by punesemu** [comment]
But did you install the qt5 development packages and the build-essential packages? 
```bash
# sudo apt install build-essential qtbase5-dev
```
I'm sorry but there is no longer an SDL version. If you could give me more information I could help you.

**Comment by punesemu** [comment]
I've updated the last comment with **nvidia-cg-toolkit** package that I've forgotten and with the fix of typo **'apt'** with **'apt-get'**,

**Comment by mrdeathjr28** [comment]
dont work but dont matter for now works with wine

**Comment by punesemu** [comment]
Ok, I think I finally understood your problem. I installed ubuntu 18.04 on a virtual machine and to correctly compile the emulator I did the following steps.
```bash
# sudo apt-get install git
# git clone https://github.com/punesemu/puNES
# sudo apt-get install autotools-dev autoconf build-essential pkg-config libasound2-dev qtbase5-dev qttools5-dev-tools libqt5svg5-dev nvidia-cg-toolkit
# cd puNES
# ./autogen.sh
# ./configure
# make
```
It has compiled everything without errors and to start the emulator
```bash
# ./src/punes
```

**Comment by mrdeathjr28** [comment]
@punesemu 

Many thanks compiled without issues
