### ISSUE TITLE
puNES saves screenshots erroneously if the scaling is bigger than 2x

### ISSUE THREAD

**Issue by TCH68k** [punesemu/puNES#89]
As the title says: if i save a screenshot with a scaling bigger than 2x, then puNES will save an image with the coorect zoom level, but with still with the 2x scaling dimensions, cropping everything but only what fits in, starting from the lower left corner.

Example images: http://oscomp.hu/depot/Toki_punes_screenshots.zip

**Comment by punesemu** [comment]
Please, try with this patch https://gist.github.com/punesemu/b819da3f358e05006a23d0f49a9279d5.

**Comment by TCH68k** [comment]
The bad positioning and cropping is definitely fixed.

However, if we are in fullscreen mode, then puNES saves the rest of the screen into the screenshot too, not just the actual NES screen. While this is not directly a bug, i think puNES should detect during screenshotting, that it is in fullscreen mode and should crop the unneeded vast blackness around the real content.

**Comment by punesemu** [comment]
yes, this behavior is normal. The screenshot is of the entire surface I use (which also includes on-screen vverlay text).

**Comment by punesemu** [comment]
Fixed in https://github.com/punesemu/puNES/commit/1a18daa24fcfba2f4cfb284d2703cd2f1bb3778d.
