### ISSUE TITLE
Feature request: option for saving screenshots always in the original size

### ISSUE THREAD

**Issue by TCH68k** [punesemu/puNES#90]
As we discussed previously, puNES currently always saves the entire rendering surface into the screenshot. However, it would be great to have an option which would force the emulator to save the original image, before the upscaling and filtering.

**Comment by punesemu** [comment]
So, if I understand correctly, you would like a screenshot of the real NES screen (256x240 pixels), right?

**Comment by TCH68k** [comment]
Yes, exactly.

**Comment by punesemu** [comment]
Something like this https://gist.github.com/punesemu/64af575c3ed7676db86e516d2214d329?

**Comment by TCH68k** [comment]
Yes, exactly what i have thought. Great work, thank you.
