### ISSUE TITLE
Cursors+LCtrl combination is no longer working

### ISSUE THREAD

**Issue by TCH68k** [punesemu/puNES#92]
I use cursors for directions and LShift/LCtrl for A/B. Now, even if i disable the rewind hotkeys, by writing NULL into the config file for them, still, i cannot use LCtrl+Left/Right together; the emulator simply does not react to the cursors, it only accepts the LCtrl alone.

I've traced down the introduction of this problem to this commit: https://github.com/punesemu/puNES/commit/f8461f0382918478533ac2620bd1d501d6ce0f91
After that, it became impossible to use LCtrl with cursor buttons at the same time.

**Comment by punesemu** [comment]
Try this patch https://gist.github.com/punesemu/b16290252962ff5a56b4e659cd728462.

**Comment by TCH68k** [comment]
It works, you can consider this fixed.

**Comment by punesemu** [comment]
Commit https://github.com/punesemu/puNES/commit/0dcdd867b7174314e7ecf54fd9e1d71e1c4b269a.
