### ISSUE TITLE
Feature Request: Save State/Load State GUI

### ISSUE THREAD

**Issue by xZabuzax** [punesemu/puNES#93]
This is a feature that is available in the Mac/Os X version of Snes9X and isn't available anywhere else. The only emulator that has a feature somewhat similar are PPSSPP and Zsnes (this one looks plain ugly though) but the implementation of Snes9X is far better than those ones. I know I'm asking a lot but it would be cool having more emulators with a feature similar to that one.

This is the feature I'm talking about:
https://imgur.com/a/em3USoV

**Comment by punesemu** [comment]
Even if with a little delay:
![save_slot_overlay](https://user-images.githubusercontent.com/14859058/133590544-91c9c039-42d2-43b0-8428-0e754298f54e.png)
