### ISSUE TITLE
Tabulator button handling is broken

### ISSUE THREAD

**Issue by TCH68k** [punesemu/puNES#94]
Commit https://github.com/punesemu/puNES/commit/f8461f0382918478533ac2620bd1d501d6ce0f91
has broken the handling of the TAB button.

I use TAB as P1K Select, but now the following happens instead of P1K Select: the Tab jumps out of the game and begins to select between the timeline/rewind functions and also does something with the emulation itself, because if the game tries to play the demo, then a small piece of demoplay is visible for a shard-second and then back to the main menu. Same in Balloon Fight and Road Fighter.

**Comment by punesemu** [comment]
Fixed in https://github.com/punesemu/puNES/commit/4f4f2ff6a6e10979f1c204baf98d57bf2dca9cf9.

**Comment by TCH68k** [comment]
Confirmed, thank you.
