### ISSUE TITLE
Ganbare Goemon Gaiden 2 - Tenka no Zaihou (J)

### ISSUE THREAD

**Issue by RVITHWVLL** [punesemu/puNES#95]
Is this an emulator thing or translation, because translated version of Ganbare Goemon Gaiden 2 - Tenka no Zaihou (J) works fine on Nestopia(only if you apply patch through emulator) and puNES just brokes the screen when I do it.

![Новый точечный рисунок](https://user-images.githubusercontent.com/54093010/62995652-2a7a9c00-be6a-11e9-976a-04120b752c50.png)

**Comment by punesemu** [comment]
Fixed with https://github.com/punesemu/puNES/commit/b38b0bd62b0e14129d89f8af50ab0e25cdb0fb6f. Try the last [WIPS](https://github.com/punesemu/puNES#wip-builds--).

**Comment by RVITHWVLL** [comment]
Works fine with D3D9 build. Thanks.
