### ISSUE TITLE
puNES always forgets working directory when saving savestate to a file

### ISSUE THREAD

**Issue by TCH68k** [punesemu/puNES#96]
If i save a state to a file, i navigate to the directory i want to save the file into. However, next time, when i tell puNES to save the state to a file, then i have to navigate to the directory again, as the emulator forgot what was the directory where i saved my last state and opens my home directory again.

Loading a save state from a file is not affected by this, puNES remembers the last used directory.

**Comment by punesemu** [comment]
As always, thx for the report.
