### ISSUE TITLE
Punes cant use my keybord

### ISSUE THREAD

**Issue by JERUKA9** [punesemu/puNES#99]
Im adding screen 

![punes](https://user-images.githubusercontent.com/3436198/77243569-bb3d0580-6c0b-11ea-8986-97933432dd6e.png)

Os Xubuntu  based on Ubuntu 18.04.

Hardware : Asus K72jr.

**Comment by punesemu** [comment]
The combobox is disabled because there are no other options to choose from, being only one it's not necessary to have active control. But are you having trouble assigning keyboard keys?

**Comment by punesemu** [comment]
Closed for inactivity.
